$axure.loadCurrentPage({
  "url":"门店设置.html",
  "generationDate":new Date(1448247500475.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"975f85d670e14612ad6dc61a76b12485",
    "type":"Axure:Page",
    "name":"门店设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bfb1033a3d3a4989932e6fde9b526474",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1190,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dda09d67c3646a7a9a3aa8c3741bf77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1190,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u0.png"}},
{
          "id":"4a38071d18834893bb294e0cf5c0ad91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":79},
            "size":{
              "width":1111,
              "height":707},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6db9d2bf35044f895f210c9c7e45cea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":79},
                "size":{
                  "width":1111,
                  "height":707},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u2.png"}},
{
          "id":"5b64b15fe03d43d188902cfe235c1b7d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":155},
            "size":{
              "width":611,
              "height":479}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9480a3a9d14e4c36bd9b19b689477743",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":155},
                "size":{
                  "width":611,
                  "height":479}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u4.png"}},
{
          "id":"327cb576f5584d6cb9296929c0b6350a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":473},
            "size":{
              "width":25,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2d5693934694bce83cda7cbb3eb72c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":521,
                  "y":473},
                "size":{
                  "width":25,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u6.png"}},
{
          "id":"cc75e3dd0906458c9a68df9b60a99d2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "location":{
              "x":527,
              "y":479},
            "size":{
              "width":13,
              "height":13},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8275945d29a474aa7c0fc087189d4cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "location":{
                  "x":527,
                  "y":479},
                "size":{
                  "width":13,
                  "height":13},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u8.png"}},
{
          "id":"a8dd1a8fa1af4103ae2102d1c9ba4e1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":653,
              "y":351},
            "size":{
              "width":25,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4784F},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45977ffb5aca4aef847ebcd78272b1c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":653,
                  "y":351},
                "size":{
                  "width":25,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u10.png"}},
{
          "id":"4b0b12d534e94d639e08b46c216528e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF4784F},
            "location":{
              "x":659,
              "y":357},
            "size":{
              "width":13,
              "height":13},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4784F},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf4b0d1d44494990b33348724909d37d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF4784F},
                "location":{
                  "x":659,
                  "y":357},
                "size":{
                  "width":13,
                  "height":13},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u12.png"}},
{
          "id":"86f2fe4656b34a57938c8e7e7742a211",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":983},
            "size":{
              "width":1111,
              "height":709},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cc6d7eceac64742a7e8a718e9b0f0be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":983},
                "size":{
                  "width":1111,
                  "height":709},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u14.png"}},
{
          "id":"0fbd40f1e9544a1894e45f6bb259e32d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF36B3C,
              "opacity":1},
            "location":{
              "x":238,
              "y":1003},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ef3bc77768f4e3bac8f510e4add2f5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C,
                  "opacity":1},
                "location":{
                  "x":238,
                  "y":1003},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e930da1c3e04267884baedd100cdef4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":1028},
            "size":{
              "width":94,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u18_line.png"}},
{
          "id":"0a563fe60baf465db865bcd3b41d4a54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":354,
              "y":1005},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7c3dab1d148493b9a78c8b91b392c89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":354,
                  "y":1005},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b433e4dbc8a4a0487e9aebdc7f93c79",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":1088},
            "size":{
              "width":588,
              "height":461}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b938b307996a4f4e9db0029184eb8407",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":1088},
                "size":{
                  "width":588,
                  "height":461}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u4.png"}},
{
          "id":"dbe497adb77e495086adf19dcb71174a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":1380},
            "size":{
              "width":22,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfb6eb7db7ae4ab086773c5a774223a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":1380},
                "size":{
                  "width":22,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u23.png"}},
{
          "id":"6a4da49680ec45c9bf255b0cee45ecfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "location":{
              "x":526,
              "y":1385},
            "size":{
              "width":12,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e95942508f414e149e915176f9d279cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "location":{
                  "x":526,
                  "y":1385},
                "size":{
                  "width":12,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u25.png"}},
{
          "id":"9e90a5431f0b47a999b1324f42dccae3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":1287},
            "size":{
              "width":22,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4784F},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43d01cd5cf484393bdb2e424584fe8fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":1287},
                "size":{
                  "width":22,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u27.png"}},
{
          "id":"c0d6bee4a4a04e339b690eb3c008ddcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF4784F},
            "location":{
              "x":632,
              "y":1292},
            "size":{
              "width":12,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4784F},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19d0657e402c4b739c6d5c9a2247bf62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF4784F},
                "location":{
                  "x":632,
                  "y":1292},
                "size":{
                  "width":12,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u29.png"}},
{
          "id":"71e0adb9798148eebf4e24d2f4f5d1c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF4784F},
            "location":{
              "x":625,
              "y":1278},
            "size":{
              "width":27,
              "height":9},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4784F},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76c2b27e5bf0412ca95ee4d9f6f839e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF4784F},
                "location":{
                  "x":625,
                  "y":1278},
                "size":{
                  "width":27,
                  "height":9},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u31.png"}},
{
          "id":"f82ef2551d6f4eebbc75c7f859b96bb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF4784F},
            "location":{
              "x":594,
              "y":1257},
            "size":{
              "width":96,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4784F},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fad6fa2f0504cdc92285c020b5008f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF4784F},
                "location":{
                  "x":594,
                  "y":1257},
                "size":{
                  "width":96,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u33.png"}},
{
          "id":"ba2f1510c3dd42e78d3a63884b05ea86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF4784F,
              "opacity":1},
            "location":{
              "x":911,
              "y":1100},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce9770405bed40b3ad7b3059e371da85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F,
                  "opacity":1},
                "location":{
                  "x":911,
                  "y":1100},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7837ba415394099937a79608d2b5c8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":908,
              "y":1057},
            "size":{
              "width":115,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"470bb9bf9e8b4ac996ffa80b9c6900ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":908,
                  "y":1057},
                "size":{
                  "width":115,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d6907bd01ee4c82931f17ad2f50af9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF4784F,
              "opacity":1},
            "location":{
              "x":911,
              "y":1154},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52c94471fac843a38aae5450902f4c1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F,
                  "opacity":1},
                "location":{
                  "x":911,
                  "y":1154},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72a1ef539ff84298b12d19c85ac9d1b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF4784F,
              "opacity":1},
            "location":{
              "x":911,
              "y":1204},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4934e81669004d37ad167806fb246c8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F,
                  "opacity":1},
                "location":{
                  "x":911,
                  "y":1204},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7053700c4564ef689ef42226a5e7a21",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":911,
              "y":1126},
            "size":{
              "width":249,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u43_line.png"}},
{
          "id":"c07858c5f932411c92b237c1e98518dd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":911,
              "y":1180},
            "size":{
              "width":249,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u43_line.png"}},
{
          "id":"6c000a47bc0743208f9edb365e2466dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF4784F,
              "opacity":1},
            "location":{
              "x":911,
              "y":1258},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3145cd19bb84c5e9cb8021a586cc0f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F,
                  "opacity":1},
                "location":{
                  "x":911,
                  "y":1258},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f37d84d56704f7ca1cd8b8fc05b73d9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":911,
              "y":1230},
            "size":{
              "width":249,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u43_line.png"}},
{
          "id":"daa90db0a54b4f69a2ad994a79462e4a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":911,
              "y":1284},
            "size":{
              "width":249,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u43_line.png"}},
{
          "id":"b2b75bc0217d4d34bcf660c1c42a6e2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF4784F,
              "opacity":1},
            "location":{
              "x":911,
              "y":1311},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ca4428275da46329bbe0ffaba86802b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F,
                  "opacity":1},
                "location":{
                  "x":911,
                  "y":1311},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c8e439c2c554bc18ba9cf5f20369136",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF4784F,
              "opacity":1},
            "location":{
              "x":911,
              "y":1361},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aff950c5ed424370bd0abe84013ba99b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F,
                  "opacity":1},
                "location":{
                  "x":911,
                  "y":1361},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4881a254bc0d410cba8df58e606cf7ed",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":911,
              "y":1337},
            "size":{
              "width":249,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u43_line.png"}},
{
          "id":"f9771d6ae9da4e779c277b621393fe1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF4784F,
              "opacity":1},
            "location":{
              "x":911,
              "y":1415},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22b2b6f0a732421f9909f6c59756f3b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F,
                  "opacity":1},
                "location":{
                  "x":911,
                  "y":1415},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0815378a2cf4aceb49af43ed5ff5b30",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":911,
              "y":1387},
            "size":{
              "width":249,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u43_line.png"}},
{
          "id":"387d89c1d1bd44f18282a842dc1ab49b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":911,
              "y":1441},
            "size":{
              "width":249,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u43_line.png"}},
{
          "id":"5476c7a39ea046de8d31a23e1ab5159a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF4784F,
              "opacity":1},
            "location":{
              "x":911,
              "y":1466},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75f66c0707004d9d854826aec268b7c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F,
                  "opacity":1},
                "location":{
                  "x":911,
                  "y":1466},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d3e469dd9254483bc20488401f3cb5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF4784F,
              "opacity":1},
            "location":{
              "x":911,
              "y":1516},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"648fbb33b705416fa3b57fac01df9784",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F,
                  "opacity":1},
                "location":{
                  "x":911,
                  "y":1516},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ffa22df277c49baafe6ceb37e01a818",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":911,
              "y":1492},
            "size":{
              "width":249,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u43_line.png"}},
{
          "id":"bdd5d47eb72546018937c1b108225f6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF4784F,
              "opacity":1},
            "location":{
              "x":911,
              "y":1570},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae76c5d4cc68402da9df88c8f2c7bf48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F,
                  "opacity":1},
                "location":{
                  "x":911,
                  "y":1570},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9000ab4dad5445ca2c894af7a090811",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":911,
              "y":1542},
            "size":{
              "width":249,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u43_line.png"}},
{
          "id":"a050ef12c3aa4528ac406525a75a3e08",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":911,
              "y":1596},
            "size":{
              "width":249,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u43_line.png"}},
{
          "id":"8bd73c4c6e5e4361bd65f369a79a60f4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1131,
              "y":1098},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdde99def3354390a9a35a7b9d202580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1131,
                  "y":1098},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u22.png"}},
{
          "id":"53a8db9f8c434f748e4a0cd438cf5244",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1131,
              "y":1151},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae8e04f9b8454979b8a26dff58c5790d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1131,
                  "y":1151},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u69.png"}},
{
          "id":"eb6ccfd114b34c57b7ee0b89e22455b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1131,
              "y":1204},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d512e60e6c1447b8990a0352967fe1f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1131,
                  "y":1204},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u22.png"}},
{
          "id":"11ca6987beda43b8888149559e8a4587",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1131,
              "y":1257},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"998241758216408bb76d6e8c5a3c4162",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1131,
                  "y":1257},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u69.png"}},
{
          "id":"5ea20fdcdd69465f81000ca94b7a9e9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1131,
              "y":1311},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b46420a39aba46b7a81bb3eaed68981f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1131,
                  "y":1311},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u22.png"}},
{
          "id":"7349d8ff16b543bcacfd2ec0d215f736",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1131,
              "y":1364},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2bd208cc707491fb10b54712dd71e8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1131,
                  "y":1364},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u69.png"}},
{
          "id":"95f193930e0743fdb69122def46b79d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1131,
              "y":1413},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc7b2c3f39b5423d8b9226681724dff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1131,
                  "y":1413},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u22.png"}},
{
          "id":"16c105f7884c4e1abbed3769ff895a62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1131,
              "y":1466},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccb9032b02744dfea4884e7ee22dbe6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1131,
                  "y":1466},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u69.png"}},
{
          "id":"286989bb8f2a45848bf6aa6dd76f7b0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1131,
              "y":1515},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4feb8fb13d846d49983c7048fd08c63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1131,
                  "y":1515},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u22.png"}},
{
          "id":"b591035c1fc94d1fa8e7bc2452a4a0eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1131,
              "y":1568},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25f1d39516fc4c1f95784a38f8dcd552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1131,
                  "y":1568},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u69.png"}},
{
          "id":"fd59a0229fd044f49b52dbeee38cfcd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":952,
              "y":316},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54678b6b354f4068a27ed94a86b4f91e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":952,
                  "y":316},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"563659b4e5bb4e4fb6c15e1217d2ee03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"35px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF4784F,
              "opacity":1},
            "location":{
              "x":950,
              "y":352},
            "size":{
              "width":163,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"198387b5bad2483d80d9db0b62d65e51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"35px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF4784F,
                  "opacity":1},
                "location":{
                  "x":950,
                  "y":352},
                "size":{
                  "width":163,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"587da47238b047dcb29ec2dfade17d1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5E5E5E,
              "opacity":1},
            "location":{
              "x":952,
              "y":414},
            "size":{
              "width":92,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51b3202706b74d0daf0c8a9b6e07d335",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5E5E5E,
                  "opacity":1},
                "location":{
                  "x":952,
                  "y":414},
                "size":{
                  "width":92,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4f831d5ecc94bd49d65a683fcf0e5ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5E5E5E,
              "opacity":1},
            "location":{
              "x":952,
              "y":446},
            "size":{
              "width":83,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2eaa68e7c8145be893b540306bbaec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5E5E5E,
                  "opacity":1},
                "location":{
                  "x":952,
                  "y":446},
                "size":{
                  "width":83,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cc58cb789664e0491069fcfd131c59b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF36B3C,
              "opacity":1},
            "location":{
              "x":236,
              "y":94},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb3d10362f104a3880dd6e4c1835e400",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C,
                  "opacity":1},
                "location":{
                  "x":236,
                  "y":94},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4acb841f9bad45e6bfd5115710559b44",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":118},
            "size":{
              "width":94,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u18_line.png"}},
{
          "id":"523224d741824491b9251d468352c315",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":351,
              "y":95},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f00c0284d1da4095b7b929b987487007",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":351,
                  "y":95},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d74ef6c499f4653b00d71cc96f1a58d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":944,
              "y":1626},
            "size":{
              "width":81,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a75c4c95a69a4ca380b0a74d4835ac4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":944,
                  "y":1626},
                "size":{
                  "width":81,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u100.png"}},
{
          "id":"3b2467e665cb45adbe57ea3f1a6ae347",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1035,
              "y":1626},
            "size":{
              "width":79,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c797a04a84f34f90a154789fbdbe09ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1035,
                  "y":1626},
                "size":{
                  "width":79,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u102.png"}},
{
          "id":"9c6e4ba8e3524b97aa135cd6189883fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-6},
            "size":{
              "width":808,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d10126054634ee5a5cfe80351788a39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-6},
                "size":{
                  "width":808,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u104.png"}},
{
          "id":"0076e1a9528141879ca9ca95141dbe97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1044,
              "y":25},
            "size":{
              "width":66,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49dbfe38533644d49e76373583db7e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1044,
                  "y":25},
                "size":{
                  "width":66,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u106.png"}},
{
          "id":"8e68e7d547bf434d8c1016a63015a68c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3F4A59},
            "location":{
              "x":0,
              "y":79},
            "size":{
              "width":80,
              "height":708},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c5bf0890c4741adb09f056fa87ab9c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59},
                "location":{
                  "x":0,
                  "y":79},
                "size":{
                  "width":80,
                  "height":708},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u108.png"}},
{
          "id":"6423da578442401c9b4b49fadbda89af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":78},
            "size":{
              "width":80,
              "height":511},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11222c4fd54c48c795cb3633c102ba20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":78},
                "size":{
                  "width":80,
                  "height":511},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u110.png"}},
{
          "id":"f9968dcf13f84051ac84f67ec6df19fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":79,
              "y":80},
            "size":{
              "width":140,
              "height":706},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0163e0ad31bf4639ae02932fe8b22f65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":79,
                  "y":80},
                "size":{
                  "width":140,
                  "height":706},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u112.png"}},
{
          "id":"79bc2e66a5e446e5a5de7f5245064214",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":104},
            "size":{
              "width":14,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a276d7dadac4afa9052b80137557bb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":104},
                "size":{
                  "width":14,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u114.png"}},
{
          "id":"9f5985981f1841e09bb3f6bb55902ff9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2BC589,
              "opacity":1},
            "location":{
              "x":93,
              "y":100},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1820ca782dcd4a8b938699f76639ba1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2BC589,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":100},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06405c4eab394c309f0f36fe78920349",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":93,
              "y":141},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b3f93ddab07420a83a39178db94ad05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":93,
                  "y":141},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0a5ed0b9e0d495db0ed3ef0e6304d80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":147},
            "size":{
              "width":13,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38ba8605c3254e70ab05843e7088e61e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":147},
                "size":{
                  "width":13,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u120.png"}},
{
          "id":"c91712e695f14e25a7d96c4d2dd8f01b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":899},
            "size":{
              "width":1190,
              "height":86},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d63cef6ae942433c96cded77509b621c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":899},
                "size":{
                  "width":1190,
                  "height":86},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u122.png"}},
{
          "id":"bd56b2570c984689ac5ec9eb2dc9cc78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":900},
            "size":{
              "width":808,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b74f05475714586ae9264b8683102b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":900},
                "size":{
                  "width":808,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u104.png"}},
{
          "id":"43a3a7133d8a4810a1e2a4cbbfab7109",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1045,
              "y":931},
            "size":{
              "width":66,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bed0dd2c6364d7abe4ed1b26f33fa0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1045,
                  "y":931},
                "size":{
                  "width":66,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u106.png"}},
{
          "id":"b70e2383217e454cb8eab8536afeee84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3F4A59},
            "location":{
              "x":1,
              "y":985},
            "size":{
              "width":80,
              "height":707},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3988ad5ced474ca5ad44be0ccd0f10c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59},
                "location":{
                  "x":1,
                  "y":985},
                "size":{
                  "width":80,
                  "height":707},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u128.png"}},
{
          "id":"4a91648c4ff04a30878fa579349e3ba5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":983},
            "size":{
              "width":80,
              "height":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cd71b4b62ae4262a85f3a1ed3b8fa09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":983},
                "size":{
                  "width":80,
                  "height":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u110.png"}},
{
          "id":"4ef5f638de234a248919c98c8ab0b312",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":80,
              "y":986},
            "size":{
              "width":140,
              "height":705},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1055eb6c71004df28d9a3f8636344062",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":80,
                  "y":986},
                "size":{
                  "width":140,
                  "height":705},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u132.png"}},
{
          "id":"c9c9b414b53343b69cba9730869a0efc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":189,
              "y":1010},
            "size":{
              "width":14,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb04b166a27840c1a828a66b0aeaaf6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":189,
                  "y":1010},
                "size":{
                  "width":14,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u114.png"}},
{
          "id":"722e38b95ed64d7cb2d063a3d2f9af4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2BC589,
              "opacity":1},
            "location":{
              "x":94,
              "y":1006},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76f8ed28c5394511b49c06d010b6dfee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2BC589,
                  "opacity":1},
                "location":{
                  "x":94,
                  "y":1006},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c62a926c3484f42bcf799db6275e15c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":94,
              "y":1047},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3b687ff96464aa0af45fa7e3f71f073",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":94,
                  "y":1047},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03d0dab4d7bd45d2ade8973b3cf004f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":189,
              "y":1053},
            "size":{
              "width":13,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02013930acdd4b0b91b225707998f71a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":189,
                  "y":1053},
                "size":{
                  "width":13,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u120.png"}},
{
          "id":"b5aecc74768c433e9ee3158256156f82",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":120},
            "size":{
              "width":972,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u142_line.png"}},
{
          "id":"b59480edf1f440a5a5c54745cd411665",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":1030},
            "size":{
              "width":972,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u142_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bfb1033a3d3a4989932e6fde9b526474":{
      "scriptId":"u0"},
    "6dda09d67c3646a7a9a3aa8c3741bf77":{
      "scriptId":"u1"},
    "4a38071d18834893bb294e0cf5c0ad91":{
      "scriptId":"u2"},
    "f6db9d2bf35044f895f210c9c7e45cea":{
      "scriptId":"u3"},
    "5b64b15fe03d43d188902cfe235c1b7d":{
      "scriptId":"u4"},
    "9480a3a9d14e4c36bd9b19b689477743":{
      "scriptId":"u5"},
    "327cb576f5584d6cb9296929c0b6350a":{
      "scriptId":"u6"},
    "e2d5693934694bce83cda7cbb3eb72c9":{
      "scriptId":"u7"},
    "cc75e3dd0906458c9a68df9b60a99d2a":{
      "scriptId":"u8"},
    "b8275945d29a474aa7c0fc087189d4cd":{
      "scriptId":"u9"},
    "a8dd1a8fa1af4103ae2102d1c9ba4e1a":{
      "scriptId":"u10"},
    "45977ffb5aca4aef847ebcd78272b1c3":{
      "scriptId":"u11"},
    "4b0b12d534e94d639e08b46c216528e4":{
      "scriptId":"u12"},
    "bf4b0d1d44494990b33348724909d37d":{
      "scriptId":"u13"},
    "86f2fe4656b34a57938c8e7e7742a211":{
      "scriptId":"u14"},
    "5cc6d7eceac64742a7e8a718e9b0f0be":{
      "scriptId":"u15"},
    "0fbd40f1e9544a1894e45f6bb259e32d":{
      "scriptId":"u16"},
    "2ef3bc77768f4e3bac8f510e4add2f5d":{
      "scriptId":"u17"},
    "5e930da1c3e04267884baedd100cdef4":{
      "scriptId":"u18"},
    "0a563fe60baf465db865bcd3b41d4a54":{
      "scriptId":"u19"},
    "a7c3dab1d148493b9a78c8b91b392c89":{
      "scriptId":"u20"},
    "3b433e4dbc8a4a0487e9aebdc7f93c79":{
      "scriptId":"u21"},
    "b938b307996a4f4e9db0029184eb8407":{
      "scriptId":"u22"},
    "dbe497adb77e495086adf19dcb71174a":{
      "scriptId":"u23"},
    "dfb6eb7db7ae4ab086773c5a774223a3":{
      "scriptId":"u24"},
    "6a4da49680ec45c9bf255b0cee45ecfc":{
      "scriptId":"u25"},
    "e95942508f414e149e915176f9d279cf":{
      "scriptId":"u26"},
    "9e90a5431f0b47a999b1324f42dccae3":{
      "scriptId":"u27"},
    "43d01cd5cf484393bdb2e424584fe8fb":{
      "scriptId":"u28"},
    "c0d6bee4a4a04e339b690eb3c008ddcb":{
      "scriptId":"u29"},
    "19d0657e402c4b739c6d5c9a2247bf62":{
      "scriptId":"u30"},
    "71e0adb9798148eebf4e24d2f4f5d1c7":{
      "scriptId":"u31"},
    "76c2b27e5bf0412ca95ee4d9f6f839e2":{
      "scriptId":"u32"},
    "f82ef2551d6f4eebbc75c7f859b96bb5":{
      "scriptId":"u33"},
    "8fad6fa2f0504cdc92285c020b5008f4":{
      "scriptId":"u34"},
    "ba2f1510c3dd42e78d3a63884b05ea86":{
      "scriptId":"u35"},
    "ce9770405bed40b3ad7b3059e371da85":{
      "scriptId":"u36"},
    "e7837ba415394099937a79608d2b5c8b":{
      "scriptId":"u37"},
    "470bb9bf9e8b4ac996ffa80b9c6900ee":{
      "scriptId":"u38"},
    "2d6907bd01ee4c82931f17ad2f50af9e":{
      "scriptId":"u39"},
    "52c94471fac843a38aae5450902f4c1c":{
      "scriptId":"u40"},
    "72a1ef539ff84298b12d19c85ac9d1b3":{
      "scriptId":"u41"},
    "4934e81669004d37ad167806fb246c8f":{
      "scriptId":"u42"},
    "f7053700c4564ef689ef42226a5e7a21":{
      "scriptId":"u43"},
    "c07858c5f932411c92b237c1e98518dd":{
      "scriptId":"u44"},
    "6c000a47bc0743208f9edb365e2466dd":{
      "scriptId":"u45"},
    "c3145cd19bb84c5e9cb8021a586cc0f8":{
      "scriptId":"u46"},
    "6f37d84d56704f7ca1cd8b8fc05b73d9":{
      "scriptId":"u47"},
    "daa90db0a54b4f69a2ad994a79462e4a":{
      "scriptId":"u48"},
    "b2b75bc0217d4d34bcf660c1c42a6e2e":{
      "scriptId":"u49"},
    "2ca4428275da46329bbe0ffaba86802b":{
      "scriptId":"u50"},
    "7c8e439c2c554bc18ba9cf5f20369136":{
      "scriptId":"u51"},
    "aff950c5ed424370bd0abe84013ba99b":{
      "scriptId":"u52"},
    "4881a254bc0d410cba8df58e606cf7ed":{
      "scriptId":"u53"},
    "f9771d6ae9da4e779c277b621393fe1c":{
      "scriptId":"u54"},
    "22b2b6f0a732421f9909f6c59756f3b3":{
      "scriptId":"u55"},
    "c0815378a2cf4aceb49af43ed5ff5b30":{
      "scriptId":"u56"},
    "387d89c1d1bd44f18282a842dc1ab49b":{
      "scriptId":"u57"},
    "5476c7a39ea046de8d31a23e1ab5159a":{
      "scriptId":"u58"},
    "75f66c0707004d9d854826aec268b7c1":{
      "scriptId":"u59"},
    "2d3e469dd9254483bc20488401f3cb5f":{
      "scriptId":"u60"},
    "648fbb33b705416fa3b57fac01df9784":{
      "scriptId":"u61"},
    "8ffa22df277c49baafe6ceb37e01a818":{
      "scriptId":"u62"},
    "bdd5d47eb72546018937c1b108225f6b":{
      "scriptId":"u63"},
    "ae76c5d4cc68402da9df88c8f2c7bf48":{
      "scriptId":"u64"},
    "b9000ab4dad5445ca2c894af7a090811":{
      "scriptId":"u65"},
    "a050ef12c3aa4528ac406525a75a3e08":{
      "scriptId":"u66"},
    "8bd73c4c6e5e4361bd65f369a79a60f4":{
      "scriptId":"u67"},
    "cdde99def3354390a9a35a7b9d202580":{
      "scriptId":"u68"},
    "53a8db9f8c434f748e4a0cd438cf5244":{
      "scriptId":"u69"},
    "ae8e04f9b8454979b8a26dff58c5790d":{
      "scriptId":"u70"},
    "eb6ccfd114b34c57b7ee0b89e22455b7":{
      "scriptId":"u71"},
    "d512e60e6c1447b8990a0352967fe1f8":{
      "scriptId":"u72"},
    "11ca6987beda43b8888149559e8a4587":{
      "scriptId":"u73"},
    "998241758216408bb76d6e8c5a3c4162":{
      "scriptId":"u74"},
    "5ea20fdcdd69465f81000ca94b7a9e9f":{
      "scriptId":"u75"},
    "b46420a39aba46b7a81bb3eaed68981f":{
      "scriptId":"u76"},
    "7349d8ff16b543bcacfd2ec0d215f736":{
      "scriptId":"u77"},
    "e2bd208cc707491fb10b54712dd71e8a":{
      "scriptId":"u78"},
    "95f193930e0743fdb69122def46b79d5":{
      "scriptId":"u79"},
    "fc7b2c3f39b5423d8b9226681724dff5":{
      "scriptId":"u80"},
    "16c105f7884c4e1abbed3769ff895a62":{
      "scriptId":"u81"},
    "ccb9032b02744dfea4884e7ee22dbe6e":{
      "scriptId":"u82"},
    "286989bb8f2a45848bf6aa6dd76f7b0e":{
      "scriptId":"u83"},
    "c4feb8fb13d846d49983c7048fd08c63":{
      "scriptId":"u84"},
    "b591035c1fc94d1fa8e7bc2452a4a0eb":{
      "scriptId":"u85"},
    "25f1d39516fc4c1f95784a38f8dcd552":{
      "scriptId":"u86"},
    "fd59a0229fd044f49b52dbeee38cfcd0":{
      "scriptId":"u87"},
    "54678b6b354f4068a27ed94a86b4f91e":{
      "scriptId":"u88"},
    "563659b4e5bb4e4fb6c15e1217d2ee03":{
      "scriptId":"u89"},
    "198387b5bad2483d80d9db0b62d65e51":{
      "scriptId":"u90"},
    "587da47238b047dcb29ec2dfade17d1b":{
      "scriptId":"u91"},
    "51b3202706b74d0daf0c8a9b6e07d335":{
      "scriptId":"u92"},
    "d4f831d5ecc94bd49d65a683fcf0e5ea":{
      "scriptId":"u93"},
    "c2eaa68e7c8145be893b540306bbaec0":{
      "scriptId":"u94"},
    "9cc58cb789664e0491069fcfd131c59b":{
      "scriptId":"u95"},
    "cb3d10362f104a3880dd6e4c1835e400":{
      "scriptId":"u96"},
    "4acb841f9bad45e6bfd5115710559b44":{
      "scriptId":"u97"},
    "523224d741824491b9251d468352c315":{
      "scriptId":"u98"},
    "f00c0284d1da4095b7b929b987487007":{
      "scriptId":"u99"},
    "2d74ef6c499f4653b00d71cc96f1a58d":{
      "scriptId":"u100"},
    "a75c4c95a69a4ca380b0a74d4835ac4a":{
      "scriptId":"u101"},
    "3b2467e665cb45adbe57ea3f1a6ae347":{
      "scriptId":"u102"},
    "c797a04a84f34f90a154789fbdbe09ad":{
      "scriptId":"u103"},
    "9c6e4ba8e3524b97aa135cd6189883fe":{
      "scriptId":"u104"},
    "6d10126054634ee5a5cfe80351788a39":{
      "scriptId":"u105"},
    "0076e1a9528141879ca9ca95141dbe97":{
      "scriptId":"u106"},
    "49dbfe38533644d49e76373583db7e11":{
      "scriptId":"u107"},
    "8e68e7d547bf434d8c1016a63015a68c":{
      "scriptId":"u108"},
    "2c5bf0890c4741adb09f056fa87ab9c7":{
      "scriptId":"u109"},
    "6423da578442401c9b4b49fadbda89af":{
      "scriptId":"u110"},
    "11222c4fd54c48c795cb3633c102ba20":{
      "scriptId":"u111"},
    "f9968dcf13f84051ac84f67ec6df19fb":{
      "scriptId":"u112"},
    "0163e0ad31bf4639ae02932fe8b22f65":{
      "scriptId":"u113"},
    "79bc2e66a5e446e5a5de7f5245064214":{
      "scriptId":"u114"},
    "0a276d7dadac4afa9052b80137557bb3":{
      "scriptId":"u115"},
    "9f5985981f1841e09bb3f6bb55902ff9":{
      "scriptId":"u116"},
    "1820ca782dcd4a8b938699f76639ba1a":{
      "scriptId":"u117"},
    "06405c4eab394c309f0f36fe78920349":{
      "scriptId":"u118"},
    "1b3f93ddab07420a83a39178db94ad05":{
      "scriptId":"u119"},
    "b0a5ed0b9e0d495db0ed3ef0e6304d80":{
      "scriptId":"u120"},
    "38ba8605c3254e70ab05843e7088e61e":{
      "scriptId":"u121"},
    "c91712e695f14e25a7d96c4d2dd8f01b":{
      "scriptId":"u122"},
    "d63cef6ae942433c96cded77509b621c":{
      "scriptId":"u123"},
    "bd56b2570c984689ac5ec9eb2dc9cc78":{
      "scriptId":"u124"},
    "5b74f05475714586ae9264b8683102b8":{
      "scriptId":"u125"},
    "43a3a7133d8a4810a1e2a4cbbfab7109":{
      "scriptId":"u126"},
    "1bed0dd2c6364d7abe4ed1b26f33fa0f":{
      "scriptId":"u127"},
    "b70e2383217e454cb8eab8536afeee84":{
      "scriptId":"u128"},
    "3988ad5ced474ca5ad44be0ccd0f10c8":{
      "scriptId":"u129"},
    "4a91648c4ff04a30878fa579349e3ba5":{
      "scriptId":"u130"},
    "1cd71b4b62ae4262a85f3a1ed3b8fa09":{
      "scriptId":"u131"},
    "4ef5f638de234a248919c98c8ab0b312":{
      "scriptId":"u132"},
    "1055eb6c71004df28d9a3f8636344062":{
      "scriptId":"u133"},
    "c9c9b414b53343b69cba9730869a0efc":{
      "scriptId":"u134"},
    "fb04b166a27840c1a828a66b0aeaaf6c":{
      "scriptId":"u135"},
    "722e38b95ed64d7cb2d063a3d2f9af4e":{
      "scriptId":"u136"},
    "76f8ed28c5394511b49c06d010b6dfee":{
      "scriptId":"u137"},
    "4c62a926c3484f42bcf799db6275e15c":{
      "scriptId":"u138"},
    "b3b687ff96464aa0af45fa7e3f71f073":{
      "scriptId":"u139"},
    "03d0dab4d7bd45d2ade8973b3cf004f6":{
      "scriptId":"u140"},
    "02013930acdd4b0b91b225707998f71a":{
      "scriptId":"u141"},
    "b5aecc74768c433e9ee3158256156f82":{
      "scriptId":"u142"},
    "b59480edf1f440a5a5c54745cd411665":{
      "scriptId":"u143"}}});