$axure.loadCurrentPage({
  "url":"微信菜单.html",
  "generationDate":new Date(1448119807738.83),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"57662c7d6be14c009d5c749ece321985",
    "type":"Axure:Page",
    "name":"微信菜单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"874206beffc94cd4acc61d4d4fe61f22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":201},
            "size":{
              "width":370,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f696453011d04cd491374361ef07333c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":201},
                "size":{
                  "width":370,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ac065a50fa0420fa8b8bf4cacdd7c1e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":227},
            "size":{
              "width":870,
              "height":663}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4be5cb97772542d6bc0b399d0ab134a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":227},
                "size":{
                  "width":870,
                  "height":663}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u2.png"}},
{
          "id":"25416005378a44d689682378584b64d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE0EAF6},
            "location":{
              "x":210,
              "y":110},
            "size":{
              "width":880,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0EAF6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c0bece4d59e4374b86bad6d1cd6ca7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6},
                "location":{
                  "x":210,
                  "y":110},
                "size":{
                  "width":880,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u4.png"}},
{
          "id":"373f5f4d672f415a97a4e9ae03f933b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":114},
            "size":{
              "width":330,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e60d32194f7f462fa073c557d0d8cc25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":114},
                "size":{
                  "width":330,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u6.png"}},
{
          "id":"88d2fd3b4985458ea7e3116b44552e00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Unicode MS Normal', 'Arial Unicode MS'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":18,
              "y":20},
            "size":{
              "width":102,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8736376a147d451d8f862e83af38e398",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Unicode MS Normal', 'Arial Unicode MS'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":20},
                "size":{
                  "width":102,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a072f246b3e430aa4ce97c17faec77c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":163,
              "y":42},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19d14405e15a4d37aa10a91f740ef568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":163,
                  "y":42},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4871fcedb4f74adca5db275f72433e53",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":75},
            "size":{
              "width":1190,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商家信息/u28_line.png"}},
{
          "id":"8776743212bc43efbea2c62ec7924cbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1121,
              "y":42},
            "size":{
              "width":40,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0669d2ab9274438865dffaf829dbed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1121,
                  "y":42},
                "size":{
                  "width":40,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"096f6e25bb5841c28101a18ec8597cc6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1083,
              "y":34},
            "size":{
              "width":34,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"473737a7fd9c484986b1af3576f35421",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1083,
                  "y":34},
                "size":{
                  "width":34,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u68.png"}},
{
          "id":"c94289615a884e13937b37c399a1acda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1E2631},
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":165,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ebe80bec2ef417f8a62d14ab6538f5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1E2631},
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":165,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u17.png"}},
{
          "id":"063f0b8e6ef64c3bb1e32afb2192bd13",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":125,
              "y":124},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55e862d6e6d2424da56b93961bf34cf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":124},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"bb5b71f7098842c9841d45e5de1d301a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":125,
              "y":203},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c21d387728443a2a722f28ced180b0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":203},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"1855b73df1ee4387b28a87f7d173be70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":290},
            "size":{
              "width":15,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddffc4c4bd844bd695aa90c3c5e55de4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":290},
                "size":{
                  "width":15,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三方接入/u17.png"}},
{
          "id":"b4cc78be83da4444ac3ed37bc5c93b5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":124},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7685f302bd69454faeae646cb554a435",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":124},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1f142455f67478d8a993b472a5096b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":202},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12be92fb58c8483a8901b007ac3677b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":202},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93c846b56cf445feb0037fe4dcbb7875",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":285},
            "size":{
              "width":113,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebf7d403892b4ffba8757d853a07efee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":285},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e399282842f1450c96017ddc87357a40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":357},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21e35a16bb7148be80c97d0d7f7be94d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":357},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"114e277156de4d33a3596022c10d6f73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":385},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"709b3fd094594de0ac6fd3d73919cc99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":385},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db57e2efaeee44f2b6a63d117af3b73e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":413},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0ce8a14dcb34c53a2fb3c24fb0b0e26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":413},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cb445e5b8f64192a62ee653ab3708e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":1190,
              "height":920},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6afcf633c9b4326ba6c25b48e95efe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":1190,
                  "height":920},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u37.png"}},
{
          "id":"a37c91f4168644a9ac1091efafeaeb36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":1181},
            "size":{
              "width":370,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34af8508ec854cfe8ccc64a5c51f67d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":1181},
                "size":{
                  "width":370,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"056caaed63714d4eb075475bcbeea085",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":1207},
            "size":{
              "width":870,
              "height":663}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85b1f7ab5d384efeb93b28c5eceff8a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":1207},
                "size":{
                  "width":870,
                  "height":663}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u2.png"}},
{
          "id":"210dd94070fe43f7a9f591864504ea43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE0EAF6},
            "location":{
              "x":210,
              "y":1090},
            "size":{
              "width":880,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0EAF6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"145b2a9efe9f424b86ce37b8ac960ae3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6},
                "location":{
                  "x":210,
                  "y":1090},
                "size":{
                  "width":880,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u4.png"}},
{
          "id":"900751887c0c41a58e82dcee5d9d7ac6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1094},
            "size":{
              "width":330,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc1e0a6134854bdc85a1b0e92055cbd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":1094},
                "size":{
                  "width":330,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u6.png"}},
{
          "id":"28b2c5cd89914002890086e89cdca45d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Unicode MS Normal', 'Arial Unicode MS'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":18,
              "y":1000},
            "size":{
              "width":102,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fc6dd7de9fa46e2856143d499b24fb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Unicode MS Normal', 'Arial Unicode MS'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":1000},
                "size":{
                  "width":102,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76dd205516f8445da22289d79a10d85f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":163,
              "y":1022},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"716262f4c2a449c789a7f12749372d2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":163,
                  "y":1022},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0c57afdefc84cfd8ce56b86c2843030",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1055},
            "size":{
              "width":1190,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商家信息/u28_line.png"}},
{
          "id":"982e964341f8456c9bb27155add5ce1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1121,
              "y":1022},
            "size":{
              "width":40,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2df7bf7c0094122b275a8327cd491f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1121,
                  "y":1022},
                "size":{
                  "width":40,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42bb7e18b2634f0b93e30a4f7c63166f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1083,
              "y":1014},
            "size":{
              "width":34,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"529a327021124130b4790ec735feddea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1083,
                  "y":1014},
                "size":{
                  "width":34,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u68.png"}},
{
          "id":"bef04736d836423b843b9f9a5977dad7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1E2631},
            "location":{
              "x":0,
              "y":1060},
            "size":{
              "width":165,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b69c740452f644918b8d926b676f7bfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1E2631},
                "location":{
                  "x":0,
                  "y":1060},
                "size":{
                  "width":165,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u17.png"}},
{
          "id":"10fd8b3c78034e5fa0cbf12abbfb6141",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":125,
              "y":1104},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8785f9c26440494b87becec55936659f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":1104},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"62c8d1825eed449eb0259056289274f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":125,
              "y":1183},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5e4cbb945644936b1d6a93f7eaeaab3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":1183},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"0474757b921241eea1b85bbfeaad445d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":1270},
            "size":{
              "width":15,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a36276298d644881b8901d595bf93f56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":1270},
                "size":{
                  "width":15,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三方接入/u17.png"}},
{
          "id":"9b3b0760c5cb46f3af1fa6d1a11b990a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":1104},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96b0a95803794fd08fd9536e1703cf0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1104},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0dc3566458845afb1ff8777a3abc896",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":1182},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ab8fdba63a645f5ac13e3c790ac31b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1182},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38f0be7e2877458190a673217e6b8ae0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":1265},
            "size":{
              "width":113,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b266c4168b4de8ae5e463660791fab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1265},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d8eefff4ecf405b8c77f9bb2ec321c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":1337},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a2a6847574446a998f9655510cbb129",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1337},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af93acc9a9cb4b34942b1615ef6336f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":1365},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61c4f094f8de4f74819cf28314d2f330",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1365},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ef92a99895d480e975f69d1f33dc056",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":1393},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ba172ddb7b5488abdaa0298befd1cec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1393},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f5b06eefba24472aa99372eb49f62c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":980},
            "size":{
              "width":1190,
              "height":920},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"944e1a2bbafc4d0e88a47a307d18803a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":980},
                "size":{
                  "width":1190,
                  "height":920},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u37.png"}},
{
          "id":"056926d8f6124a558251b8e695b2c825",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1250,
              "y":1101},
            "size":{
              "width":999,
              "height":678}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74bb50ab5b414ab5aedf61f05c2f5aea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1250,
                  "y":1101},
                "size":{
                  "width":999,
                  "height":678}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u78.png"}},
{
          "id":"845b462271574cfe9626d9b69e8bee5b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":1197},
            "size":{
              "width":621,
              "height":605}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98a3eec4c3504d1f9e18839e89bde299",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":1197},
                "size":{
                  "width":621,
                  "height":605}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u80.png"}},
{
          "id":"336cb431c07d41bc8726eb0127476a1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1460,
              "y":201},
            "size":{
              "width":370,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae657725d256486893f0e25f25a1c43f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1460,
                  "y":201},
                "size":{
                  "width":370,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"409426b75f2a408a8eca81de20894291",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1460,
              "y":227},
            "size":{
              "width":870,
              "height":663}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec01c5adbd8c474a97115fa455106620",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1460,
                  "y":227},
                "size":{
                  "width":870,
                  "height":663}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u2.png"}},
{
          "id":"579991bacc9140d1b008ac47c5f8fe72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE0EAF6},
            "location":{
              "x":1460,
              "y":110},
            "size":{
              "width":880,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0EAF6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4533f45638144f5db7bddaeba5e19a01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6},
                "location":{
                  "x":1460,
                  "y":110},
                "size":{
                  "width":880,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u4.png"}},
{
          "id":"9b016c6ca7b94169ae4bc67f6485afd7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1480,
              "y":114},
            "size":{
              "width":330,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9773fdcf86d54e10a3591af113f4e9b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1480,
                  "y":114},
                "size":{
                  "width":330,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u6.png"}},
{
          "id":"cbd5881e60b94d7bb7156cf037401046",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Unicode MS Normal', 'Arial Unicode MS'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1268,
              "y":20},
            "size":{
              "width":102,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4ca6fc7bffa42759b2f507ef93cc392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Unicode MS Normal', 'Arial Unicode MS'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1268,
                  "y":20},
                "size":{
                  "width":102,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ffb762585314be398027eb03d808590",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1413,
              "y":42},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f76460e766b24b6f9dc024563063691d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1413,
                  "y":42},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c48dbab3fd414c5f82825d163642ad4c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1250,
              "y":75},
            "size":{
              "width":1190,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商家信息/u28_line.png"}},
{
          "id":"07aeb1ecd0a544d38903e548f7e2abc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":2371,
              "y":42},
            "size":{
              "width":40,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"502851d594e14c798681ebfa7685d021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":2371,
                  "y":42},
                "size":{
                  "width":40,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"242e487a83f54b5494191c9d19e1dd7d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2333,
              "y":34},
            "size":{
              "width":34,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"804a388752e24a9eb5e1ff2927e8d2f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2333,
                  "y":34},
                "size":{
                  "width":34,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u68.png"}},
{
          "id":"ce6b5172ab93465ca42f1ff52ad855fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1E2631},
            "location":{
              "x":1250,
              "y":80},
            "size":{
              "width":165,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5195dd850dfb426cae6574ffe93e294b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1E2631},
                "location":{
                  "x":1250,
                  "y":80},
                "size":{
                  "width":165,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u17.png"}},
{
          "id":"c11588edeacd42d0beecfd048a350307",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1375,
              "y":124},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8cb382f41624adebf66588e28136eea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1375,
                  "y":124},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"efc577a80e9f4e8ab070ecdb4fc6752f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1375,
              "y":203},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90243465c75a4fa09257a1a630728bce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1375,
                  "y":203},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"a5ce1f67c82547319bfbb35195903488",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1379,
              "y":290},
            "size":{
              "width":15,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d41449777c742c581487abd252dc881",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1379,
                  "y":290},
                "size":{
                  "width":15,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三方接入/u17.png"}},
{
          "id":"03c03d6257614d968c7fac4e26437298",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":1272,
              "y":124},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b13c5a4536714fce967d5dc8c6227ec5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":1272,
                  "y":124},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3dde5507067a4c2b9832186cde09df13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":1272,
              "y":202},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8b374e2938149809b182bacfba4341f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":1272,
                  "y":202},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac5a46961cba4ba997beab63857974d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1272,
              "y":285},
            "size":{
              "width":113,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b777577c0cb946788c260b41ec63432c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1272,
                  "y":285},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3e1d26d6bed486585fc136b050fe6ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":1272,
              "y":357},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beb40c3f9b174bd880316ca1de75eeef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":1272,
                  "y":357},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22083b7d6f5e43ebafb39bafcbf63043",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1272,
              "y":385},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cf24dc3a2f948308fd17ae98fb0b08e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1272,
                  "y":385},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"824f5d1b47d74ed2b24ceb7528901620",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":1272,
              "y":413},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b166ddd520d4e4983ba4476be37f51e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":1272,
                  "y":413},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7521fea9f6ad42b7940375f7a509431c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1250,
              "y":0},
            "size":{
              "width":1190,
              "height":920},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a203edbb0da45abab6725e2870f71d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1250,
                  "y":0},
                "size":{
                  "width":1190,
                  "height":920},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u37.png"}},
{
          "id":"ade1ac9b59e44567927cdd81889ddde7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xBF000000},
            "location":{
              "x":1250,
              "y":0},
            "size":{
              "width":1190,
              "height":921}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a38346571134ee89007c9fdf450d239",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xBF000000},
                "location":{
                  "x":1250,
                  "y":0},
                "size":{
                  "width":1190,
                  "height":921}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u121.png"}},
{
          "id":"5ab0b876c7774672a72e8a11794eb694",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1679,
              "y":46},
            "size":{
              "width":384,
              "height":806}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d8d26883c784e2b9236db8c784f88ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1679,
                  "y":46},
                "size":{
                  "width":384,
                  "height":806}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u123.png"}},
{
          "id":"f38c516a719046ec90bffcd9758fa4dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1764,
              "y":632},
            "size":{
              "width":236,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ec247b7a0bd483b858aec3824a099cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1764,
                  "y":632},
                "size":{
                  "width":236,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u125.png"}},
{
          "id":"fe4fce353e7a4145bc704129211c3e74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1782,
              "y":638},
            "size":{
              "width":179,
              "height":32},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef970f734f13479084a731ec6ba9ebfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1782,
                  "y":638},
                "size":{
                  "width":179,
                  "height":32},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u127.png"}},
{
          "id":"9952fbd69629422e9d512beb79c0eafc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1983,
              "y":639},
            "size":{
              "width":28,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"118"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29e50e9c9bf243c4be511d2f75c53598",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1983,
                  "y":639},
                "size":{
                  "width":28,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"118"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u129.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "874206beffc94cd4acc61d4d4fe61f22":{
      "scriptId":"u0"},
    "f696453011d04cd491374361ef07333c":{
      "scriptId":"u1"},
    "6ac065a50fa0420fa8b8bf4cacdd7c1e":{
      "scriptId":"u2"},
    "4be5cb97772542d6bc0b399d0ab134a3":{
      "scriptId":"u3"},
    "25416005378a44d689682378584b64d9":{
      "scriptId":"u4"},
    "7c0bece4d59e4374b86bad6d1cd6ca7d":{
      "scriptId":"u5"},
    "373f5f4d672f415a97a4e9ae03f933b4":{
      "scriptId":"u6"},
    "e60d32194f7f462fa073c557d0d8cc25":{
      "scriptId":"u7"},
    "88d2fd3b4985458ea7e3116b44552e00":{
      "scriptId":"u8"},
    "8736376a147d451d8f862e83af38e398":{
      "scriptId":"u9"},
    "6a072f246b3e430aa4ce97c17faec77c":{
      "scriptId":"u10"},
    "19d14405e15a4d37aa10a91f740ef568":{
      "scriptId":"u11"},
    "4871fcedb4f74adca5db275f72433e53":{
      "scriptId":"u12"},
    "8776743212bc43efbea2c62ec7924cbb":{
      "scriptId":"u13"},
    "b0669d2ab9274438865dffaf829dbed3":{
      "scriptId":"u14"},
    "096f6e25bb5841c28101a18ec8597cc6":{
      "scriptId":"u15"},
    "473737a7fd9c484986b1af3576f35421":{
      "scriptId":"u16"},
    "c94289615a884e13937b37c399a1acda":{
      "scriptId":"u17"},
    "6ebe80bec2ef417f8a62d14ab6538f5b":{
      "scriptId":"u18"},
    "063f0b8e6ef64c3bb1e32afb2192bd13":{
      "scriptId":"u19"},
    "55e862d6e6d2424da56b93961bf34cf9":{
      "scriptId":"u20"},
    "bb5b71f7098842c9841d45e5de1d301a":{
      "scriptId":"u21"},
    "3c21d387728443a2a722f28ced180b0d":{
      "scriptId":"u22"},
    "1855b73df1ee4387b28a87f7d173be70":{
      "scriptId":"u23"},
    "ddffc4c4bd844bd695aa90c3c5e55de4":{
      "scriptId":"u24"},
    "b4cc78be83da4444ac3ed37bc5c93b5d":{
      "scriptId":"u25"},
    "7685f302bd69454faeae646cb554a435":{
      "scriptId":"u26"},
    "b1f142455f67478d8a993b472a5096b4":{
      "scriptId":"u27"},
    "12be92fb58c8483a8901b007ac3677b9":{
      "scriptId":"u28"},
    "93c846b56cf445feb0037fe4dcbb7875":{
      "scriptId":"u29"},
    "ebf7d403892b4ffba8757d853a07efee":{
      "scriptId":"u30"},
    "e399282842f1450c96017ddc87357a40":{
      "scriptId":"u31"},
    "21e35a16bb7148be80c97d0d7f7be94d":{
      "scriptId":"u32"},
    "114e277156de4d33a3596022c10d6f73":{
      "scriptId":"u33"},
    "709b3fd094594de0ac6fd3d73919cc99":{
      "scriptId":"u34"},
    "db57e2efaeee44f2b6a63d117af3b73e":{
      "scriptId":"u35"},
    "c0ce8a14dcb34c53a2fb3c24fb0b0e26":{
      "scriptId":"u36"},
    "6cb445e5b8f64192a62ee653ab3708e9":{
      "scriptId":"u37"},
    "c6afcf633c9b4326ba6c25b48e95efe9":{
      "scriptId":"u38"},
    "a37c91f4168644a9ac1091efafeaeb36":{
      "scriptId":"u39"},
    "34af8508ec854cfe8ccc64a5c51f67d9":{
      "scriptId":"u40"},
    "056caaed63714d4eb075475bcbeea085":{
      "scriptId":"u41"},
    "85b1f7ab5d384efeb93b28c5eceff8a4":{
      "scriptId":"u42"},
    "210dd94070fe43f7a9f591864504ea43":{
      "scriptId":"u43"},
    "145b2a9efe9f424b86ce37b8ac960ae3":{
      "scriptId":"u44"},
    "900751887c0c41a58e82dcee5d9d7ac6":{
      "scriptId":"u45"},
    "bc1e0a6134854bdc85a1b0e92055cbd5":{
      "scriptId":"u46"},
    "28b2c5cd89914002890086e89cdca45d":{
      "scriptId":"u47"},
    "0fc6dd7de9fa46e2856143d499b24fb7":{
      "scriptId":"u48"},
    "76dd205516f8445da22289d79a10d85f":{
      "scriptId":"u49"},
    "716262f4c2a449c789a7f12749372d2c":{
      "scriptId":"u50"},
    "f0c57afdefc84cfd8ce56b86c2843030":{
      "scriptId":"u51"},
    "982e964341f8456c9bb27155add5ce1e":{
      "scriptId":"u52"},
    "c2df7bf7c0094122b275a8327cd491f6":{
      "scriptId":"u53"},
    "42bb7e18b2634f0b93e30a4f7c63166f":{
      "scriptId":"u54"},
    "529a327021124130b4790ec735feddea":{
      "scriptId":"u55"},
    "bef04736d836423b843b9f9a5977dad7":{
      "scriptId":"u56"},
    "b69c740452f644918b8d926b676f7bfc":{
      "scriptId":"u57"},
    "10fd8b3c78034e5fa0cbf12abbfb6141":{
      "scriptId":"u58"},
    "8785f9c26440494b87becec55936659f":{
      "scriptId":"u59"},
    "62c8d1825eed449eb0259056289274f2":{
      "scriptId":"u60"},
    "e5e4cbb945644936b1d6a93f7eaeaab3":{
      "scriptId":"u61"},
    "0474757b921241eea1b85bbfeaad445d":{
      "scriptId":"u62"},
    "a36276298d644881b8901d595bf93f56":{
      "scriptId":"u63"},
    "9b3b0760c5cb46f3af1fa6d1a11b990a":{
      "scriptId":"u64"},
    "96b0a95803794fd08fd9536e1703cf0c":{
      "scriptId":"u65"},
    "c0dc3566458845afb1ff8777a3abc896":{
      "scriptId":"u66"},
    "8ab8fdba63a645f5ac13e3c790ac31b7":{
      "scriptId":"u67"},
    "38f0be7e2877458190a673217e6b8ae0":{
      "scriptId":"u68"},
    "20b266c4168b4de8ae5e463660791fab":{
      "scriptId":"u69"},
    "3d8eefff4ecf405b8c77f9bb2ec321c5":{
      "scriptId":"u70"},
    "4a2a6847574446a998f9655510cbb129":{
      "scriptId":"u71"},
    "af93acc9a9cb4b34942b1615ef6336f5":{
      "scriptId":"u72"},
    "61c4f094f8de4f74819cf28314d2f330":{
      "scriptId":"u73"},
    "8ef92a99895d480e975f69d1f33dc056":{
      "scriptId":"u74"},
    "1ba172ddb7b5488abdaa0298befd1cec":{
      "scriptId":"u75"},
    "7f5b06eefba24472aa99372eb49f62c5":{
      "scriptId":"u76"},
    "944e1a2bbafc4d0e88a47a307d18803a":{
      "scriptId":"u77"},
    "056926d8f6124a558251b8e695b2c825":{
      "scriptId":"u78"},
    "74bb50ab5b414ab5aedf61f05c2f5aea":{
      "scriptId":"u79"},
    "845b462271574cfe9626d9b69e8bee5b":{
      "scriptId":"u80"},
    "98a3eec4c3504d1f9e18839e89bde299":{
      "scriptId":"u81"},
    "336cb431c07d41bc8726eb0127476a1f":{
      "scriptId":"u82"},
    "ae657725d256486893f0e25f25a1c43f":{
      "scriptId":"u83"},
    "409426b75f2a408a8eca81de20894291":{
      "scriptId":"u84"},
    "ec01c5adbd8c474a97115fa455106620":{
      "scriptId":"u85"},
    "579991bacc9140d1b008ac47c5f8fe72":{
      "scriptId":"u86"},
    "4533f45638144f5db7bddaeba5e19a01":{
      "scriptId":"u87"},
    "9b016c6ca7b94169ae4bc67f6485afd7":{
      "scriptId":"u88"},
    "9773fdcf86d54e10a3591af113f4e9b5":{
      "scriptId":"u89"},
    "cbd5881e60b94d7bb7156cf037401046":{
      "scriptId":"u90"},
    "c4ca6fc7bffa42759b2f507ef93cc392":{
      "scriptId":"u91"},
    "2ffb762585314be398027eb03d808590":{
      "scriptId":"u92"},
    "f76460e766b24b6f9dc024563063691d":{
      "scriptId":"u93"},
    "c48dbab3fd414c5f82825d163642ad4c":{
      "scriptId":"u94"},
    "07aeb1ecd0a544d38903e548f7e2abc4":{
      "scriptId":"u95"},
    "502851d594e14c798681ebfa7685d021":{
      "scriptId":"u96"},
    "242e487a83f54b5494191c9d19e1dd7d":{
      "scriptId":"u97"},
    "804a388752e24a9eb5e1ff2927e8d2f3":{
      "scriptId":"u98"},
    "ce6b5172ab93465ca42f1ff52ad855fe":{
      "scriptId":"u99"},
    "5195dd850dfb426cae6574ffe93e294b":{
      "scriptId":"u100"},
    "c11588edeacd42d0beecfd048a350307":{
      "scriptId":"u101"},
    "b8cb382f41624adebf66588e28136eea":{
      "scriptId":"u102"},
    "efc577a80e9f4e8ab070ecdb4fc6752f":{
      "scriptId":"u103"},
    "90243465c75a4fa09257a1a630728bce":{
      "scriptId":"u104"},
    "a5ce1f67c82547319bfbb35195903488":{
      "scriptId":"u105"},
    "5d41449777c742c581487abd252dc881":{
      "scriptId":"u106"},
    "03c03d6257614d968c7fac4e26437298":{
      "scriptId":"u107"},
    "b13c5a4536714fce967d5dc8c6227ec5":{
      "scriptId":"u108"},
    "3dde5507067a4c2b9832186cde09df13":{
      "scriptId":"u109"},
    "b8b374e2938149809b182bacfba4341f":{
      "scriptId":"u110"},
    "ac5a46961cba4ba997beab63857974d9":{
      "scriptId":"u111"},
    "b777577c0cb946788c260b41ec63432c":{
      "scriptId":"u112"},
    "f3e1d26d6bed486585fc136b050fe6ae":{
      "scriptId":"u113"},
    "beb40c3f9b174bd880316ca1de75eeef":{
      "scriptId":"u114"},
    "22083b7d6f5e43ebafb39bafcbf63043":{
      "scriptId":"u115"},
    "3cf24dc3a2f948308fd17ae98fb0b08e":{
      "scriptId":"u116"},
    "824f5d1b47d74ed2b24ceb7528901620":{
      "scriptId":"u117"},
    "6b166ddd520d4e4983ba4476be37f51e":{
      "scriptId":"u118"},
    "7521fea9f6ad42b7940375f7a509431c":{
      "scriptId":"u119"},
    "3a203edbb0da45abab6725e2870f71d8":{
      "scriptId":"u120"},
    "ade1ac9b59e44567927cdd81889ddde7":{
      "scriptId":"u121"},
    "9a38346571134ee89007c9fdf450d239":{
      "scriptId":"u122"},
    "5ab0b876c7774672a72e8a11794eb694":{
      "scriptId":"u123"},
    "9d8d26883c784e2b9236db8c784f88ab":{
      "scriptId":"u124"},
    "f38c516a719046ec90bffcd9758fa4dc":{
      "scriptId":"u125"},
    "7ec247b7a0bd483b858aec3824a099cf":{
      "scriptId":"u126"},
    "fe4fce353e7a4145bc704129211c3e74":{
      "scriptId":"u127"},
    "ef970f734f13479084a731ec6ba9ebfc":{
      "scriptId":"u128"},
    "9952fbd69629422e9d512beb79c0eafc":{
      "scriptId":"u129"},
    "29e50e9c9bf243c4be511d2f75c53598":{
      "scriptId":"u130"}}});