$axure.loadCurrentPage({
  "url":"店员管理.html",
  "generationDate":new Date(1448247501652.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bc6b476bc5db4590a59faa378f15863b",
    "type":"Axure:Page",
    "name":"店员管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6a3bfee437d14fc4bd78febb57b2383a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":79},
            "size":{
              "width":1195,
              "height":707},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e7ff0c33aae42b5b5ba4681067b3632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":79},
                "size":{
                  "width":1195,
                  "height":707},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u0.png"}},
{
          "id":"7a25f7e961e449ddae2e1c6fe49b9a9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF36B3C,
              "opacity":1},
            "location":{
              "x":235,
              "y":91},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fc02a1a70a8445f9385c1d8caab42db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C,
                  "opacity":1},
                "location":{
                  "x":235,
                  "y":91},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"faf721084d3442269c22bfb2c35d3844",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":150},
            "size":{
              "width":107,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30ea11d6f8d14dca9b95c62868f0c315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":150},
                "size":{
                  "width":107,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u4.png"}},
{
          "id":"2068981d09fe40dbb9c4c2788356c5b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":244,
              "y":155},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c82ad2f077024e1fafe451ffb5736471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":244,
                  "y":155},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43d2bd97519d49d4aedc78ddf5506b3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":156},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f57ff646c0bb4fb9ae9a6503a9c025b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":156},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4486d2806d44cebad31a3a991f96d11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":616,
              "y":157},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4516c085d0284107ae1164bff309f672",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":616,
                  "y":157},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"293e2894e08541a892cdf2a22f0fbd69",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":150},
            "size":{
              "width":138,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"6713e02e5508479bb7da04dd7d6e35c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":815,
              "y":222},
            "size":{
              "width":94,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61c54052fc254729804c836513b154d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":815,
                  "y":222},
                "size":{
                  "width":94,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u13.png"}},
{
          "id":"65fe94523ad24d478daa8a6bcbb74f70",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":241,
              "y":279},
            "size":{
              "width":938,
              "height":104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce6269f859de40bebd26ff9d53be19bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":105,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8a395ddf9ec49d79b4d0bad144e8821",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "size":{
                      "width":105,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u16.png"}},
{
              "id":"de2ef647de0043ca8cec26e2e6d125ba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":105,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"457d993e4a814bfc94553797fa6d96b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":105,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u28.png"}},
{
              "id":"68e3e500f49044ad959d5451106a82b2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":105,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f0c8ead53c654d65afe833d4731085ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":105,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u40.png"}},
{
              "id":"904edc577cc94e2e8581af9eac6ced8b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":540,
                  "y":0},
                "size":{
                  "width":104,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"16afee59488d498382f84ae1526e9b92",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":540,
                      "y":0},
                    "size":{
                      "width":104,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u24.png"}},
{
              "id":"981fd68f13d342618b205c3ef0587c8c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":540,
                  "y":30},
                "size":{
                  "width":104,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"632567cf01db45da8bc64422d4c147ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":540,
                      "y":30},
                    "size":{
                      "width":104,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u36.png"}},
{
              "id":"7503a67386e84b849c98c9f991aa434b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":540,
                  "y":66},
                "size":{
                  "width":104,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"705112218dd44c469af37f6568b4c026",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":540,
                      "y":66},
                    "size":{
                      "width":104,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u48.png"}},
{
              "id":"259be760361b4dc7b1591ad23ca1142f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":644,
                  "y":0},
                "size":{
                  "width":294,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a4c43907e75a4fb9a20e7077643a93ff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":644,
                      "y":0},
                    "size":{
                      "width":294,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u26.png"}},
{
              "id":"9af6ea814dcf4ceb9c2e537e9084362e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":644,
                  "y":30},
                "size":{
                  "width":294,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c794b809dc4347a299e1c653c6b01f01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":644,
                      "y":30},
                    "size":{
                      "width":294,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u38.png"}},
{
              "id":"47c00e091ffd429b8fd450ab8df0afc2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":644,
                  "y":66},
                "size":{
                  "width":294,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ede75bbde30042c9863201525449b0e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":644,
                      "y":66},
                    "size":{
                      "width":294,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u50.png"}},
{
              "id":"f551b3b05c2041c484d73e60e2669774",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":105,
                  "y":0},
                "size":{
                  "width":123,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a370609836694d7aabe93edd8b42eafa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":105,
                      "y":0},
                    "size":{
                      "width":123,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u18.png"}},
{
              "id":"f547013650e64e8490fe4bc594e93301",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":105,
                  "y":30},
                "size":{
                  "width":123,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3fc7efa30c8f4c02b42ed7b1dddce73b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":105,
                      "y":30},
                    "size":{
                      "width":123,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u30.png"}},
{
              "id":"e6ceb39e2f8c419fbb1f808ddb290f1c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":105,
                  "y":66},
                "size":{
                  "width":123,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"96d9c8a0520e41f59c26c02c63535746",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":105,
                      "y":66},
                    "size":{
                      "width":123,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u42.png"}},
{
              "id":"f9fcc3497002457d93eee37585c79280",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":228,
                  "y":0},
                "size":{
                  "width":213,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ce2973bf90664258ba2e6806068410d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":228,
                      "y":0},
                    "size":{
                      "width":213,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u20.png"}},
{
              "id":"a66726e3dbf8405da125e775c76703e7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":228,
                  "y":30},
                "size":{
                  "width":213,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c1ceb2bd8f1e49ebad34ea0bdfeee8b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":228,
                      "y":30},
                    "size":{
                      "width":213,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u32.png"}},
{
              "id":"7d561c0aea78442d8289ade57c51d1c8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":228,
                  "y":66},
                "size":{
                  "width":213,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1cd44c6c2443444cad8367207986b354",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":228,
                      "y":66},
                    "size":{
                      "width":213,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u44.png"}},
{
              "id":"d1c34525ec504555b0cf5d3a767396bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":441,
                  "y":0},
                "size":{
                  "width":99,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c52e6c42b5f7419d9f43cb41f907cfed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":441,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u22.png"}},
{
              "id":"dee617cf3a5e4791b86421727b1dbe4b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":441,
                  "y":30},
                "size":{
                  "width":99,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"623c8a4e687e44a39b7487eb2177ee33",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":441,
                      "y":30},
                    "size":{
                      "width":99,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u34.png"}},
{
              "id":"ecf8005529d74d68b97eb282ea82fadc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":441,
                  "y":66},
                "size":{
                  "width":99,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"16d6598aaff340059cd387c8e306a405",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":441,
                      "y":66},
                    "size":{
                      "width":99,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u46.png"}}]},
{
          "id":"6756895e75cc46dcad0df2eb3a361494",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":962,
              "y":322},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c34a475841984caf9237adbffe3b6797",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":962,
                  "y":322},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9995d60f73e94f8dba70ebb43ab38ed9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":998,
              "y":322},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5200f37547ca4cd2a26500d0f5f9ca36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":998,
                  "y":322},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78c7426645564bbc84b0d581a78a0c6c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":416},
            "size":{
              "width":392,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66d0c761777e4b0d99191ebd27ce3ce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":416},
                "size":{
                  "width":392,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u56.png"}},
{
          "id":"e42d9ad7dcf34aa39672c8b16b08f423",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1034,
              "y":417},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb65e635a96a41738b706056211460ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1034,
                  "y":417},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u58.png"}},
{
          "id":"b9f492edc1f446599f243fb6086eda4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":516,
              "y":428},
            "size":{
              "width":101,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67b0207edb944ceabf90f43eec404797",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":516,
                  "y":428},
                "size":{
                  "width":101,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b62f5bcc5764faaa310a81aa6e5cded",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1067,
              "y":222},
            "size":{
              "width":94,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce4fee40d1f4d1eb6cbb2c9fd376ae4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1067,
                  "y":222},
                "size":{
                  "width":94,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u13.png"}},
{
          "id":"a1c07c2c6d8e4119802173ce9fbf94cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":1042,
              "y":322},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14faf10adcf84ed6b1496de677659e7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":1042,
                  "y":322},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0a5c0e6406443aca1d62887dcff6194",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":1080,
              "y":322},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e00f327571644934a1973d6b4ad8690d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":1080,
                  "y":322},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"197aadd25d8e4901a549da1d3b9a0eb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":151},
            "size":{
              "width":103,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6881607878d54e3592cb7c08db77d06a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":151},
                "size":{
                  "width":103,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u68.png"}},
{
          "id":"2de324c89af04376a7b405bd897af3e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":842,
              "y":156},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce6f703344df45e9b49f739581a055f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":842,
                  "y":156},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a98c3c799444176b89365bb397534dd",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":883,
              "y":150},
            "size":{
              "width":105,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"d163f0b2474844aab68ff43c6cadb6c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":158},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ba79dcff4cf46a5afdc2c29873da415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":158},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c2685faf6c04776904f5dcada42f4e6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1056,
              "y":150},
            "size":{
              "width":105,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"2abe2fcf966a40f1a4787d5daefb584d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":943,
              "y":222},
            "size":{
              "width":94,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74ac3a0151b946ed871d5a6202dfa0c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":943,
                  "y":222},
                "size":{
                  "width":94,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u13.png"}},
{
          "id":"8c5a27ec474a4b1b9c763294d8a4dec9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":115},
            "size":{
              "width":94,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u18_line.png"}},
{
          "id":"ac171a9e430e48429dc8ded89acea799",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":352,
              "y":92},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eabb8777e2a945c993945f065c126d76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":352,
                  "y":92},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"690c113a2a5943eb86897ef1e4dee48f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF36B3C},
            "location":{
              "x":1190,
              "y":122},
            "size":{
              "width":5,
              "height":665},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"917c2ee1c44f4c55b95695ace42d8eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C},
                "location":{
                  "x":1190,
                  "y":122},
                "size":{
                  "width":5,
                  "height":665},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移动门店/u52.png"}},
{
          "id":"6c0399ff2ee74f3b865b5055311529cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF36B3C},
            "location":{
              "x":1125,
              "y":157},
            "size":{
              "width":100,
              "height":30},
            "rotation":"90",
            "textRotation":"90",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fa01f159fb24ce08b5364137b09fc4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C},
                "location":{
                  "x":1125,
                  "y":157},
                "size":{
                  "width":100,
                  "height":30},
                "rotation":"90",
                "textRotation":"90",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移动门店/u54.png"}},
{
          "id":"d2707f1519e7455faf1967aa07390551",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1169,
              "y":158},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a63c80aaecd54dbea1fb2f85cfac09e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1169,
                  "y":158},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb715244018748f18dfee9937c0e9fea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1195,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1af344f0a4b45fda4d58f536a192585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1195,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u87.png"}},
{
          "id":"f2b8ad2e6913481ab5d00dc013eba685",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-6},
            "size":{
              "width":808,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5e541da5f1b4550ad540b46c997d6d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-6},
                "size":{
                  "width":808,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u104.png"}},
{
          "id":"030967540d9e4ec29a5bf74104b6799f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1044,
              "y":25},
            "size":{
              "width":66,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60089911b9ea4ebb980636ef55e4381f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1044,
                  "y":25},
                "size":{
                  "width":66,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u106.png"}},
{
          "id":"10a9525556e342d4bb8539fdea978db6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3F4A59},
            "location":{
              "x":0,
              "y":79},
            "size":{
              "width":80,
              "height":708},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30d378d94626468cb55cad2dfc5135b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59},
                "location":{
                  "x":0,
                  "y":79},
                "size":{
                  "width":80,
                  "height":708},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u108.png"}},
{
          "id":"3ebd1a6d342b40908e4357d1277b813e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":78},
            "size":{
              "width":80,
              "height":511},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d50b91c5df04b78ad6d849abec29e28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":78},
                "size":{
                  "width":80,
                  "height":511},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u110.png"}},
{
          "id":"99880ce9238a413f92648ec777248c6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":79,
              "y":80},
            "size":{
              "width":140,
              "height":706},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e7216a4480b4e86be953a635c2915eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":79,
                  "y":80},
                "size":{
                  "width":140,
                  "height":706},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u112.png"}},
{
          "id":"45bd1afb98d543239fadf8fd90a6059b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":147},
            "size":{
              "width":14,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e64858c6950416e8390674af578c6ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":147},
                "size":{
                  "width":14,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u114.png"}},
{
          "id":"5c707a5219794aeaa2c2949f10f1f879",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":93,
              "y":100},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff1161d7eca942e3a1de7a39e9064e0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":93,
                  "y":100},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7d18627b95646b6bb3799c058e24824",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2BC589,
              "opacity":1},
            "location":{
              "x":93,
              "y":141},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b136864ec6ce440bbcaaac73ce547ecc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2BC589,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":141},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01b7894b02164151ac3f13ce22653f0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":106},
            "size":{
              "width":13,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75288484652b45e18518bc37705feb8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":106},
                "size":{
                  "width":13,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u120.png"}},
{
          "id":"a2955f130f5549369daa0613f6e841eb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":222,
              "y":117},
            "size":{
              "width":972,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u142_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6a3bfee437d14fc4bd78febb57b2383a":{
      "scriptId":"u0"},
    "1e7ff0c33aae42b5b5ba4681067b3632":{
      "scriptId":"u1"},
    "7a25f7e961e449ddae2e1c6fe49b9a9f":{
      "scriptId":"u2"},
    "5fc02a1a70a8445f9385c1d8caab42db":{
      "scriptId":"u3"},
    "faf721084d3442269c22bfb2c35d3844":{
      "scriptId":"u4"},
    "30ea11d6f8d14dca9b95c62868f0c315":{
      "scriptId":"u5"},
    "2068981d09fe40dbb9c4c2788356c5b1":{
      "scriptId":"u6"},
    "c82ad2f077024e1fafe451ffb5736471":{
      "scriptId":"u7"},
    "43d2bd97519d49d4aedc78ddf5506b3a":{
      "scriptId":"u8"},
    "f57ff646c0bb4fb9ae9a6503a9c025b6":{
      "scriptId":"u9"},
    "d4486d2806d44cebad31a3a991f96d11":{
      "scriptId":"u10"},
    "4516c085d0284107ae1164bff309f672":{
      "scriptId":"u11"},
    "293e2894e08541a892cdf2a22f0fbd69":{
      "scriptId":"u12"},
    "6713e02e5508479bb7da04dd7d6e35c7":{
      "scriptId":"u13"},
    "61c54052fc254729804c836513b154d0":{
      "scriptId":"u14"},
    "65fe94523ad24d478daa8a6bcbb74f70":{
      "scriptId":"u15"},
    "ce6269f859de40bebd26ff9d53be19bf":{
      "scriptId":"u16"},
    "f8a395ddf9ec49d79b4d0bad144e8821":{
      "scriptId":"u17"},
    "f551b3b05c2041c484d73e60e2669774":{
      "scriptId":"u18"},
    "a370609836694d7aabe93edd8b42eafa":{
      "scriptId":"u19"},
    "f9fcc3497002457d93eee37585c79280":{
      "scriptId":"u20"},
    "ce2973bf90664258ba2e6806068410d4":{
      "scriptId":"u21"},
    "d1c34525ec504555b0cf5d3a767396bf":{
      "scriptId":"u22"},
    "c52e6c42b5f7419d9f43cb41f907cfed":{
      "scriptId":"u23"},
    "904edc577cc94e2e8581af9eac6ced8b":{
      "scriptId":"u24"},
    "16afee59488d498382f84ae1526e9b92":{
      "scriptId":"u25"},
    "259be760361b4dc7b1591ad23ca1142f":{
      "scriptId":"u26"},
    "a4c43907e75a4fb9a20e7077643a93ff":{
      "scriptId":"u27"},
    "de2ef647de0043ca8cec26e2e6d125ba":{
      "scriptId":"u28"},
    "457d993e4a814bfc94553797fa6d96b5":{
      "scriptId":"u29"},
    "f547013650e64e8490fe4bc594e93301":{
      "scriptId":"u30"},
    "3fc7efa30c8f4c02b42ed7b1dddce73b":{
      "scriptId":"u31"},
    "a66726e3dbf8405da125e775c76703e7":{
      "scriptId":"u32"},
    "c1ceb2bd8f1e49ebad34ea0bdfeee8b7":{
      "scriptId":"u33"},
    "dee617cf3a5e4791b86421727b1dbe4b":{
      "scriptId":"u34"},
    "623c8a4e687e44a39b7487eb2177ee33":{
      "scriptId":"u35"},
    "981fd68f13d342618b205c3ef0587c8c":{
      "scriptId":"u36"},
    "632567cf01db45da8bc64422d4c147ca":{
      "scriptId":"u37"},
    "9af6ea814dcf4ceb9c2e537e9084362e":{
      "scriptId":"u38"},
    "c794b809dc4347a299e1c653c6b01f01":{
      "scriptId":"u39"},
    "68e3e500f49044ad959d5451106a82b2":{
      "scriptId":"u40"},
    "f0c8ead53c654d65afe833d4731085ce":{
      "scriptId":"u41"},
    "e6ceb39e2f8c419fbb1f808ddb290f1c":{
      "scriptId":"u42"},
    "96d9c8a0520e41f59c26c02c63535746":{
      "scriptId":"u43"},
    "7d561c0aea78442d8289ade57c51d1c8":{
      "scriptId":"u44"},
    "1cd44c6c2443444cad8367207986b354":{
      "scriptId":"u45"},
    "ecf8005529d74d68b97eb282ea82fadc":{
      "scriptId":"u46"},
    "16d6598aaff340059cd387c8e306a405":{
      "scriptId":"u47"},
    "7503a67386e84b849c98c9f991aa434b":{
      "scriptId":"u48"},
    "705112218dd44c469af37f6568b4c026":{
      "scriptId":"u49"},
    "47c00e091ffd429b8fd450ab8df0afc2":{
      "scriptId":"u50"},
    "ede75bbde30042c9863201525449b0e2":{
      "scriptId":"u51"},
    "6756895e75cc46dcad0df2eb3a361494":{
      "scriptId":"u52"},
    "c34a475841984caf9237adbffe3b6797":{
      "scriptId":"u53"},
    "9995d60f73e94f8dba70ebb43ab38ed9":{
      "scriptId":"u54"},
    "5200f37547ca4cd2a26500d0f5f9ca36":{
      "scriptId":"u55"},
    "78c7426645564bbc84b0d581a78a0c6c":{
      "scriptId":"u56"},
    "66d0c761777e4b0d99191ebd27ce3ce3":{
      "scriptId":"u57"},
    "e42d9ad7dcf34aa39672c8b16b08f423":{
      "scriptId":"u58"},
    "cb65e635a96a41738b706056211460ed":{
      "scriptId":"u59"},
    "b9f492edc1f446599f243fb6086eda4b":{
      "scriptId":"u60"},
    "67b0207edb944ceabf90f43eec404797":{
      "scriptId":"u61"},
    "3b62f5bcc5764faaa310a81aa6e5cded":{
      "scriptId":"u62"},
    "6ce4fee40d1f4d1eb6cbb2c9fd376ae4":{
      "scriptId":"u63"},
    "a1c07c2c6d8e4119802173ce9fbf94cc":{
      "scriptId":"u64"},
    "14faf10adcf84ed6b1496de677659e7b":{
      "scriptId":"u65"},
    "a0a5c0e6406443aca1d62887dcff6194":{
      "scriptId":"u66"},
    "e00f327571644934a1973d6b4ad8690d":{
      "scriptId":"u67"},
    "197aadd25d8e4901a549da1d3b9a0eb6":{
      "scriptId":"u68"},
    "6881607878d54e3592cb7c08db77d06a":{
      "scriptId":"u69"},
    "2de324c89af04376a7b405bd897af3e5":{
      "scriptId":"u70"},
    "ce6f703344df45e9b49f739581a055f9":{
      "scriptId":"u71"},
    "6a98c3c799444176b89365bb397534dd":{
      "scriptId":"u72"},
    "d163f0b2474844aab68ff43c6cadb6c8":{
      "scriptId":"u73"},
    "9ba79dcff4cf46a5afdc2c29873da415":{
      "scriptId":"u74"},
    "8c2685faf6c04776904f5dcada42f4e6":{
      "scriptId":"u75"},
    "2abe2fcf966a40f1a4787d5daefb584d":{
      "scriptId":"u76"},
    "74ac3a0151b946ed871d5a6202dfa0c9":{
      "scriptId":"u77"},
    "8c5a27ec474a4b1b9c763294d8a4dec9":{
      "scriptId":"u78"},
    "ac171a9e430e48429dc8ded89acea799":{
      "scriptId":"u79"},
    "eabb8777e2a945c993945f065c126d76":{
      "scriptId":"u80"},
    "690c113a2a5943eb86897ef1e4dee48f":{
      "scriptId":"u81"},
    "917c2ee1c44f4c55b95695ace42d8eff":{
      "scriptId":"u82"},
    "6c0399ff2ee74f3b865b5055311529cc":{
      "scriptId":"u83"},
    "1fa01f159fb24ce08b5364137b09fc4f":{
      "scriptId":"u84"},
    "d2707f1519e7455faf1967aa07390551":{
      "scriptId":"u85"},
    "a63c80aaecd54dbea1fb2f85cfac09e6":{
      "scriptId":"u86"},
    "bb715244018748f18dfee9937c0e9fea":{
      "scriptId":"u87"},
    "b1af344f0a4b45fda4d58f536a192585":{
      "scriptId":"u88"},
    "f2b8ad2e6913481ab5d00dc013eba685":{
      "scriptId":"u89"},
    "d5e541da5f1b4550ad540b46c997d6d3":{
      "scriptId":"u90"},
    "030967540d9e4ec29a5bf74104b6799f":{
      "scriptId":"u91"},
    "60089911b9ea4ebb980636ef55e4381f":{
      "scriptId":"u92"},
    "10a9525556e342d4bb8539fdea978db6":{
      "scriptId":"u93"},
    "30d378d94626468cb55cad2dfc5135b2":{
      "scriptId":"u94"},
    "3ebd1a6d342b40908e4357d1277b813e":{
      "scriptId":"u95"},
    "4d50b91c5df04b78ad6d849abec29e28":{
      "scriptId":"u96"},
    "99880ce9238a413f92648ec777248c6f":{
      "scriptId":"u97"},
    "5e7216a4480b4e86be953a635c2915eb":{
      "scriptId":"u98"},
    "45bd1afb98d543239fadf8fd90a6059b":{
      "scriptId":"u99"},
    "2e64858c6950416e8390674af578c6ec":{
      "scriptId":"u100"},
    "5c707a5219794aeaa2c2949f10f1f879":{
      "scriptId":"u101"},
    "ff1161d7eca942e3a1de7a39e9064e0b":{
      "scriptId":"u102"},
    "c7d18627b95646b6bb3799c058e24824":{
      "scriptId":"u103"},
    "b136864ec6ce440bbcaaac73ce547ecc":{
      "scriptId":"u104"},
    "01b7894b02164151ac3f13ce22653f0e":{
      "scriptId":"u105"},
    "75288484652b45e18518bc37705feb8f":{
      "scriptId":"u106"},
    "a2955f130f5549369daa0613f6e841eb":{
      "scriptId":"u107"}}});