$axure.loadCurrentPage({
  "url":"流程图-微信im流程.html",
  "generationDate":new Date(1451548206413.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f6fb9e2ac977409ba583c04c82bf06d5",
    "type":"Axure:Page",
    "name":"流程图-微信IM流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1767ad2e4064489cb8b567639a5cc5f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "size":{
              "width":1099,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee79d80e0c7f4019b99d29e04aa638aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "size":{
                  "width":1099,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图-微信im流程/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1767ad2e4064489cb8b567639a5cc5f8":{
      "scriptId":"u0"},
    "ee79d80e0c7f4019b99d29e04aa638aa":{
      "scriptId":"u1"}}});