$axure.loadCurrentPage({
  "url":"添加菜单-跳转网页.html",
  "generationDate":new Date(1448119813079.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"78ed6014e0a94b4ba305133c7963853c",
    "type":"Axure:Page",
    "name":"添加菜单-跳转网页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"480fe78af6bb4d7fb34503075ed38aa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Unicode MS Normal', 'Arial Unicode MS'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":18,
              "y":1010},
            "size":{
              "width":102,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"276c0c2898a54687bcd1ad56d54e4025",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Unicode MS Normal', 'Arial Unicode MS'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":1010},
                "size":{
                  "width":102,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c98bf5733ee48078d57b46091bba337",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":163,
              "y":1032},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1b96c2b14aa44bb85ab7b5da2ade8a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":163,
                  "y":1032},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e33148736ba4f788410255fab63991c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1065},
            "size":{
              "width":1190,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商家信息/u28_line.png"}},
{
          "id":"6521dc94279e43188dbaab43ebcedcd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1E2631},
            "location":{
              "x":0,
              "y":1070},
            "size":{
              "width":165,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e080ece3b5bc4e3384f2c702210790c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1E2631},
                "location":{
                  "x":0,
                  "y":1070},
                "size":{
                  "width":165,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u17.png"}},
{
          "id":"ad678bceaed445349c7bf5f7189452dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":125,
              "y":1114},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7800e8ab14f4bc1bb780bed944cfb05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":1114},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"e91b9230af45414190d5b80a40884224",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":125,
              "y":1193},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"775dfc095a4d415fb926c3d03783cfd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":1193},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"22d452c947874585ac0a8ff70a469640",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":1280},
            "size":{
              "width":15,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7e55e77fe2e4874bb1f887b04b61d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":1280},
                "size":{
                  "width":15,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三方接入/u17.png"}},
{
          "id":"cf80bce69c424a718c6759ed39783c93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":1114},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3542b2138a4b4f7a9eab57f980f1b2f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1114},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d47b1a3a0c5a4fd38c5e3555f868b183",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":1192},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd5e1f83fa2840bc98b2f7500d9d59eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1192},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a056b8cdb7a45958ea3f615f7bf6b21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":1275},
            "size":{
              "width":113,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"929d71cf00fa4533bdc9ab6d4a17cd14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1275},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c21b1d2d3b543db9d3011818f0133d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":1347},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f52f1aca94604470848de3a80a2a3b5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1347},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aec9c26a67614108acc04959d3dbe489",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":1375},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"760c4fdda286412cab3b549900e3cc5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1375},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03a1a12df6e7444f9efbdda573c838e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":1403},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1082e13c8ded456e846dafa61c9b78df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1403},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa6bd4a7cbaa4fd195ff912211208a57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":990},
            "size":{
              "width":1190,
              "height":920},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff16e3c4e7494440a928120b8a8bb796",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":990},
                "size":{
                  "width":1190,
                  "height":920},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u37.png"}},
{
          "id":"81b2eacc1f194eb1ab0904d3ce914678",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Unicode MS Normal', 'Arial Unicode MS'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":18,
              "y":20},
            "size":{
              "width":102,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9880e19aad9b4b90970d00307910213e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Unicode MS Normal', 'Arial Unicode MS'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":20},
                "size":{
                  "width":102,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"642f886357024398a7c265afbec806a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":163,
              "y":42},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00f003d898324530a2e78ef0e5db38a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":163,
                  "y":42},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31a750d51ccf45c29554695bd6b00c41",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":75},
            "size":{
              "width":1190,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商家信息/u28_line.png"}},
{
          "id":"93f833178bf34cf0a6156b9dffa0d119",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1121,
              "y":42},
            "size":{
              "width":40,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2b3705e2db74484a2aa88d3d08b28fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1121,
                  "y":42},
                "size":{
                  "width":40,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0836245904f140f0b642567fdde49092",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1083,
              "y":34},
            "size":{
              "width":34,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6452538c57b445c089b0622b897065be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1083,
                  "y":34},
                "size":{
                  "width":34,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u68.png"}},
{
          "id":"0e0743f68d89429d8598d188dd6083cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1E2631},
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":165,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac69dc06039c4119bbe7892636ad914e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1E2631},
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":165,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u17.png"}},
{
          "id":"91c827696fa1459b88fe0572974315d3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":125,
              "y":124},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0e715b991ad44f39e5e01abb6b55324",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":124},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"f58acc9745574110945b23165502bcdb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":125,
              "y":203},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc0db0fa48064ab7afbaec8b3451caad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":203},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"00f845c1467b4405b0ee86818897d48c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":290},
            "size":{
              "width":15,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e88b9f686074f2290e540de882b540e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":290},
                "size":{
                  "width":15,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三方接入/u17.png"}},
{
          "id":"3f599b2a8d87430f8ff8f0bc40bcb28d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":124},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fd29f394af247d19a5ca02cffb6a00c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":124},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0d4e998629f45c88a2b882ff2810c5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":202},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9861a4a712b74493b0abe666af3b6e92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":202},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d44b24b06324250ab245aa6a483c05b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":285},
            "size":{
              "width":113,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16b48c5c20cd40d99dc806475ce7fea0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":285},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08690fb0d67741088b75c325009017dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":357},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad1b4d8f8a7748bd8baee4a70b442f6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":357},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a345ef26de0469c95544300eb2fe3e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":385},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e92cee0de31147539b8d0da29a27a63b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":385},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23b11d03826a459882c66f03b9525b5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":413},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e326a95e8dcd4fe0a1e01a4683e1a452",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":413},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd31e858ee774e89960e394217b787d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":1190,
              "height":920},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33273913a161413a92f3230a0138f1c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":1190,
                  "height":920},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u37.png"}},
{
          "id":"e832bfe2b0a2459e819b3fa5d402d8a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":202},
            "size":{
              "width":370,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa25c7fdf6de4dca8ccc73d2bbd55220",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":202},
                "size":{
                  "width":370,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"716b321fae964f83bc85c871865f6e3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE0EAF6},
            "location":{
              "x":204,
              "y":111},
            "size":{
              "width":941,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0EAF6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0462b74a81e04fe29d0d5cfc355a52f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6},
                "location":{
                  "x":204,
                  "y":111},
                "size":{
                  "width":941,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u33.png"}},
{
          "id":"d3c36c1582404fd78832b59ff7f0d4ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":115},
            "size":{
              "width":330,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abc94bf1c6f1476e82a28e506955e490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":224,
                  "y":115},
                "size":{
                  "width":330,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u6.png"}},
{
          "id":"c6046c8fcf9b4e59ba706d0254e39dfd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":228},
            "size":{
              "width":941,
              "height":674}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddeed98792fa44829e123cb812ba21c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":228},
                "size":{
                  "width":941,
                  "height":674}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u37.png"}},
{
          "id":"5045006c4f944951a85c72c2147302e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":844,
              "y":501},
            "size":{
              "width":250,
              "height":170},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39ee1681003d407ebaf49bcd09a679d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":844,
                  "y":501},
                "size":{
                  "width":250,
                  "height":170},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u41.png"}},
{
          "id":"34a138d8f54049a18a3fdd87e8ec266d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":591},
            "size":{
              "width":150,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"820e9b62b7ef46aea094b830620f25c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647,
                  "y":591},
                "size":{
                  "width":150,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u43.png"}},
{
          "id":"11226850bb8e40b9befe994e660ba4ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":571,
              "y":433},
            "size":{
              "width":552,
              "height":268}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bebfdbc10e04b0f95dff8946a6b9db4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":571,
                  "y":433},
                "size":{
                  "width":552,
                  "height":268}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_文字信息/u12.png"}},
{
          "id":"4e7763963839473ba15243e61942b9e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":811,
              "y":443},
            "size":{
              "width":300,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ef75aa3e6b146c6b47136314909f6c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":811,
                  "y":443},
                "size":{
                  "width":300,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u39.png"}},
{
          "id":"be7c137477ea433bbd37ab0d8af42ad8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":547,
              "y":234},
            "size":{
              "width":598,
              "height":593}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec1532a1269f4a799697bf7a2babe923",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":547,
                  "y":234},
                "size":{
                  "width":598,
                  "height":593}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u74.png"}},
{
          "id":"179dade2cc8e4b8eb2c52ac63cf08c33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":1190},
            "size":{
              "width":367,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09c5c0e9f3704e19af8485e39bfda096",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":1190},
                "size":{
                  "width":367,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea5686573d664fdf83e138ed545fc558",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE0EAF6},
            "location":{
              "x":237,
              "y":1100},
            "size":{
              "width":933,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0EAF6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a48ee3b47e9b42d6ac6e5b6a9f9c7ac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6},
                "location":{
                  "x":237,
                  "y":1100},
                "size":{
                  "width":933,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u78.png"}},
{
          "id":"f6fa782d5eb245dfabd383667846cb96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":257,
              "y":1104},
            "size":{
              "width":327,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3fd2a5439e7436b8034a91ec3c1df8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":257,
                  "y":1104},
                "size":{
                  "width":327,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信菜单/u6.png"}},
{
          "id":"82470baa988441c3b6c84f4d9876366b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":1216},
            "size":{
              "width":933,
              "height":668}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94ab43c7cc674735ab05d1ec54bce9ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":1216},
                "size":{
                  "width":933,
                  "height":668}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u37.png"}},
{
          "id":"8dd5c4a5979a4bceb879034c66726e94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":872,
              "y":1487},
            "size":{
              "width":248,
              "height":169},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f517e8ae4514e08b8014828e906d4b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":872,
                  "y":1487},
                "size":{
                  "width":248,
                  "height":169},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u84.png"}},
{
          "id":"1bf31920c41f41a981ba49da699cf367",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":677,
              "y":1576},
            "size":{
              "width":149,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b77955c420542bab903d467a277062b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":677,
                  "y":1576},
                "size":{
                  "width":149,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u86.png"}},
{
          "id":"8359e6cfcaa94927892897b48357c109",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":601,
              "y":1419},
            "size":{
              "width":547,
              "height":266}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28f5069d1f1c4e74a50c81e778db2911",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":601,
                  "y":1419},
                "size":{
                  "width":547,
                  "height":266}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_文字信息/u12.png"}},
{
          "id":"807ca632f4a74158933b44603ba2ff73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":839,
              "y":1429},
            "size":{
              "width":297,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0da41f6cc4be4af0b1aea79248173462",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":839,
                  "y":1429},
                "size":{
                  "width":297,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u90.png"}},
{
          "id":"ffaed416f42341b7b1255e1e93cd0530",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":577,
              "y":1222},
            "size":{
              "width":593,
              "height":588}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8afa692af4ef46c196957fcc6ac08215",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":577,
                  "y":1222},
                "size":{
                  "width":593,
                  "height":588}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u74.png"}},
{
          "id":"7ea709ec6d864175805eb2e7227ad885",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":0,
              "y":990},
            "size":{
              "width":1190,
              "height":920}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ca7a066923546bd82331198de817dc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":0,
                  "y":990},
                "size":{
                  "width":1190,
                  "height":920}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u94.png"}},
{
          "id":"26706db43f334d7bb54c8d2fce092999",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":838,
              "y":1668},
            "size":{
              "width":226,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a428c0c6008b4002a7ea42b05a5e92f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":838,
                  "y":1668},
                "size":{
                  "width":226,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u96.png"}},
{
          "id":"c0b31571aa5b482aa2ca8d1dcd797cf5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":990},
            "size":{
              "width":1027,
              "height":920},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc5a7762552f4269bbd45c0a11dd71b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":164,
                  "y":990},
                "size":{
                  "width":1027,
                  "height":920},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u96.png"}},
{
          "id":"cb25e2d182824ae89b22c6a58e305d47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":217,
              "y":1108},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c4eedf1e4c54b6482ab31a6cf1e63e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":1108},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"289f9ca7ec7a445b93d7a89768402618",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":189,
              "y":1157},
            "size":{
              "width":264,
              "height":603},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c702a2a369a4404d95ce3d0588bd91a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":189,
                  "y":1157},
                "size":{
                  "width":264,
                  "height":603},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u102.png"}},
{
          "id":"9e6b046e5a5545cc8f3b68bc9ed8d360",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":189,
              "y":1157},
            "size":{
              "width":264,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04b4b3fd34f34c4b973f4075c5946ee1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":189,
                  "y":1157},
                "size":{
                  "width":264,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u104.png"}},
{
          "id":"92cc43077b324afa94f1b51e16bf4de4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":451,
              "y":1157},
            "size":{
              "width":721,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5384088e9b44486ea6b7a4981907e9d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":451,
                  "y":1157},
                "size":{
                  "width":721,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u106.png"}},
{
          "id":"9d7489095ae2436b8564e0f507f4d1f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":452,
              "y":1208},
            "size":{
              "width":718,
              "height":551},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ebd4044567b47be9b075c945e00d232",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":452,
                  "y":1208},
                "size":{
                  "width":718,
                  "height":551},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u108.png"}},
{
          "id":"fe77524e7a454e0080ffa878c7e67c4f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1131,
              "y":1008},
            "size":{
              "width":10,
              "height":44},
            "rotation":"40",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单-跳转网页/u110_line.png"}},
{
          "id":"915a07d6ce4945d79bbad39e3672feec",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1131,
              "y":1008},
            "size":{
              "width":10,
              "height":44},
            "rotation":"320",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单-跳转网页/u110_line.png"}},
{
          "id":"d911ccd1624c4d0c8e047346ddd55010",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":1082},
            "size":{
              "width":1011,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单_图文信息/u114_line.png"}},
{
          "id":"089941a47b374b3c8e936d086fc2438f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":602,
              "y":1025},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"475a1398a06d41c583b0a6760602da0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":602,
                  "y":1025},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90189fa491a141ad8f8d30bf746355af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":1222},
            "size":{
              "width":76,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26dfc0d129bd44349138eb1c4936cf98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":1222},
                "size":{
                  "width":76,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u115.png"}},
{
          "id":"67ed6b349cef4e41bf8d3936e697790d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":1246},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db5caf10406742c58101759455a80423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":1246},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f9a549c72874671aece5ebcd8bf8557",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":1226},
            "size":{
              "width":76,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c76dace68d454fd8844f3199dce5e121",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":1226},
                "size":{
                  "width":76,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u115.png"}},
{
          "id":"6d9cc0f511664c0c829d8894e5ea0f65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":685,
              "y":1250},
            "size":{
              "width":79,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0e9b000b5ad4de6a6172f3bbb61f453",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":685,
                  "y":1250},
                "size":{
                  "width":79,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b3af8e38ba24384b5bd54f16a38ca19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":432,
              "y":1804},
            "size":{
              "width":187,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20819b5b7bfa4954bb762ea81a150982",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":432,
                  "y":1804},
                "size":{
                  "width":187,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u123.png"}},
{
          "id":"36bc529e759a47b8b82ab8785dc9b6d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":1243},
            "size":{
              "width":33,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d7932e5a6914cabbf879376c5ad49af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":1243},
                "size":{
                  "width":33,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u133.png"}},
{
          "id":"5769c2966a3f4481a5d842914ed54a93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":419,
              "y":1246},
            "size":{
              "width":9,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46653e3d49f144b4a5be88aa73f12668",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":419,
                  "y":1246},
                "size":{
                  "width":9,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"185e8f9cedb643b6961708565c74969b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":1300},
            "size":{
              "width":248,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单-跳转网页/u129_line.png"}},
{
          "id":"2ed16cf05e89426ea391fbbfe313fbbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":1311},
            "size":{
              "width":76,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd135044e96749928df528a2614d9ab6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":1311},
                "size":{
                  "width":76,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u115.png"}},
{
          "id":"c57710ff39674c8e848a29202b6e0d29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":687,
              "y":1333},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2994c239051e4c7298cf2603b99e3a16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":687,
                  "y":1333},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d91f012edc0411598a006dc982e9a66",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":1328},
            "size":{
              "width":33,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"236f99c8d92c4ee192c9f27d547dddda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":1328},
                "size":{
                  "width":33,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u133.png"}},
{
          "id":"6f70aca118704f958d9657dac7f353d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":1394},
            "size":{
              "width":76,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5203d83327844da8ac14da676878e0c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":1394},
                "size":{
                  "width":76,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u115.png"}},
{
          "id":"82f3a50262cb48aabb00f8eaea866121",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":685,
              "y":1418},
            "size":{
              "width":70,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6ec7dd2863641e1ab410c8db4f63d48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":685,
                  "y":1418},
                "size":{
                  "width":70,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8acece7bf4924b3ba1c72e5f3493153d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":1411},
            "size":{
              "width":33,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d2b1bb3fd914dd2b26087be0f7129ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":1411},
                "size":{
                  "width":33,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u133.png"}},
{
          "id":"96200215ac474f8fae6d34e5b23d6f35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":215,
              "y":1139},
            "size":{
              "width":31,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae4afbd64b7b4e348304bdc30a75f5bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":215,
                  "y":1139},
                "size":{
                  "width":31,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u150.png"}},
{
          "id":"6b3e464836c84d35adc613ea2a452af4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF44B549},
            "location":{
              "x":666,
              "y":1804},
            "size":{
              "width":187,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf53361624d2446bb24067e2c58262b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF44B549},
                "location":{
                  "x":666,
                  "y":1804},
                "size":{
                  "width":187,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u117.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "480fe78af6bb4d7fb34503075ed38aa1":{
      "scriptId":"u0"},
    "276c0c2898a54687bcd1ad56d54e4025":{
      "scriptId":"u1"},
    "8c98bf5733ee48078d57b46091bba337":{
      "scriptId":"u2"},
    "a1b96c2b14aa44bb85ab7b5da2ade8a2":{
      "scriptId":"u3"},
    "7e33148736ba4f788410255fab63991c":{
      "scriptId":"u4"},
    "6521dc94279e43188dbaab43ebcedcd7":{
      "scriptId":"u5"},
    "e080ece3b5bc4e3384f2c702210790c3":{
      "scriptId":"u6"},
    "ad678bceaed445349c7bf5f7189452dc":{
      "scriptId":"u7"},
    "e7800e8ab14f4bc1bb780bed944cfb05":{
      "scriptId":"u8"},
    "e91b9230af45414190d5b80a40884224":{
      "scriptId":"u9"},
    "775dfc095a4d415fb926c3d03783cfd0":{
      "scriptId":"u10"},
    "22d452c947874585ac0a8ff70a469640":{
      "scriptId":"u11"},
    "f7e55e77fe2e4874bb1f887b04b61d35":{
      "scriptId":"u12"},
    "cf80bce69c424a718c6759ed39783c93":{
      "scriptId":"u13"},
    "3542b2138a4b4f7a9eab57f980f1b2f6":{
      "scriptId":"u14"},
    "d47b1a3a0c5a4fd38c5e3555f868b183":{
      "scriptId":"u15"},
    "bd5e1f83fa2840bc98b2f7500d9d59eb":{
      "scriptId":"u16"},
    "5a056b8cdb7a45958ea3f615f7bf6b21":{
      "scriptId":"u17"},
    "929d71cf00fa4533bdc9ab6d4a17cd14":{
      "scriptId":"u18"},
    "1c21b1d2d3b543db9d3011818f0133d6":{
      "scriptId":"u19"},
    "f52f1aca94604470848de3a80a2a3b5e":{
      "scriptId":"u20"},
    "aec9c26a67614108acc04959d3dbe489":{
      "scriptId":"u21"},
    "760c4fdda286412cab3b549900e3cc5d":{
      "scriptId":"u22"},
    "03a1a12df6e7444f9efbdda573c838e7":{
      "scriptId":"u23"},
    "1082e13c8ded456e846dafa61c9b78df":{
      "scriptId":"u24"},
    "aa6bd4a7cbaa4fd195ff912211208a57":{
      "scriptId":"u25"},
    "ff16e3c4e7494440a928120b8a8bb796":{
      "scriptId":"u26"},
    "81b2eacc1f194eb1ab0904d3ce914678":{
      "scriptId":"u27"},
    "9880e19aad9b4b90970d00307910213e":{
      "scriptId":"u28"},
    "642f886357024398a7c265afbec806a8":{
      "scriptId":"u29"},
    "00f003d898324530a2e78ef0e5db38a1":{
      "scriptId":"u30"},
    "31a750d51ccf45c29554695bd6b00c41":{
      "scriptId":"u31"},
    "93f833178bf34cf0a6156b9dffa0d119":{
      "scriptId":"u32"},
    "f2b3705e2db74484a2aa88d3d08b28fe":{
      "scriptId":"u33"},
    "0836245904f140f0b642567fdde49092":{
      "scriptId":"u34"},
    "6452538c57b445c089b0622b897065be":{
      "scriptId":"u35"},
    "0e0743f68d89429d8598d188dd6083cb":{
      "scriptId":"u36"},
    "ac69dc06039c4119bbe7892636ad914e":{
      "scriptId":"u37"},
    "91c827696fa1459b88fe0572974315d3":{
      "scriptId":"u38"},
    "c0e715b991ad44f39e5e01abb6b55324":{
      "scriptId":"u39"},
    "f58acc9745574110945b23165502bcdb":{
      "scriptId":"u40"},
    "cc0db0fa48064ab7afbaec8b3451caad":{
      "scriptId":"u41"},
    "00f845c1467b4405b0ee86818897d48c":{
      "scriptId":"u42"},
    "2e88b9f686074f2290e540de882b540e":{
      "scriptId":"u43"},
    "3f599b2a8d87430f8ff8f0bc40bcb28d":{
      "scriptId":"u44"},
    "0fd29f394af247d19a5ca02cffb6a00c":{
      "scriptId":"u45"},
    "c0d4e998629f45c88a2b882ff2810c5b":{
      "scriptId":"u46"},
    "9861a4a712b74493b0abe666af3b6e92":{
      "scriptId":"u47"},
    "2d44b24b06324250ab245aa6a483c05b":{
      "scriptId":"u48"},
    "16b48c5c20cd40d99dc806475ce7fea0":{
      "scriptId":"u49"},
    "08690fb0d67741088b75c325009017dd":{
      "scriptId":"u50"},
    "ad1b4d8f8a7748bd8baee4a70b442f6f":{
      "scriptId":"u51"},
    "7a345ef26de0469c95544300eb2fe3e8":{
      "scriptId":"u52"},
    "e92cee0de31147539b8d0da29a27a63b":{
      "scriptId":"u53"},
    "23b11d03826a459882c66f03b9525b5a":{
      "scriptId":"u54"},
    "e326a95e8dcd4fe0a1e01a4683e1a452":{
      "scriptId":"u55"},
    "bd31e858ee774e89960e394217b787d7":{
      "scriptId":"u56"},
    "33273913a161413a92f3230a0138f1c0":{
      "scriptId":"u57"},
    "e832bfe2b0a2459e819b3fa5d402d8a6":{
      "scriptId":"u58"},
    "fa25c7fdf6de4dca8ccc73d2bbd55220":{
      "scriptId":"u59"},
    "716b321fae964f83bc85c871865f6e3f":{
      "scriptId":"u60"},
    "0462b74a81e04fe29d0d5cfc355a52f2":{
      "scriptId":"u61"},
    "d3c36c1582404fd78832b59ff7f0d4ec":{
      "scriptId":"u62"},
    "abc94bf1c6f1476e82a28e506955e490":{
      "scriptId":"u63"},
    "c6046c8fcf9b4e59ba706d0254e39dfd":{
      "scriptId":"u64"},
    "ddeed98792fa44829e123cb812ba21c2":{
      "scriptId":"u65"},
    "5045006c4f944951a85c72c2147302e2":{
      "scriptId":"u66"},
    "39ee1681003d407ebaf49bcd09a679d1":{
      "scriptId":"u67"},
    "34a138d8f54049a18a3fdd87e8ec266d":{
      "scriptId":"u68"},
    "820e9b62b7ef46aea094b830620f25c0":{
      "scriptId":"u69"},
    "11226850bb8e40b9befe994e660ba4ad":{
      "scriptId":"u70"},
    "2bebfdbc10e04b0f95dff8946a6b9db4":{
      "scriptId":"u71"},
    "4e7763963839473ba15243e61942b9e7":{
      "scriptId":"u72"},
    "4ef75aa3e6b146c6b47136314909f6c4":{
      "scriptId":"u73"},
    "be7c137477ea433bbd37ab0d8af42ad8":{
      "scriptId":"u74"},
    "ec1532a1269f4a799697bf7a2babe923":{
      "scriptId":"u75"},
    "179dade2cc8e4b8eb2c52ac63cf08c33":{
      "scriptId":"u76"},
    "09c5c0e9f3704e19af8485e39bfda096":{
      "scriptId":"u77"},
    "ea5686573d664fdf83e138ed545fc558":{
      "scriptId":"u78"},
    "a48ee3b47e9b42d6ac6e5b6a9f9c7ac3":{
      "scriptId":"u79"},
    "f6fa782d5eb245dfabd383667846cb96":{
      "scriptId":"u80"},
    "b3fd2a5439e7436b8034a91ec3c1df8b":{
      "scriptId":"u81"},
    "82470baa988441c3b6c84f4d9876366b":{
      "scriptId":"u82"},
    "94ab43c7cc674735ab05d1ec54bce9ec":{
      "scriptId":"u83"},
    "8dd5c4a5979a4bceb879034c66726e94":{
      "scriptId":"u84"},
    "5f517e8ae4514e08b8014828e906d4b1":{
      "scriptId":"u85"},
    "1bf31920c41f41a981ba49da699cf367":{
      "scriptId":"u86"},
    "3b77955c420542bab903d467a277062b":{
      "scriptId":"u87"},
    "8359e6cfcaa94927892897b48357c109":{
      "scriptId":"u88"},
    "28f5069d1f1c4e74a50c81e778db2911":{
      "scriptId":"u89"},
    "807ca632f4a74158933b44603ba2ff73":{
      "scriptId":"u90"},
    "0da41f6cc4be4af0b1aea79248173462":{
      "scriptId":"u91"},
    "ffaed416f42341b7b1255e1e93cd0530":{
      "scriptId":"u92"},
    "8afa692af4ef46c196957fcc6ac08215":{
      "scriptId":"u93"},
    "7ea709ec6d864175805eb2e7227ad885":{
      "scriptId":"u94"},
    "3ca7a066923546bd82331198de817dc8":{
      "scriptId":"u95"},
    "26706db43f334d7bb54c8d2fce092999":{
      "scriptId":"u96"},
    "a428c0c6008b4002a7ea42b05a5e92f4":{
      "scriptId":"u97"},
    "c0b31571aa5b482aa2ca8d1dcd797cf5":{
      "scriptId":"u98"},
    "dc5a7762552f4269bbd45c0a11dd71b2":{
      "scriptId":"u99"},
    "cb25e2d182824ae89b22c6a58e305d47":{
      "scriptId":"u100"},
    "9c4eedf1e4c54b6482ab31a6cf1e63e9":{
      "scriptId":"u101"},
    "289f9ca7ec7a445b93d7a89768402618":{
      "scriptId":"u102"},
    "c702a2a369a4404d95ce3d0588bd91a8":{
      "scriptId":"u103"},
    "9e6b046e5a5545cc8f3b68bc9ed8d360":{
      "scriptId":"u104"},
    "04b4b3fd34f34c4b973f4075c5946ee1":{
      "scriptId":"u105"},
    "92cc43077b324afa94f1b51e16bf4de4":{
      "scriptId":"u106"},
    "5384088e9b44486ea6b7a4981907e9d9":{
      "scriptId":"u107"},
    "9d7489095ae2436b8564e0f507f4d1f7":{
      "scriptId":"u108"},
    "0ebd4044567b47be9b075c945e00d232":{
      "scriptId":"u109"},
    "fe77524e7a454e0080ffa878c7e67c4f":{
      "scriptId":"u110"},
    "915a07d6ce4945d79bbad39e3672feec":{
      "scriptId":"u111"},
    "d911ccd1624c4d0c8e047346ddd55010":{
      "scriptId":"u112"},
    "089941a47b374b3c8e936d086fc2438f":{
      "scriptId":"u113"},
    "475a1398a06d41c583b0a6760602da0f":{
      "scriptId":"u114"},
    "90189fa491a141ad8f8d30bf746355af":{
      "scriptId":"u115"},
    "26dfc0d129bd44349138eb1c4936cf98":{
      "scriptId":"u116"},
    "67ed6b349cef4e41bf8d3936e697790d":{
      "scriptId":"u117"},
    "db5caf10406742c58101759455a80423":{
      "scriptId":"u118"},
    "1f9a549c72874671aece5ebcd8bf8557":{
      "scriptId":"u119"},
    "c76dace68d454fd8844f3199dce5e121":{
      "scriptId":"u120"},
    "6d9cc0f511664c0c829d8894e5ea0f65":{
      "scriptId":"u121"},
    "c0e9b000b5ad4de6a6172f3bbb61f453":{
      "scriptId":"u122"},
    "5b3af8e38ba24384b5bd54f16a38ca19":{
      "scriptId":"u123"},
    "20819b5b7bfa4954bb762ea81a150982":{
      "scriptId":"u124"},
    "36bc529e759a47b8b82ab8785dc9b6d4":{
      "scriptId":"u125"},
    "6d7932e5a6914cabbf879376c5ad49af":{
      "scriptId":"u126"},
    "5769c2966a3f4481a5d842914ed54a93":{
      "scriptId":"u127"},
    "46653e3d49f144b4a5be88aa73f12668":{
      "scriptId":"u128"},
    "185e8f9cedb643b6961708565c74969b":{
      "scriptId":"u129"},
    "2ed16cf05e89426ea391fbbfe313fbbc":{
      "scriptId":"u130"},
    "fd135044e96749928df528a2614d9ab6":{
      "scriptId":"u131"},
    "c57710ff39674c8e848a29202b6e0d29":{
      "scriptId":"u132"},
    "2994c239051e4c7298cf2603b99e3a16":{
      "scriptId":"u133"},
    "9d91f012edc0411598a006dc982e9a66":{
      "scriptId":"u134"},
    "236f99c8d92c4ee192c9f27d547dddda":{
      "scriptId":"u135"},
    "6f70aca118704f958d9657dac7f353d8":{
      "scriptId":"u136"},
    "5203d83327844da8ac14da676878e0c5":{
      "scriptId":"u137"},
    "82f3a50262cb48aabb00f8eaea866121":{
      "scriptId":"u138"},
    "d6ec7dd2863641e1ab410c8db4f63d48":{
      "scriptId":"u139"},
    "8acece7bf4924b3ba1c72e5f3493153d":{
      "scriptId":"u140"},
    "8d2b1bb3fd914dd2b26087be0f7129ed":{
      "scriptId":"u141"},
    "96200215ac474f8fae6d34e5b23d6f35":{
      "scriptId":"u142"},
    "ae4afbd64b7b4e348304bdc30a75f5bf":{
      "scriptId":"u143"},
    "6b3e464836c84d35adc613ea2a452af4":{
      "scriptId":"u144"},
    "bf53361624d2446bb24067e2c58262b7":{
      "scriptId":"u145"}}});