$axure.loadCurrentPage({
  "url":"停用店员账号.html",
  "generationDate":new Date(1448247503221.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a80f22c9c1dc4f13aa6979d56b3a31a6",
    "type":"Axure:Page",
    "name":"停用店员账号",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a279a7fea9dd4d1a824fd04b29958fcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":122},
            "size":{
              "width":1195,
              "height":665},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34241783621c427e9f202edbeda90f44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":122},
                "size":{
                  "width":1195,
                  "height":665},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/批量新增店员/u0.png"}},
{
          "id":"ec017fe2cf1f40f4bd3271c48743186d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF36B3C,
              "opacity":1},
            "location":{
              "x":235,
              "y":91},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4eea724a4c44d8e8d6adf6d50a21fb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C,
                  "opacity":1},
                "location":{
                  "x":235,
                  "y":91},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"826ccc788e2b4d6e90c10afcbd4ef71e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":150},
            "size":{
              "width":107,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b57ce561bb79434ea2735c54d1ba1abe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":150},
                "size":{
                  "width":107,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u4.png"}},
{
          "id":"8fb5c869eac044c1b28fcfe0336efac3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":244,
              "y":155},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47235f871c4d431e8e00024780687869",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":244,
                  "y":155},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f88b71e8581469381c80e712b9aa0e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":156},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a201f02561e4437da95c52b300413f0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":156},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0bd8b2539274ff29a009a42488cd887",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":616,
              "y":157},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e95f1a0cbaf4f75afc26a84d8eed304",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":616,
                  "y":157},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df6df5ae091c460792cfeb4a27247c73",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":150},
            "size":{
              "width":138,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"8bbb3b41ff7141b2b918aa05830fafe3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":815,
              "y":222},
            "size":{
              "width":94,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd6968250d745539c8629448c5c22bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":815,
                  "y":222},
                "size":{
                  "width":94,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u13.png"}},
{
          "id":"86978339a9d049e0827a1681580cc6db",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":241,
              "y":279},
            "size":{
              "width":938,
              "height":104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"351ebe2126524b43939d35c59140645e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":105,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"28d7a3afe9964ff194eb0544bc415e4c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "size":{
                      "width":105,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u16.png"}},
{
              "id":"0a65f8bb0297465dbcb458244ae5a973",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":105,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6ee1b47c359d4afb84127498f6dfd368",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":105,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u28.png"}},
{
              "id":"2ab0f756526448359428e24b01474da5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":105,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"42f95bc5f3cb42ccb90b3ff9c0c22dcd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":105,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u40.png"}},
{
              "id":"75687de5f29f46ccb216399630647a76",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":540,
                  "y":0},
                "size":{
                  "width":104,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6917fdf8050433eaba0e2dd6faf7729",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":540,
                      "y":0},
                    "size":{
                      "width":104,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u24.png"}},
{
              "id":"cab501d475c247209948e2f2a8691222",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":540,
                  "y":30},
                "size":{
                  "width":104,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"80225f608cf142caa47b88271294fd92",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":540,
                      "y":30},
                    "size":{
                      "width":104,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u36.png"}},
{
              "id":"00976ebf69bb480ebdb9757deb91b3bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":540,
                  "y":66},
                "size":{
                  "width":104,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"89c1019201a5446783b849b713d98d64",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":540,
                      "y":66},
                    "size":{
                      "width":104,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u48.png"}},
{
              "id":"95d0ae32824244039407d47fe7a54344",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":644,
                  "y":0},
                "size":{
                  "width":294,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e8156543dd8e4fe99a67b8219671babf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":644,
                      "y":0},
                    "size":{
                      "width":294,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u26.png"}},
{
              "id":"608bd63ac94f490191ed4ae6df1e380b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":644,
                  "y":30},
                "size":{
                  "width":294,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6980c4bb64f40779a27a0bc916d88e1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":644,
                      "y":30},
                    "size":{
                      "width":294,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u38.png"}},
{
              "id":"73c6ef4e9c0b4691964cb81961e5c616",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":644,
                  "y":66},
                "size":{
                  "width":294,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9570996e9c394fc3b8a8d7b78eab824a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":644,
                      "y":66},
                    "size":{
                      "width":294,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u50.png"}},
{
              "id":"de64046bfce64de89d78ec40e1609851",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":105,
                  "y":0},
                "size":{
                  "width":123,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1b31b428b0074ee8803dda6933d6fc40",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":105,
                      "y":0},
                    "size":{
                      "width":123,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u18.png"}},
{
              "id":"d8728517914f421cad819aedf10d6151",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":105,
                  "y":30},
                "size":{
                  "width":123,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2901c21cfec4d1bb97c283bef43f18e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":105,
                      "y":30},
                    "size":{
                      "width":123,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u30.png"}},
{
              "id":"e965c2eaedb2457f84b806ca783d65f3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":105,
                  "y":66},
                "size":{
                  "width":123,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a44d5d6458ac43bf867c85d0ecc143b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":105,
                      "y":66},
                    "size":{
                      "width":123,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u42.png"}},
{
              "id":"56490a1dc59a44a5817d6718dda0cd7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":228,
                  "y":0},
                "size":{
                  "width":213,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29f86156782745d480c36a1be631108a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":228,
                      "y":0},
                    "size":{
                      "width":213,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u20.png"}},
{
              "id":"6f8145e5975b4ed888c67143d74f45fa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":228,
                  "y":30},
                "size":{
                  "width":213,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c78f5c51b264e13b2e2403c014e9404",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":228,
                      "y":30},
                    "size":{
                      "width":213,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u32.png"}},
{
              "id":"b7a1d7cc9a1a4b769e56d0e365efe2fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":228,
                  "y":66},
                "size":{
                  "width":213,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9c7b993a14e84fe390c08390f49e9ab0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":228,
                      "y":66},
                    "size":{
                      "width":213,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u44.png"}},
{
              "id":"622f1887dbf7491c98a3400d80826c81",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":441,
                  "y":0},
                "size":{
                  "width":99,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"57eb82ce875f4485b3e857b6a4ef4daa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":441,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u22.png"}},
{
              "id":"b50b2a77634a400991f213243abe3b0b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":441,
                  "y":30},
                "size":{
                  "width":99,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e759c9583b204900b19c0387a2cd2ca6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":441,
                      "y":30},
                    "size":{
                      "width":99,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u34.png"}},
{
              "id":"b415f46bdb3a4dc2aaaf33c6fcd7724d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":441,
                  "y":66},
                "size":{
                  "width":99,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"59338839b57441309202eec28ab83867",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":441,
                      "y":66},
                    "size":{
                      "width":99,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u46.png"}}]},
{
          "id":"8ceef352f80142d5a5e6a7464b92a9fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":962,
              "y":322},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a568ec9e55d4684a0d30bddada1e59b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":962,
                  "y":322},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbb4e24fb8e54323991d77e0cb0dafad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":998,
              "y":322},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a363f4a1123a4d4d8e9caebccb5fa8da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":998,
                  "y":322},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c40d227ab2c44078bba6dc5312d5f95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":416},
            "size":{
              "width":392,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"474797279a3c4c42aff86f1e12eb0368",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":416},
                "size":{
                  "width":392,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u56.png"}},
{
          "id":"66f95f8babe24b6ea3a7b53931e36d8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1034,
              "y":417},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dfccd5009064784bbbf6d866845ff10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1034,
                  "y":417},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u58.png"}},
{
          "id":"66e6838dd4584de8a20a835242910b40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":516,
              "y":428},
            "size":{
              "width":101,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26f45e8ee0a44507b3a05b0cfbdd66d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":516,
                  "y":428},
                "size":{
                  "width":101,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"caab7cd439954a6fa055a1c8646b9eac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1067,
              "y":222},
            "size":{
              "width":94,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0ca2980059b4f7da046704bed54564d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1067,
                  "y":222},
                "size":{
                  "width":94,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u13.png"}},
{
          "id":"4c9cc0a27b164990846399cdec36137f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":1042,
              "y":322},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2126228dd6324725930fda000733cf37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":1042,
                  "y":322},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d378b6cf9fc24eae87dd5f4c09487e1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":1080,
              "y":322},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce873b787c61453faabdad7fd24d0b07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":1080,
                  "y":322},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"275444007e2b49f5b191e649221c0f55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":151},
            "size":{
              "width":103,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7f95b3236d64473bebcfd54d3b94ac0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":151},
                "size":{
                  "width":103,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u68.png"}},
{
          "id":"cd2295b8d3124383a7a7caffcf2962a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":842,
              "y":156},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85c7ddd115ae454da46245f1823b60c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":842,
                  "y":156},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0059b7d75e5463e8eb4d4c8fcd398c0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":883,
              "y":150},
            "size":{
              "width":105,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"82e904e89f2e4075b132ea00ce1f6d89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":158},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cee113b9328e4d4fa83edb1800f2a1b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":158},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c64255c692814a26b95faad8c0abc59e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1056,
              "y":150},
            "size":{
              "width":105,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"f67ed822347a498fb48688fd82e56ced",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":943,
              "y":222},
            "size":{
              "width":94,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"260bb70a548c456e867de9db7d506562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":943,
                  "y":222},
                "size":{
                  "width":94,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u13.png"}},
{
          "id":"4198246e63d4459a8e50105da95e9890",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":115},
            "size":{
              "width":94,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u18_line.png"}},
{
          "id":"750c7b11c9354f3884bafeaa3be1773f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":352,
              "y":92},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dcb4ba5ec99444a9ddde7ab7e17c20e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":352,
                  "y":92},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39d46f7c7c134daf9417d7fdef7d033c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF36B3C},
            "location":{
              "x":1190,
              "y":122},
            "size":{
              "width":5,
              "height":665},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e5333ef83404310bae2844c7bfde1a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C},
                "location":{
                  "x":1190,
                  "y":122},
                "size":{
                  "width":5,
                  "height":665},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移动门店/u52.png"}},
{
          "id":"ce660f5757bb4af785c383e00fb4887d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF36B3C},
            "location":{
              "x":1125,
              "y":157},
            "size":{
              "width":100,
              "height":30},
            "rotation":"90",
            "textRotation":"90",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a2c621ef94843b4bbc5138c57e8b505",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C},
                "location":{
                  "x":1125,
                  "y":157},
                "size":{
                  "width":100,
                  "height":30},
                "rotation":"90",
                "textRotation":"90",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移动门店/u54.png"}},
{
          "id":"f4ecedd18b9144e78d65411ffcaa4a3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1169,
              "y":158},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2ed3ac9c25b44e8af13d82728af17b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1169,
                  "y":158},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00dede6bdcf3414c914fe612c0a1b35c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1190,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"716454fc866249608ba5b9c790a52944",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1190,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u0.png"}},
{
          "id":"aac999363ff54f2293859a2911027443",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-6},
            "size":{
              "width":808,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"600586282a0241efb2e672b4bed758f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-6},
                "size":{
                  "width":808,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u104.png"}},
{
          "id":"9b30db83324643b6b108460ce590626c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1044,
              "y":25},
            "size":{
              "width":66,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0682e1891a14f32bcfd6dba909dee86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1044,
                  "y":25},
                "size":{
                  "width":66,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u106.png"}},
{
          "id":"2c83921400ba48ffbdc2a4025f3541b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3F4A59},
            "location":{
              "x":0,
              "y":79},
            "size":{
              "width":80,
              "height":708},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2774aea6a9484e76832a419caaf36f59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59},
                "location":{
                  "x":0,
                  "y":79},
                "size":{
                  "width":80,
                  "height":708},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u108.png"}},
{
          "id":"59bee0a228314ab6a5d7bd7254db7904",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":78},
            "size":{
              "width":80,
              "height":511},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"272fd5fe468548e3808b0bd21098fff1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":78},
                "size":{
                  "width":80,
                  "height":511},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u110.png"}},
{
          "id":"43cf5527386448138b2043d019a6d989",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":79,
              "y":80},
            "size":{
              "width":140,
              "height":706},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaabe55000fd4593ab63a8063d7131cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":79,
                  "y":80},
                "size":{
                  "width":140,
                  "height":706},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u112.png"}},
{
          "id":"d436c66116694c2fa69cff0fca1cb063",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":147},
            "size":{
              "width":14,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ceb4fbc222b422c975905bc2bcc93c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":147},
                "size":{
                  "width":14,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u114.png"}},
{
          "id":"b9be37573b1c428aabecbc74cd25638f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":93,
              "y":100},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd2939545ca14df2adb154dd86b7275b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":93,
                  "y":100},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3733cf77384c40f0b3282bb85130b4bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2BC589,
              "opacity":1},
            "location":{
              "x":93,
              "y":141},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1570204998124e0e8084b62c3fd623cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2BC589,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":141},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"840a713fd33340b8b5aaa15201a4fcbb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":106},
            "size":{
              "width":13,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb3152c40ee74a1daea6cb17d4c38bce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":106},
                "size":{
                  "width":13,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u120.png"}},
{
          "id":"9076c6f780f94135b78573610a542a5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x66000000},
            "size":{
              "width":1196,
              "height":787}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d1a9d953e304a2ca14e59a937a27c7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x66000000},
                "size":{
                  "width":1196,
                  "height":787}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/批量新增店员/u107.png"}},
{
          "id":"10e64e6829ea40e0a1495dfe920a72bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":445,
              "y":188},
            "size":{
              "width":395,
              "height":206}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0ae1557a3b544348cc02e005b8f1109",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":445,
                  "y":188},
                "size":{
                  "width":395,
                  "height":206}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/停用店员账号/u109.png"}},
{
          "id":"79b9913f4bbc4555b16eb35358904873",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":493,
              "y":232},
            "size":{
              "width":327,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码/u111_line.png"}},
{
          "id":"39381985e4444151b16194e8c179b954",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":606,
              "y":203},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a28a140bd91d4991b8b2c9b84051d492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":606,
                  "y":203},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"459967d36e7f4c35854a56b00be36af2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":205},
            "size":{
              "width":10,
              "height":19},
            "rotation":"40",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码/u114_line.png"}},
{
          "id":"1a4c0e44a2c94b7babce0901796f1198",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":204},
            "size":{
              "width":10,
              "height":20},
            "rotation":"320",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/批量新增店员/u227_line.png"}},
{
          "id":"0489d4c5a3ef42bf856a1a13827d4007",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":567,
              "y":269},
            "size":{
              "width":177,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b399765caca8432385b93c6ecf9799d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":567,
                  "y":269},
                "size":{
                  "width":177,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b856eafc3d024ad7a9801dac8b669238",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":512,
              "y":337},
            "size":{
              "width":124,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"981abd6f6e464560b708af09edc1e1a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":512,
                  "y":337},
                "size":{
                  "width":124,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u233.png"}},
{
          "id":"e2ef34d316e3423da69d6cd66b8de826",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":649,
              "y":337},
            "size":{
              "width":124,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5841b0c52e1d4756a587f6cc4e54c4ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":649,
                  "y":337},
                "size":{
                  "width":124,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u233.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a279a7fea9dd4d1a824fd04b29958fcf":{
      "scriptId":"u0"},
    "34241783621c427e9f202edbeda90f44":{
      "scriptId":"u1"},
    "ec017fe2cf1f40f4bd3271c48743186d":{
      "scriptId":"u2"},
    "a4eea724a4c44d8e8d6adf6d50a21fb7":{
      "scriptId":"u3"},
    "826ccc788e2b4d6e90c10afcbd4ef71e":{
      "scriptId":"u4"},
    "b57ce561bb79434ea2735c54d1ba1abe":{
      "scriptId":"u5"},
    "8fb5c869eac044c1b28fcfe0336efac3":{
      "scriptId":"u6"},
    "47235f871c4d431e8e00024780687869":{
      "scriptId":"u7"},
    "9f88b71e8581469381c80e712b9aa0e4":{
      "scriptId":"u8"},
    "a201f02561e4437da95c52b300413f0c":{
      "scriptId":"u9"},
    "d0bd8b2539274ff29a009a42488cd887":{
      "scriptId":"u10"},
    "2e95f1a0cbaf4f75afc26a84d8eed304":{
      "scriptId":"u11"},
    "df6df5ae091c460792cfeb4a27247c73":{
      "scriptId":"u12"},
    "8bbb3b41ff7141b2b918aa05830fafe3":{
      "scriptId":"u13"},
    "4bd6968250d745539c8629448c5c22bb":{
      "scriptId":"u14"},
    "86978339a9d049e0827a1681580cc6db":{
      "scriptId":"u15"},
    "351ebe2126524b43939d35c59140645e":{
      "scriptId":"u16"},
    "28d7a3afe9964ff194eb0544bc415e4c":{
      "scriptId":"u17"},
    "de64046bfce64de89d78ec40e1609851":{
      "scriptId":"u18"},
    "1b31b428b0074ee8803dda6933d6fc40":{
      "scriptId":"u19"},
    "56490a1dc59a44a5817d6718dda0cd7b":{
      "scriptId":"u20"},
    "29f86156782745d480c36a1be631108a":{
      "scriptId":"u21"},
    "622f1887dbf7491c98a3400d80826c81":{
      "scriptId":"u22"},
    "57eb82ce875f4485b3e857b6a4ef4daa":{
      "scriptId":"u23"},
    "75687de5f29f46ccb216399630647a76":{
      "scriptId":"u24"},
    "c6917fdf8050433eaba0e2dd6faf7729":{
      "scriptId":"u25"},
    "95d0ae32824244039407d47fe7a54344":{
      "scriptId":"u26"},
    "e8156543dd8e4fe99a67b8219671babf":{
      "scriptId":"u27"},
    "0a65f8bb0297465dbcb458244ae5a973":{
      "scriptId":"u28"},
    "6ee1b47c359d4afb84127498f6dfd368":{
      "scriptId":"u29"},
    "d8728517914f421cad819aedf10d6151":{
      "scriptId":"u30"},
    "a2901c21cfec4d1bb97c283bef43f18e":{
      "scriptId":"u31"},
    "6f8145e5975b4ed888c67143d74f45fa":{
      "scriptId":"u32"},
    "5c78f5c51b264e13b2e2403c014e9404":{
      "scriptId":"u33"},
    "b50b2a77634a400991f213243abe3b0b":{
      "scriptId":"u34"},
    "e759c9583b204900b19c0387a2cd2ca6":{
      "scriptId":"u35"},
    "cab501d475c247209948e2f2a8691222":{
      "scriptId":"u36"},
    "80225f608cf142caa47b88271294fd92":{
      "scriptId":"u37"},
    "608bd63ac94f490191ed4ae6df1e380b":{
      "scriptId":"u38"},
    "b6980c4bb64f40779a27a0bc916d88e1":{
      "scriptId":"u39"},
    "2ab0f756526448359428e24b01474da5":{
      "scriptId":"u40"},
    "42f95bc5f3cb42ccb90b3ff9c0c22dcd":{
      "scriptId":"u41"},
    "e965c2eaedb2457f84b806ca783d65f3":{
      "scriptId":"u42"},
    "a44d5d6458ac43bf867c85d0ecc143b2":{
      "scriptId":"u43"},
    "b7a1d7cc9a1a4b769e56d0e365efe2fe":{
      "scriptId":"u44"},
    "9c7b993a14e84fe390c08390f49e9ab0":{
      "scriptId":"u45"},
    "b415f46bdb3a4dc2aaaf33c6fcd7724d":{
      "scriptId":"u46"},
    "59338839b57441309202eec28ab83867":{
      "scriptId":"u47"},
    "00976ebf69bb480ebdb9757deb91b3bc":{
      "scriptId":"u48"},
    "89c1019201a5446783b849b713d98d64":{
      "scriptId":"u49"},
    "73c6ef4e9c0b4691964cb81961e5c616":{
      "scriptId":"u50"},
    "9570996e9c394fc3b8a8d7b78eab824a":{
      "scriptId":"u51"},
    "8ceef352f80142d5a5e6a7464b92a9fb":{
      "scriptId":"u52"},
    "3a568ec9e55d4684a0d30bddada1e59b":{
      "scriptId":"u53"},
    "fbb4e24fb8e54323991d77e0cb0dafad":{
      "scriptId":"u54"},
    "a363f4a1123a4d4d8e9caebccb5fa8da":{
      "scriptId":"u55"},
    "4c40d227ab2c44078bba6dc5312d5f95":{
      "scriptId":"u56"},
    "474797279a3c4c42aff86f1e12eb0368":{
      "scriptId":"u57"},
    "66f95f8babe24b6ea3a7b53931e36d8a":{
      "scriptId":"u58"},
    "1dfccd5009064784bbbf6d866845ff10":{
      "scriptId":"u59"},
    "66e6838dd4584de8a20a835242910b40":{
      "scriptId":"u60"},
    "26f45e8ee0a44507b3a05b0cfbdd66d4":{
      "scriptId":"u61"},
    "caab7cd439954a6fa055a1c8646b9eac":{
      "scriptId":"u62"},
    "a0ca2980059b4f7da046704bed54564d":{
      "scriptId":"u63"},
    "4c9cc0a27b164990846399cdec36137f":{
      "scriptId":"u64"},
    "2126228dd6324725930fda000733cf37":{
      "scriptId":"u65"},
    "d378b6cf9fc24eae87dd5f4c09487e1c":{
      "scriptId":"u66"},
    "ce873b787c61453faabdad7fd24d0b07":{
      "scriptId":"u67"},
    "275444007e2b49f5b191e649221c0f55":{
      "scriptId":"u68"},
    "f7f95b3236d64473bebcfd54d3b94ac0":{
      "scriptId":"u69"},
    "cd2295b8d3124383a7a7caffcf2962a9":{
      "scriptId":"u70"},
    "85c7ddd115ae454da46245f1823b60c6":{
      "scriptId":"u71"},
    "f0059b7d75e5463e8eb4d4c8fcd398c0":{
      "scriptId":"u72"},
    "82e904e89f2e4075b132ea00ce1f6d89":{
      "scriptId":"u73"},
    "cee113b9328e4d4fa83edb1800f2a1b6":{
      "scriptId":"u74"},
    "c64255c692814a26b95faad8c0abc59e":{
      "scriptId":"u75"},
    "f67ed822347a498fb48688fd82e56ced":{
      "scriptId":"u76"},
    "260bb70a548c456e867de9db7d506562":{
      "scriptId":"u77"},
    "4198246e63d4459a8e50105da95e9890":{
      "scriptId":"u78"},
    "750c7b11c9354f3884bafeaa3be1773f":{
      "scriptId":"u79"},
    "5dcb4ba5ec99444a9ddde7ab7e17c20e":{
      "scriptId":"u80"},
    "39d46f7c7c134daf9417d7fdef7d033c":{
      "scriptId":"u81"},
    "9e5333ef83404310bae2844c7bfde1a3":{
      "scriptId":"u82"},
    "ce660f5757bb4af785c383e00fb4887d":{
      "scriptId":"u83"},
    "5a2c621ef94843b4bbc5138c57e8b505":{
      "scriptId":"u84"},
    "f4ecedd18b9144e78d65411ffcaa4a3c":{
      "scriptId":"u85"},
    "f2ed3ac9c25b44e8af13d82728af17b4":{
      "scriptId":"u86"},
    "00dede6bdcf3414c914fe612c0a1b35c":{
      "scriptId":"u87"},
    "716454fc866249608ba5b9c790a52944":{
      "scriptId":"u88"},
    "aac999363ff54f2293859a2911027443":{
      "scriptId":"u89"},
    "600586282a0241efb2e672b4bed758f6":{
      "scriptId":"u90"},
    "9b30db83324643b6b108460ce590626c":{
      "scriptId":"u91"},
    "f0682e1891a14f32bcfd6dba909dee86":{
      "scriptId":"u92"},
    "2c83921400ba48ffbdc2a4025f3541b2":{
      "scriptId":"u93"},
    "2774aea6a9484e76832a419caaf36f59":{
      "scriptId":"u94"},
    "59bee0a228314ab6a5d7bd7254db7904":{
      "scriptId":"u95"},
    "272fd5fe468548e3808b0bd21098fff1":{
      "scriptId":"u96"},
    "43cf5527386448138b2043d019a6d989":{
      "scriptId":"u97"},
    "aaabe55000fd4593ab63a8063d7131cd":{
      "scriptId":"u98"},
    "d436c66116694c2fa69cff0fca1cb063":{
      "scriptId":"u99"},
    "0ceb4fbc222b422c975905bc2bcc93c3":{
      "scriptId":"u100"},
    "b9be37573b1c428aabecbc74cd25638f":{
      "scriptId":"u101"},
    "dd2939545ca14df2adb154dd86b7275b":{
      "scriptId":"u102"},
    "3733cf77384c40f0b3282bb85130b4bf":{
      "scriptId":"u103"},
    "1570204998124e0e8084b62c3fd623cd":{
      "scriptId":"u104"},
    "840a713fd33340b8b5aaa15201a4fcbb":{
      "scriptId":"u105"},
    "fb3152c40ee74a1daea6cb17d4c38bce":{
      "scriptId":"u106"},
    "9076c6f780f94135b78573610a542a5b":{
      "scriptId":"u107"},
    "4d1a9d953e304a2ca14e59a937a27c7d":{
      "scriptId":"u108"},
    "10e64e6829ea40e0a1495dfe920a72bf":{
      "scriptId":"u109"},
    "b0ae1557a3b544348cc02e005b8f1109":{
      "scriptId":"u110"},
    "79b9913f4bbc4555b16eb35358904873":{
      "scriptId":"u111"},
    "39381985e4444151b16194e8c179b954":{
      "scriptId":"u112"},
    "a28a140bd91d4991b8b2c9b84051d492":{
      "scriptId":"u113"},
    "459967d36e7f4c35854a56b00be36af2":{
      "scriptId":"u114"},
    "1a4c0e44a2c94b7babce0901796f1198":{
      "scriptId":"u115"},
    "0489d4c5a3ef42bf856a1a13827d4007":{
      "scriptId":"u116"},
    "b399765caca8432385b93c6ecf9799d7":{
      "scriptId":"u117"},
    "b856eafc3d024ad7a9801dac8b669238":{
      "scriptId":"u118"},
    "981abd6f6e464560b708af09edc1e1a0":{
      "scriptId":"u119"},
    "e2ef34d316e3423da69d6cd66b8de826":{
      "scriptId":"u120"},
    "5841b0c52e1d4756a587f6cc4e54c4ee":{
      "scriptId":"u121"}}});