$axure.loadCurrentPage({
  "url":"适用门店.html",
  "generationDate":new Date(1448257275488.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1ad2b75d77714980b9a5f16d8cc9ba89",
    "type":"Axure:Page",
    "name":"适用门店",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d0da208710647bb8675a0eb44378bfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":550,
              "y":0},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc6c01e1492f43589b32109c62a6cdc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":550,
                  "y":0},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信会话中获取卡券/u0.png"}},
{
          "id":"cf5c7ecebe8b4de5999edaba7f51610c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "location":{
              "x":550,
              "y":18},
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d355ae62591743b8a8c14bd55fcf7c34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "location":{
                  "x":550,
                  "y":18},
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信会话中获取卡券/u2.png"}},
{
          "id":"e397f3809b03430fab0f4884626a3741",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":0},
            "size":{
              "width":320,
              "height":18},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bef09665ea8b44729f26f9f361fae917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":0},
                "size":{
                  "width":320,
                  "height":18},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信会话中获取卡券/u4.png"}},
{
          "id":"6de4eceefb7f495d8dab865035fcbc3b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":27},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff20b82231644ec4a6f8dd17f52ab849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":27},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信会话中获取卡券/u6.png"}},
{
          "id":"e52f0a75aa044176b72777cbf944beb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":696,
              "y":35},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96d083d910474d91ab306f62f7da14c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":696,
                  "y":35},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0971a931a8d14c9288700cbedf699201",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":551,
              "y":61},
            "size":{
              "width":318,
              "height":505}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e09d5e606afc43959bebc37b26d7f6f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":551,
                  "y":61},
                "size":{
                  "width":318,
                  "height":505}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u10.jpg"}},
{
          "id":"d98d33315860482da9832cfb3b4289cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":71},
            "size":{
              "width":140,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17711b7aca22487abb44741117452325",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":71},
                "size":{
                  "width":140,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f61a004e21514bad8a7a218ee15ce44c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afc9c72e6e4f43c0b9aa45da727db97e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机卡包--平台卡券_微信卡券/u0.png"}},
{
          "id":"69545063d61f4c488bf5ab8984a83af2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "location":{
              "x":0,
              "y":18},
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78a6d1cf30f9405a9731a1b462bbabc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "location":{
                  "x":0,
                  "y":18},
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信会话中获取卡券/u2.png"}},
{
          "id":"5d01fbe050304221ba2b54b6d61f5aa8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "size":{
              "width":320,
              "height":18},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fc150ee85a7423895e2c73c7e1faeb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "size":{
                  "width":320,
                  "height":18},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信会话中获取卡券/u4.png"}},
{
          "id":"a1f11947fba74b5291770e1a19a1e064",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":0,
              "y":28},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7b0c9d7469a44e98a464a47c955ea0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":0,
                  "y":28},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信会话中获取卡券/u6.png"}},
{
          "id":"c8e4057e770743ca8fccaa3aeb24cabd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":145,
              "y":34},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c0fea817ced486baa4374c841907e69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":145,
                  "y":34},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdc0476540e5440aa30156d1360e5eec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFA1A1A1},
            "location":{
              "x":9,
              "y":67},
            "size":{
              "width":300,
              "height":132}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f921f3a0485400a85e0efc6e3557f10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1},
                "location":{
                  "x":9,
                  "y":67},
                "size":{
                  "width":300,
                  "height":132}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机卡包--平台卡券_微信卡券/u10.png"}},
{
          "id":"379dfae07d114345b6803b8ecdaf1b26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":17,
              "y":75},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0d3596225204579b3f1f0c01b89114a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":17,
                  "y":75},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信会话中获取卡券/u72.png"}},
{
          "id":"e54ab9fcc7ef428590f28a7bc7668eb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"15px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":71,
              "y":90},
            "size":{
              "width":63,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2125bca6557e48419240210a98cd1ca9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"15px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":71,
                  "y":90},
                "size":{
                  "width":63,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39b276a8e3724eb4b9d04c6ccae84245",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":32,
              "y":172},
            "size":{
              "width":210,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95dcccff743e4100a3bc4b3a3c07ecf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":32,
                  "y":172},
                "size":{
                  "width":210,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"710ab4372d594af48b567a74d990dd73",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":112,
              "y":126},
            "size":{
              "width":94,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfbc579079684b5f85120c2222b305a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":112,
                  "y":126},
                "size":{
                  "width":94,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2027ee00d39b4dfcb7b59a3f1039c7d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFA1A1A1},
            "location":{
              "x":9,
              "y":437},
            "size":{
              "width":300,
              "height":131}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d6a10da77a242e5b0bbdf3c799a8a60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1},
                "location":{
                  "x":9,
                  "y":437},
                "size":{
                  "width":300,
                  "height":131}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机卡包--平台卡券_微信卡券/u68.png"}},
{
          "id":"ac1d1399e6e0473a96e36c29b9f35475",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":20,
              "y":449},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ec3ca1ab2e544d185372fd258b06259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":20,
                  "y":449},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信会话中获取卡券/u72.png"}},
{
          "id":"4ed1abb798084290b6a1b581ef135206",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"15px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":84,
              "y":456},
            "size":{
              "width":63,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44ee97587d364c9780f95cd78071c6af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"15px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":84,
                  "y":456},
                "size":{
                  "width":63,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8395afc408a34e2d93fad104a566d99e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":33,
              "y":524},
            "size":{
              "width":210,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6afaa6eb69b449548db88060f93a4e62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":33,
                  "y":524},
                "size":{
                  "width":210,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15f6dbf3c1c54d26b16847d8d7a66db0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":110,
              "y":476},
            "size":{
              "width":133,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"151169329a6846e3931d2b02742cbfcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":476},
                "size":{
                  "width":133,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"098b61697cd6409aae96401c4cbf732f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":198},
            "size":{
              "width":300,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cb4b3ac5b2d4bfdb64ab8f6f5bf1b10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":198},
                "size":{
                  "width":300,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机卡包--平台卡券_微信卡券/u78.png"}},
{
          "id":"368254ac324741ec9e7767984b7d0f1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":84,
              "y":209},
            "size":{
              "width":150,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd28f56ac3f74c65845635a3afcd2dcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":84,
                  "y":209},
                "size":{
                  "width":150,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信会话中获取卡券/u114.png"}},
{
          "id":"b7fb975a04f143498f2b0ec96899fe09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":97,
              "y":319},
            "size":{
              "width":108,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd6e962ede5244279bf1b8868010628d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":97,
                  "y":319},
                "size":{
                  "width":108,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25788923abeb4cf38101b8bfc0f287fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":9,
              "y":387},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41d934c632314a17aa0838c6d78e24a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":9,
                  "y":387},
                "size":{
                  "width":300,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机卡包--平台卡券_微信卡券/u84.png"}},
{
          "id":"6c7eb9f5760b401f9f89858a5ad155ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":9,
              "y":348},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0f4c76f87ff49fab85edeaa0dc539f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":9,
                  "y":348},
                "size":{
                  "width":300,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机卡包--平台卡券_微信卡券/u84.png"}},
{
          "id":"19e99ab11c0b423199a14ee0ea239b1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":12,
              "y":400},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92748f3ae0584676b06692a373c4b304",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":12,
                  "y":400},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4ecfdb8aa304dd093a11ccff70bcd35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":12,
              "y":360},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0758c131c7746339886f0efccafa03b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":12,
                  "y":360},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a592d278120a4e59875ae80b461c8d21",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":280,
              "y":394},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95db482ef52c471692f0038bad69f96a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":280,
                  "y":394},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u48.png"}},
{
          "id":"a7d4afc22a29495695ed626820e43025",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":280,
              "y":352},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60bc9753369c4c67b7859544601677e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":280,
                  "y":352},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u48.png"}},
{
          "id":"676bd39968644d1e980bce755e5df61c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7F666666},
            "location":{
              "x":0,
              "y":18},
            "size":{
              "width":320,
              "height":550},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5869c1211694c16936c4ca21583f0f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F666666},
                "location":{
                  "x":0,
                  "y":18},
                "size":{
                  "width":320,
                  "height":550},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/使用说明/u48.png"}},
{
          "id":"e157699b3656446e838f4194600c5792",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":61},
            "size":{
              "width":257,
              "height":419}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f55ba0255e2941528399987ef935100f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":61},
                "size":{
                  "width":257,
                  "height":419}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u64.png"}},
{
          "id":"ca238ae187ee42b7b16343ca1fc36ee6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC00},
            "location":{
              "x":33,
              "y":61},
            "size":{
              "width":257,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bdc6d9c231f43d38c4bc555230fd1de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00},
                "location":{
                  "x":33,
                  "y":61},
                "size":{
                  "width":257,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u66.png"}},
{
          "id":"d2ce23754c49473faabd9ea023ba2e69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":132,
              "y":76},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9bdd8722d7241b0b2f832ddb1885a5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":132,
                  "y":76},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"193b6001a1204acb806f74ac0af6e8de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":106},
            "size":{
              "width":257,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4827d9c1930d4f429213e1b1e835f011",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":106},
                "size":{
                  "width":257,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u70.png"}},
{
          "id":"a3a832378b4a4b79b69acb8595aa24c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":110,
              "y":122},
            "size":{
              "width":99,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6140e34e03c34fcb91cbaf50ef0e8cdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":110,
                  "y":122},
                "size":{
                  "width":99,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8461eb778cec4e8fac55aec431d62acf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":150},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb5ed8e1ec2b49cdb79d5fc60f248a8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":150},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd1885fd975f42a79bbd936fe568c23e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":121},
            "size":{
              "width":57,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04938a529da14504a919e4b97bf39c62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":121},
                "size":{
                  "width":57,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u76.png"}},
{
          "id":"17068530798f4096ab842aa2a84988ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":119},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fde676b367fb498ea9d98eace32cd660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":119},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u78.png"}},
{
          "id":"27c299de82e34204a9f40b4951cb86a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":123},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8907c349037149d09d6678e3856dc7c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":123},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98497e8aca9b4ecbab2eefd7946d8073",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":185},
            "size":{
              "width":257,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93fd1ef4b8a540ce803fe0894929f9a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":185},
                "size":{
                  "width":257,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u70.png"}},
{
          "id":"f09c1b880299452dac9f3ba90925922e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":110,
              "y":201},
            "size":{
              "width":99,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c03b825cfdff4f55b76857d7d57ee3ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":110,
                  "y":201},
                "size":{
                  "width":99,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a8f887168ce4168bbc309447aef7e6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":229},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7d39f0fc3a24f68a2a71080d5bdf0dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":229},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e5408cdbd28490785f24d9a6370b3a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":200},
            "size":{
              "width":57,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"069fc9f9a3044460aec164abad815e0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":200},
                "size":{
                  "width":57,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u76.png"}},
{
          "id":"3a9d80a2feec47aeb7c5233507b30e5c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":198},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65d755cb4442487ea0b213653a602450",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":198},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u78.png"}},
{
          "id":"158f2ac30aac410281bbf2a857616357",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":202},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7679bd8f50ab4ed0b6dfb02b4931455e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":202},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29f0ac15fad24d48b71943f5dd050c4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":264},
            "size":{
              "width":257,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d61ee40b4aa4ed68afa409fc0ec8bf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":264},
                "size":{
                  "width":257,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u70.png"}},
{
          "id":"dc6fd28d3e0d445da8641c3a26511b5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":110,
              "y":280},
            "size":{
              "width":99,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8407dc4edcc249a68b693622d2ecc698",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":110,
                  "y":280},
                "size":{
                  "width":99,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39f6e8ff60ee412cb5a5bba678934786",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":308},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ebd5b4a65be45aeb42afd4aaef72007",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":308},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a91ecff8c7244a48db88da0dd6d671a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":279},
            "size":{
              "width":57,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d8e6f5291a3481f82012336749eaacd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":279},
                "size":{
                  "width":57,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u76.png"}},
{
          "id":"052009221dc74ffd92ec5913a19b2fd6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":277},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79b48178ac6e4b52a1dd69443b80e19f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":277},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u78.png"}},
{
          "id":"a388e157e0d24bdc9128fa4da8aa07bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":281},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39db5d333ac048c4b0a9673405d596fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":281},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"909f1cf144654dd1aab96b446a418a5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":343},
            "size":{
              "width":257,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"140cb63cefdd40b9b6d5c5eb6c231690",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":343},
                "size":{
                  "width":257,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u70.png"}},
{
          "id":"d18599be70564eb9a75a678c88850f9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":110,
              "y":359},
            "size":{
              "width":99,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f227a61bc49441e7be30c917027ba643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":110,
                  "y":359},
                "size":{
                  "width":99,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"086b5cd732274916954e92f06e7f97cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":110,
              "y":387},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5904142adf6b4ba58d9702545243ffe6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":387},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"909e065f790040bdbbbfe5d7482b8f89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":358},
            "size":{
              "width":57,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b21ef664b1f4f6b9d65c198a511d3e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":358},
                "size":{
                  "width":57,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u76.png"}},
{
          "id":"4037d51bed234fd38b73280e0d7e2b20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":356},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc3f852fbf324cc988489bffeb788c21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":356},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u78.png"}},
{
          "id":"e17ef040c4594ccc8193f6bb8b9010d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":360},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad6a913e56b94304853497beed4ad24e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":360},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d501d9fc35554ca6946a0b4db087c577",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":110,
              "y":438},
            "size":{
              "width":99,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b26fbed14904b65b7b28831ba6190a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":110,
                  "y":438},
                "size":{
                  "width":99,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a68d1577e6c64ef3939459905173f3f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":437},
            "size":{
              "width":57,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a662ea1ea6e743d6a938963edd4684ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":437},
                "size":{
                  "width":57,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/适用门店/u120.png"}},
{
          "id":"28f539fec42d498e91c6593ca90f6fd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":265,
              "y":52},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"34"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c0aea3c657641f3bc75c6b1d7949fc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":265,
                  "y":52},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"34"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/使用说明/u60.png"}},
{
          "id":"2b8878ab8ebf4eaaa4160a516504d25b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":57},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ede146b544b4c778626b2f843d6aa8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":57},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u164.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d0da208710647bb8675a0eb44378bfa":{
      "scriptId":"u0"},
    "cc6c01e1492f43589b32109c62a6cdc7":{
      "scriptId":"u1"},
    "cf5c7ecebe8b4de5999edaba7f51610c":{
      "scriptId":"u2"},
    "d355ae62591743b8a8c14bd55fcf7c34":{
      "scriptId":"u3"},
    "e397f3809b03430fab0f4884626a3741":{
      "scriptId":"u4"},
    "bef09665ea8b44729f26f9f361fae917":{
      "scriptId":"u5"},
    "6de4eceefb7f495d8dab865035fcbc3b":{
      "scriptId":"u6"},
    "ff20b82231644ec4a6f8dd17f52ab849":{
      "scriptId":"u7"},
    "e52f0a75aa044176b72777cbf944beb1":{
      "scriptId":"u8"},
    "96d083d910474d91ab306f62f7da14c6":{
      "scriptId":"u9"},
    "0971a931a8d14c9288700cbedf699201":{
      "scriptId":"u10"},
    "e09d5e606afc43959bebc37b26d7f6f2":{
      "scriptId":"u11"},
    "d98d33315860482da9832cfb3b4289cf":{
      "scriptId":"u12"},
    "17711b7aca22487abb44741117452325":{
      "scriptId":"u13"},
    "f61a004e21514bad8a7a218ee15ce44c":{
      "scriptId":"u14"},
    "afc9c72e6e4f43c0b9aa45da727db97e":{
      "scriptId":"u15"},
    "69545063d61f4c488bf5ab8984a83af2":{
      "scriptId":"u16"},
    "78a6d1cf30f9405a9731a1b462bbabc7":{
      "scriptId":"u17"},
    "5d01fbe050304221ba2b54b6d61f5aa8":{
      "scriptId":"u18"},
    "1fc150ee85a7423895e2c73c7e1faeb0":{
      "scriptId":"u19"},
    "a1f11947fba74b5291770e1a19a1e064":{
      "scriptId":"u20"},
    "a7b0c9d7469a44e98a464a47c955ea0c":{
      "scriptId":"u21"},
    "c8e4057e770743ca8fccaa3aeb24cabd":{
      "scriptId":"u22"},
    "2c0fea817ced486baa4374c841907e69":{
      "scriptId":"u23"},
    "fdc0476540e5440aa30156d1360e5eec":{
      "scriptId":"u24"},
    "2f921f3a0485400a85e0efc6e3557f10":{
      "scriptId":"u25"},
    "379dfae07d114345b6803b8ecdaf1b26":{
      "scriptId":"u26"},
    "d0d3596225204579b3f1f0c01b89114a":{
      "scriptId":"u27"},
    "e54ab9fcc7ef428590f28a7bc7668eb3":{
      "scriptId":"u28"},
    "2125bca6557e48419240210a98cd1ca9":{
      "scriptId":"u29"},
    "39b276a8e3724eb4b9d04c6ccae84245":{
      "scriptId":"u30"},
    "95dcccff743e4100a3bc4b3a3c07ecf5":{
      "scriptId":"u31"},
    "710ab4372d594af48b567a74d990dd73":{
      "scriptId":"u32"},
    "cfbc579079684b5f85120c2222b305a4":{
      "scriptId":"u33"},
    "2027ee00d39b4dfcb7b59a3f1039c7d7":{
      "scriptId":"u34"},
    "3d6a10da77a242e5b0bbdf3c799a8a60":{
      "scriptId":"u35"},
    "ac1d1399e6e0473a96e36c29b9f35475":{
      "scriptId":"u36"},
    "1ec3ca1ab2e544d185372fd258b06259":{
      "scriptId":"u37"},
    "4ed1abb798084290b6a1b581ef135206":{
      "scriptId":"u38"},
    "44ee97587d364c9780f95cd78071c6af":{
      "scriptId":"u39"},
    "8395afc408a34e2d93fad104a566d99e":{
      "scriptId":"u40"},
    "6afaa6eb69b449548db88060f93a4e62":{
      "scriptId":"u41"},
    "15f6dbf3c1c54d26b16847d8d7a66db0":{
      "scriptId":"u42"},
    "151169329a6846e3931d2b02742cbfcb":{
      "scriptId":"u43"},
    "098b61697cd6409aae96401c4cbf732f":{
      "scriptId":"u44"},
    "6cb4b3ac5b2d4bfdb64ab8f6f5bf1b10":{
      "scriptId":"u45"},
    "368254ac324741ec9e7767984b7d0f1f":{
      "scriptId":"u46"},
    "cd28f56ac3f74c65845635a3afcd2dcd":{
      "scriptId":"u47"},
    "b7fb975a04f143498f2b0ec96899fe09":{
      "scriptId":"u48"},
    "fd6e962ede5244279bf1b8868010628d":{
      "scriptId":"u49"},
    "25788923abeb4cf38101b8bfc0f287fa":{
      "scriptId":"u50"},
    "41d934c632314a17aa0838c6d78e24a4":{
      "scriptId":"u51"},
    "6c7eb9f5760b401f9f89858a5ad155ed":{
      "scriptId":"u52"},
    "b0f4c76f87ff49fab85edeaa0dc539f9":{
      "scriptId":"u53"},
    "19e99ab11c0b423199a14ee0ea239b1e":{
      "scriptId":"u54"},
    "92748f3ae0584676b06692a373c4b304":{
      "scriptId":"u55"},
    "f4ecfdb8aa304dd093a11ccff70bcd35":{
      "scriptId":"u56"},
    "d0758c131c7746339886f0efccafa03b":{
      "scriptId":"u57"},
    "a592d278120a4e59875ae80b461c8d21":{
      "scriptId":"u58"},
    "95db482ef52c471692f0038bad69f96a":{
      "scriptId":"u59"},
    "a7d4afc22a29495695ed626820e43025":{
      "scriptId":"u60"},
    "60bc9753369c4c67b7859544601677e5":{
      "scriptId":"u61"},
    "676bd39968644d1e980bce755e5df61c":{
      "scriptId":"u62"},
    "d5869c1211694c16936c4ca21583f0f1":{
      "scriptId":"u63"},
    "e157699b3656446e838f4194600c5792":{
      "scriptId":"u64"},
    "f55ba0255e2941528399987ef935100f":{
      "scriptId":"u65"},
    "ca238ae187ee42b7b16343ca1fc36ee6":{
      "scriptId":"u66"},
    "1bdc6d9c231f43d38c4bc555230fd1de":{
      "scriptId":"u67"},
    "d2ce23754c49473faabd9ea023ba2e69":{
      "scriptId":"u68"},
    "c9bdd8722d7241b0b2f832ddb1885a5d":{
      "scriptId":"u69"},
    "193b6001a1204acb806f74ac0af6e8de":{
      "scriptId":"u70"},
    "4827d9c1930d4f429213e1b1e835f011":{
      "scriptId":"u71"},
    "a3a832378b4a4b79b69acb8595aa24c0":{
      "scriptId":"u72"},
    "6140e34e03c34fcb91cbaf50ef0e8cdb":{
      "scriptId":"u73"},
    "8461eb778cec4e8fac55aec431d62acf":{
      "scriptId":"u74"},
    "cb5ed8e1ec2b49cdb79d5fc60f248a8e":{
      "scriptId":"u75"},
    "bd1885fd975f42a79bbd936fe568c23e":{
      "scriptId":"u76"},
    "04938a529da14504a919e4b97bf39c62":{
      "scriptId":"u77"},
    "17068530798f4096ab842aa2a84988ca":{
      "scriptId":"u78"},
    "fde676b367fb498ea9d98eace32cd660":{
      "scriptId":"u79"},
    "27c299de82e34204a9f40b4951cb86a2":{
      "scriptId":"u80"},
    "8907c349037149d09d6678e3856dc7c5":{
      "scriptId":"u81"},
    "98497e8aca9b4ecbab2eefd7946d8073":{
      "scriptId":"u82"},
    "93fd1ef4b8a540ce803fe0894929f9a0":{
      "scriptId":"u83"},
    "f09c1b880299452dac9f3ba90925922e":{
      "scriptId":"u84"},
    "c03b825cfdff4f55b76857d7d57ee3ac":{
      "scriptId":"u85"},
    "4a8f887168ce4168bbc309447aef7e6a":{
      "scriptId":"u86"},
    "d7d39f0fc3a24f68a2a71080d5bdf0dc":{
      "scriptId":"u87"},
    "4e5408cdbd28490785f24d9a6370b3a9":{
      "scriptId":"u88"},
    "069fc9f9a3044460aec164abad815e0f":{
      "scriptId":"u89"},
    "3a9d80a2feec47aeb7c5233507b30e5c":{
      "scriptId":"u90"},
    "65d755cb4442487ea0b213653a602450":{
      "scriptId":"u91"},
    "158f2ac30aac410281bbf2a857616357":{
      "scriptId":"u92"},
    "7679bd8f50ab4ed0b6dfb02b4931455e":{
      "scriptId":"u93"},
    "29f0ac15fad24d48b71943f5dd050c4b":{
      "scriptId":"u94"},
    "2d61ee40b4aa4ed68afa409fc0ec8bf5":{
      "scriptId":"u95"},
    "dc6fd28d3e0d445da8641c3a26511b5e":{
      "scriptId":"u96"},
    "8407dc4edcc249a68b693622d2ecc698":{
      "scriptId":"u97"},
    "39f6e8ff60ee412cb5a5bba678934786":{
      "scriptId":"u98"},
    "5ebd5b4a65be45aeb42afd4aaef72007":{
      "scriptId":"u99"},
    "0a91ecff8c7244a48db88da0dd6d671a":{
      "scriptId":"u100"},
    "6d8e6f5291a3481f82012336749eaacd":{
      "scriptId":"u101"},
    "052009221dc74ffd92ec5913a19b2fd6":{
      "scriptId":"u102"},
    "79b48178ac6e4b52a1dd69443b80e19f":{
      "scriptId":"u103"},
    "a388e157e0d24bdc9128fa4da8aa07bd":{
      "scriptId":"u104"},
    "39db5d333ac048c4b0a9673405d596fd":{
      "scriptId":"u105"},
    "909f1cf144654dd1aab96b446a418a5e":{
      "scriptId":"u106"},
    "140cb63cefdd40b9b6d5c5eb6c231690":{
      "scriptId":"u107"},
    "d18599be70564eb9a75a678c88850f9f":{
      "scriptId":"u108"},
    "f227a61bc49441e7be30c917027ba643":{
      "scriptId":"u109"},
    "086b5cd732274916954e92f06e7f97cd":{
      "scriptId":"u110"},
    "5904142adf6b4ba58d9702545243ffe6":{
      "scriptId":"u111"},
    "909e065f790040bdbbbfe5d7482b8f89":{
      "scriptId":"u112"},
    "9b21ef664b1f4f6b9d65c198a511d3e6":{
      "scriptId":"u113"},
    "4037d51bed234fd38b73280e0d7e2b20":{
      "scriptId":"u114"},
    "dc3f852fbf324cc988489bffeb788c21":{
      "scriptId":"u115"},
    "e17ef040c4594ccc8193f6bb8b9010d9":{
      "scriptId":"u116"},
    "ad6a913e56b94304853497beed4ad24e":{
      "scriptId":"u117"},
    "d501d9fc35554ca6946a0b4db087c577":{
      "scriptId":"u118"},
    "3b26fbed14904b65b7b28831ba6190a1":{
      "scriptId":"u119"},
    "a68d1577e6c64ef3939459905173f3f5":{
      "scriptId":"u120"},
    "a662ea1ea6e743d6a938963edd4684ef":{
      "scriptId":"u121"},
    "28f539fec42d498e91c6593ca90f6fd2":{
      "scriptId":"u122"},
    "1c0aea3c657641f3bc75c6b1d7949fc4":{
      "scriptId":"u123"},
    "2b8878ab8ebf4eaaa4160a516504d25b":{
      "scriptId":"u124"},
    "5ede146b544b4c778626b2f843d6aa8a":{
      "scriptId":"u125"}}});