$axure.loadCurrentPage({
  "url":"角色管理.html",
  "generationDate":new Date(1448247503577.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"53d540bc51544f0abcad438b4328590d",
    "type":"Axure:Page",
    "name":"角色管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"81541d40f815424597a83fdd2523e69b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":79},
            "size":{
              "width":1190,
              "height":707},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bbf055874b84d0c8c14909b4bb77366",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":79},
                "size":{
                  "width":1190,
                  "height":707},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/角色管理/u0.png"}},
{
          "id":"3837f56c396e4625b27b97a1c6b14d03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1190,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9fe10dac4134064903a2af5a9369d04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1190,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u0.png"}},
{
          "id":"c12fbddcacda46858a7b62bfbec510f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1},
            "size":{
              "width":808,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7be59e31cddb4f8a9c390f403a6364ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1},
                "size":{
                  "width":808,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u104.png"}},
{
          "id":"b9ff4eb6f5954cf9b53a4383421f4b22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1044,
              "y":24},
            "size":{
              "width":66,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b213d2cf0d14536a1e93d609587a2c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1044,
                  "y":24},
                "size":{
                  "width":66,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u106.png"}},
{
          "id":"78357e4e35d54edaa5ef73218c2cae92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3F4A59},
            "location":{
              "x":0,
              "y":78},
            "size":{
              "width":80,
              "height":708},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7816f8e28195475fb228cf6b110ed3b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59},
                "location":{
                  "x":0,
                  "y":78},
                "size":{
                  "width":80,
                  "height":708},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u108.png"}},
{
          "id":"8a53ff81b23e48b38bb9edb6587d3931",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-2,
              "y":78},
            "size":{
              "width":80,
              "height":511},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01f3d6b7698547e6bedc2bd03fb36510",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-2,
                  "y":78},
                "size":{
                  "width":80,
                  "height":511},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u110.png"}},
{
          "id":"42799df93e1a424d9f96e5ea08a71841",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":78,
              "y":80},
            "size":{
              "width":140,
              "height":706},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3e14ce18f0b4fea83821738d55d7eb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":78,
                  "y":80},
                "size":{
                  "width":140,
                  "height":706},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u112.png"}},
{
          "id":"7fe454bfe2fc4f70b2794b892739c78f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":146},
            "size":{
              "width":14,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"195e6adbd888493094e27712daec0a7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":146},
                "size":{
                  "width":14,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u114.png"}},
{
          "id":"a8bc6b8e62764ac3ab79fa2f8b336358",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":92,
              "y":100},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a921d037edae414d8a71ff14a369bd24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":92,
                  "y":100},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d70a59531cc047dca14976a9b01a3bc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2BC589,
              "opacity":1},
            "location":{
              "x":92,
              "y":140},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb5b461f501c47f19f5140c88fcf7e44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2BC589,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":140},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"914e85e4438242cabec93950836ae35d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":106},
            "size":{
              "width":13,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbe381c592af4772a55ebd29b93f56ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":106},
                "size":{
                  "width":13,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u120.png"}},
{
          "id":"36d5d7471e1f40708c9b588fe40d9bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":240,
              "y":93},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbc61c40959f43b8b635b5051a73e7b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":240,
                  "y":93},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"451f9ca8df9948efa13d9dbf1f592fee",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":345,
              "y":115},
            "size":{
              "width":94,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u18_line.png"}},
{
          "id":"af86ffbb14e94e78822042b945655ad5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF36B3C,
              "opacity":1},
            "location":{
              "x":357,
              "y":92},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8baa9c95ba8d4e30be0e7af93b446d53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C,
                  "opacity":1},
                "location":{
                  "x":357,
                  "y":92},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d2778bca4514d6dbcac8231d0a92947",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":169},
            "size":{
              "width":893,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a5f339177304cf9b6050c633924f0f2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":232,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1174b56e9d504dbcbd6a0a16b91c5ec3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "size":{
                      "width":232,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u28.png"}},
{
              "id":"182f7f74b50144e6a31a4f288fb11de8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":232,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9e0298e73f88400197854446f083b6fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":232,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u34.png"}},
{
              "id":"6050ce798e9b419d978a8a8b2a97d9d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":232,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ca79432da6b04df3a86d678c40944324",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":232,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u40.png"}},
{
              "id":"de48eecb53e3488ab0b458e645de4560",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":232,
                  "y":0},
                "size":{
                  "width":384,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f9d91c1cabc94444a5714cf03203da31",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":232,
                      "y":0},
                    "size":{
                      "width":384,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u30.png"}},
{
              "id":"19a817d4d883446697fe5cd09ea2ac8b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":232,
                  "y":30},
                "size":{
                  "width":384,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ec2df41f58804981a02ff9efac962ad4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":232,
                      "y":30},
                    "size":{
                      "width":384,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u36.png"}},
{
              "id":"78a5e232a2624e85a8ff34fa22cec22b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":232,
                  "y":60},
                "size":{
                  "width":384,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"96e45b40c11249c1bb98b51d6f058a75",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":232,
                      "y":60},
                    "size":{
                      "width":384,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u42.png"}},
{
              "id":"0f295ceda758417f80ca0ec04bc81a2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":616,
                  "y":0},
                "size":{
                  "width":277,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12fcd64dda4c4b5f9bf2e9ce5118d47d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":616,
                      "y":0},
                    "size":{
                      "width":277,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u32.png"}},
{
              "id":"6b050962b8074da99c79dd8004dfac7a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":616,
                  "y":30},
                "size":{
                  "width":277,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c96f2622929149209e3623082dc6fb6c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":616,
                      "y":30},
                    "size":{
                      "width":277,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u38.png"}},
{
              "id":"8c4c85b22c76475abf3d8f90506803f3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":616,
                  "y":60},
                "size":{
                  "width":277,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ce573aeb79ec47eb9ef8e0ab00ecf6ac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":616,
                      "y":60},
                    "size":{
                      "width":277,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u44.png"}}]},
{
          "id":"aa2b0edbf1354871ac802e08594219e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":998,
              "y":207},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"071155874f1d450d8756ea797b97b575",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":998,
                  "y":207},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"259f10c4d7934ebab450683c4b9fb692",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":999,
              "y":237},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d16bdaa15f9e471887fa8e9e48b8bdfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":999,
                  "y":237},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"663e10401ba94a48b30d46c1f6c12174",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1016},
            "size":{
              "width":1190,
              "height":665},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d385363b5014a06931e80f7444e3be3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1016},
                "size":{
                  "width":1190,
                  "height":665},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/角色管理/u50.png"}},
{
          "id":"762a497a0eec4a3dbdc9415368b0217a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":894},
            "size":{
              "width":1190,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fce7c91b44f34676a2c0d6bd9a7d49e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":894},
                "size":{
                  "width":1190,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u0.png"}},
{
          "id":"34bc1a8c01cb4ed9934933e8961a9762",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":895},
            "size":{
              "width":808,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fda6ff99225c4601a1255d30bd22284f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":895},
                "size":{
                  "width":808,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u104.png"}},
{
          "id":"e87e682abadb410ea9c72776f8f16980",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1044,
              "y":918},
            "size":{
              "width":66,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"691e912c15714fa6841159440b072f11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1044,
                  "y":918},
                "size":{
                  "width":66,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u106.png"}},
{
          "id":"0f68ad6508ac494ca6c15b8801c1b85c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3F4A59},
            "location":{
              "x":0,
              "y":972},
            "size":{
              "width":80,
              "height":708},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e2d4090c0ae46d59b0bd33622bc2293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59},
                "location":{
                  "x":0,
                  "y":972},
                "size":{
                  "width":80,
                  "height":708},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u108.png"}},
{
          "id":"e4d99337c51b4fa3b526972711f4d12b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-2,
              "y":972},
            "size":{
              "width":80,
              "height":511},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2635d2a589224f7c9263f6e82025617e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-2,
                  "y":972},
                "size":{
                  "width":80,
                  "height":511},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u110.png"}},
{
          "id":"ec13b4addd9e49ac97407a14a6bf1f82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":78,
              "y":974},
            "size":{
              "width":140,
              "height":706},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d3a958565414d45a32a003109e003f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":78,
                  "y":974},
                "size":{
                  "width":140,
                  "height":706},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u112.png"}},
{
          "id":"f6736a69cd8648578ea6469e5337a7bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":1040},
            "size":{
              "width":14,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e17fbf80a234203a9c172043cb68893",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":1040},
                "size":{
                  "width":14,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u114.png"}},
{
          "id":"e12c53dc977146c7b2af19e8598905a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":92,
              "y":994},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a81df45130314edabab1e273ada42346",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":92,
                  "y":994},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6eb39261855b4a308f8a46d6505f6cc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2BC589,
              "opacity":1},
            "location":{
              "x":92,
              "y":1034},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd1d29a354244005a076664617eb6377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2BC589,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":1034},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"880296ab2d574cd4a6186f7a10083492",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":1000},
            "size":{
              "width":13,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7de3124bc873457d845f53a053ea7c9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":1000},
                "size":{
                  "width":13,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u120.png"}},
{
          "id":"48eeeb0e9d1e464f96934e0b70e0fb88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":240,
              "y":987},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f38af95461364ea58115b78f0e521a62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":240,
                  "y":987},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e306d3c5af33419fbb0c7acd5f1bbd8f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":345,
              "y":1009},
            "size":{
              "width":94,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u18_line.png"}},
{
          "id":"401c4210829b43aaa335bf81ff852f88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF36B3C,
              "opacity":1},
            "location":{
              "x":357,
              "y":986},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27f3063f530447248934a0734b8177df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C,
                  "opacity":1},
                "location":{
                  "x":357,
                  "y":986},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4976449873e4975a4e5523faf41bfb2",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":1063},
            "size":{
              "width":893,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c055d9d49f004b68b355dc112c81d952",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":232,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc1555a2f396495bbc39843c821cfdb9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "size":{
                      "width":232,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u28.png"}},
{
              "id":"48375f4342a74a13b78d7b6cfd474f1b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":232,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"08957f552dd3485cbd7976850b958fd1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":232,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u34.png"}},
{
              "id":"e00a9f88d6984901972094a797f95789",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":232,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6213533366d54b9eb0b2db6d7ef8d07c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":232,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u40.png"}},
{
              "id":"680aefac9a944910833a80962eda58d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":232,
                  "y":0},
                "size":{
                  "width":384,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f81bea902e44443498d37f986939482c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":232,
                      "y":0},
                    "size":{
                      "width":384,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u30.png"}},
{
              "id":"d822c0ef5d934ac5a3e9b8d153c86831",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":232,
                  "y":30},
                "size":{
                  "width":384,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b09a9c3729b54446814d2e2fab065816",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":232,
                      "y":30},
                    "size":{
                      "width":384,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u36.png"}},
{
              "id":"41a49d5b23a24fc59eee78284731d228",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":232,
                  "y":60},
                "size":{
                  "width":384,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21949ce562eb4e4fbb7a8687b077bc22",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":232,
                      "y":60},
                    "size":{
                      "width":384,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u42.png"}},
{
              "id":"8718b887c0644028aa4433024cdfaf25",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":616,
                  "y":0},
                "size":{
                  "width":277,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e72dff12bfac45788b017269573b8331",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":616,
                      "y":0},
                    "size":{
                      "width":277,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u32.png"}},
{
              "id":"9e866029d34a4bedb33234f9580e0b82",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":616,
                  "y":30},
                "size":{
                  "width":277,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f762ddf344c646a0a815f896cf1a3c06",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":616,
                      "y":30},
                    "size":{
                      "width":277,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u38.png"}},
{
              "id":"1a054dd702e845efbe238d134b5c6c47",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":616,
                  "y":60},
                "size":{
                  "width":277,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b09bc2fe343b48d884e33d4b861a3de9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":616,
                      "y":60},
                    "size":{
                      "width":277,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u44.png"}}]},
{
          "id":"59e983198417441d915a5b9126a7d25d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":998,
              "y":1101},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f93c43623fd34499aab81b79bcdaf6d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":998,
                  "y":1101},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0da9995b0d2e4f3fa91cb7f21e94ce97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":999,
              "y":1131},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1d92ff1bdfe4a9ab3b4adb3a71ea4dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":999,
                  "y":1131},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc2370ce189b4d76965651b2f505825f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x66000000},
            "location":{
              "x":0,
              "y":894},
            "size":{
              "width":1190,
              "height":786}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57680b7ac28b4368aa5139d627007a78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x66000000},
                "location":{
                  "x":0,
                  "y":894},
                "size":{
                  "width":1190,
                  "height":786}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/角色管理/u100.png"}},
{
          "id":"5be467b10124467197d7b39123e3fe08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":398,
              "y":1054},
            "size":{
              "width":392,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1811e87e27164c3e835d8f13e489924f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":398,
                  "y":1054},
                "size":{
                  "width":392,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/角色管理/u102.png"}},
{
          "id":"291f5e5766164ddda672d8ae284b1c99",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":433,
              "y":1100},
            "size":{
              "width":327,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码/u111_line.png"}},
{
          "id":"2bb56f11ebfa4f33b13740edc6f8ec61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":547,
              "y":1070},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1515b997b27f4751842aa52ac3c7291e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":547,
                  "y":1070},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a3e55dc392a42de91cf25660b556ecb",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":741,
              "y":1072},
            "size":{
              "width":10,
              "height":19},
            "rotation":"40",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码/u114_line.png"}},
{
          "id":"25f65cf7754841608029bfb793d3b1ef",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":741,
              "y":1072},
            "size":{
              "width":10,
              "height":20},
            "rotation":"320",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/批量新增店员/u227_line.png"}},
{
          "id":"0d2c904a0be64917b56e2634217f0570",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":1142},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2783f4ea1ce64621952caefe9ef38d1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":1142},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8194ee05827400396c3f88e6c311379",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":1188},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4482b67f77cc419396099e6fa8d85318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":1188},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65c87c6baac949e783c8739054cbbeb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":1136},
            "size":{
              "width":199,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baf025a6c2744aee9f98884636c3eda8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":1136},
                "size":{
                  "width":199,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u124.png"}},
{
          "id":"30c92d44f4c64a81b968fa14a4f19832",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":1142},
            "size":{
              "width":14,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1e3312a9af1467abfe7677f205947b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":1142},
                "size":{
                  "width":14,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u132.png"}},
{
          "id":"51874fbf6dd44d3db6256c1605de216e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":432,
              "y":1190},
            "size":{
              "width":14,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66586666e19d4213be7a4bc65a9b9030",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":432,
                  "y":1190},
                "size":{
                  "width":14,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u132.png"}},
{
          "id":"6434cc02050b4360a72b0cce99e6ba82",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":1188},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d878be4c77e54a6182c2871fc8c8076e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":1188},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0646b1b3492b4cd2b1474040ea2ab1fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":466,
              "y":1240},
            "size":{
              "width":124,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebce447e10ca46d982a959b8dc2e0a07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":466,
                  "y":1240},
                "size":{
                  "width":124,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u233.png"}},
{
          "id":"53320c52087d48ec914c09a45cf82474",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":602,
              "y":1240},
            "size":{
              "width":124,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"624ad7899de04c8eaa3be58fab56b19f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":602,
                  "y":1240},
                "size":{
                  "width":124,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u233.png"}},
{
          "id":"a8b08083d54c4df090b07e048b836d1a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":116},
            "size":{
              "width":972,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u142_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "81541d40f815424597a83fdd2523e69b":{
      "scriptId":"u0"},
    "2bbf055874b84d0c8c14909b4bb77366":{
      "scriptId":"u1"},
    "3837f56c396e4625b27b97a1c6b14d03":{
      "scriptId":"u2"},
    "f9fe10dac4134064903a2af5a9369d04":{
      "scriptId":"u3"},
    "c12fbddcacda46858a7b62bfbec510f1":{
      "scriptId":"u4"},
    "7be59e31cddb4f8a9c390f403a6364ee":{
      "scriptId":"u5"},
    "b9ff4eb6f5954cf9b53a4383421f4b22":{
      "scriptId":"u6"},
    "8b213d2cf0d14536a1e93d609587a2c7":{
      "scriptId":"u7"},
    "78357e4e35d54edaa5ef73218c2cae92":{
      "scriptId":"u8"},
    "7816f8e28195475fb228cf6b110ed3b6":{
      "scriptId":"u9"},
    "8a53ff81b23e48b38bb9edb6587d3931":{
      "scriptId":"u10"},
    "01f3d6b7698547e6bedc2bd03fb36510":{
      "scriptId":"u11"},
    "42799df93e1a424d9f96e5ea08a71841":{
      "scriptId":"u12"},
    "d3e14ce18f0b4fea83821738d55d7eb1":{
      "scriptId":"u13"},
    "7fe454bfe2fc4f70b2794b892739c78f":{
      "scriptId":"u14"},
    "195e6adbd888493094e27712daec0a7d":{
      "scriptId":"u15"},
    "a8bc6b8e62764ac3ab79fa2f8b336358":{
      "scriptId":"u16"},
    "a921d037edae414d8a71ff14a369bd24":{
      "scriptId":"u17"},
    "d70a59531cc047dca14976a9b01a3bc8":{
      "scriptId":"u18"},
    "eb5b461f501c47f19f5140c88fcf7e44":{
      "scriptId":"u19"},
    "914e85e4438242cabec93950836ae35d":{
      "scriptId":"u20"},
    "dbe381c592af4772a55ebd29b93f56ae":{
      "scriptId":"u21"},
    "36d5d7471e1f40708c9b588fe40d9bd4":{
      "scriptId":"u22"},
    "bbc61c40959f43b8b635b5051a73e7b5":{
      "scriptId":"u23"},
    "451f9ca8df9948efa13d9dbf1f592fee":{
      "scriptId":"u24"},
    "af86ffbb14e94e78822042b945655ad5":{
      "scriptId":"u25"},
    "8baa9c95ba8d4e30be0e7af93b446d53":{
      "scriptId":"u26"},
    "1d2778bca4514d6dbcac8231d0a92947":{
      "scriptId":"u27"},
    "5a5f339177304cf9b6050c633924f0f2":{
      "scriptId":"u28"},
    "1174b56e9d504dbcbd6a0a16b91c5ec3":{
      "scriptId":"u29"},
    "de48eecb53e3488ab0b458e645de4560":{
      "scriptId":"u30"},
    "f9d91c1cabc94444a5714cf03203da31":{
      "scriptId":"u31"},
    "0f295ceda758417f80ca0ec04bc81a2a":{
      "scriptId":"u32"},
    "12fcd64dda4c4b5f9bf2e9ce5118d47d":{
      "scriptId":"u33"},
    "182f7f74b50144e6a31a4f288fb11de8":{
      "scriptId":"u34"},
    "9e0298e73f88400197854446f083b6fa":{
      "scriptId":"u35"},
    "19a817d4d883446697fe5cd09ea2ac8b":{
      "scriptId":"u36"},
    "ec2df41f58804981a02ff9efac962ad4":{
      "scriptId":"u37"},
    "6b050962b8074da99c79dd8004dfac7a":{
      "scriptId":"u38"},
    "c96f2622929149209e3623082dc6fb6c":{
      "scriptId":"u39"},
    "6050ce798e9b419d978a8a8b2a97d9d3":{
      "scriptId":"u40"},
    "ca79432da6b04df3a86d678c40944324":{
      "scriptId":"u41"},
    "78a5e232a2624e85a8ff34fa22cec22b":{
      "scriptId":"u42"},
    "96e45b40c11249c1bb98b51d6f058a75":{
      "scriptId":"u43"},
    "8c4c85b22c76475abf3d8f90506803f3":{
      "scriptId":"u44"},
    "ce573aeb79ec47eb9ef8e0ab00ecf6ac":{
      "scriptId":"u45"},
    "aa2b0edbf1354871ac802e08594219e0":{
      "scriptId":"u46"},
    "071155874f1d450d8756ea797b97b575":{
      "scriptId":"u47"},
    "259f10c4d7934ebab450683c4b9fb692":{
      "scriptId":"u48"},
    "d16bdaa15f9e471887fa8e9e48b8bdfe":{
      "scriptId":"u49"},
    "663e10401ba94a48b30d46c1f6c12174":{
      "scriptId":"u50"},
    "9d385363b5014a06931e80f7444e3be3":{
      "scriptId":"u51"},
    "762a497a0eec4a3dbdc9415368b0217a":{
      "scriptId":"u52"},
    "fce7c91b44f34676a2c0d6bd9a7d49e6":{
      "scriptId":"u53"},
    "34bc1a8c01cb4ed9934933e8961a9762":{
      "scriptId":"u54"},
    "fda6ff99225c4601a1255d30bd22284f":{
      "scriptId":"u55"},
    "e87e682abadb410ea9c72776f8f16980":{
      "scriptId":"u56"},
    "691e912c15714fa6841159440b072f11":{
      "scriptId":"u57"},
    "0f68ad6508ac494ca6c15b8801c1b85c":{
      "scriptId":"u58"},
    "8e2d4090c0ae46d59b0bd33622bc2293":{
      "scriptId":"u59"},
    "e4d99337c51b4fa3b526972711f4d12b":{
      "scriptId":"u60"},
    "2635d2a589224f7c9263f6e82025617e":{
      "scriptId":"u61"},
    "ec13b4addd9e49ac97407a14a6bf1f82":{
      "scriptId":"u62"},
    "5d3a958565414d45a32a003109e003f4":{
      "scriptId":"u63"},
    "f6736a69cd8648578ea6469e5337a7bd":{
      "scriptId":"u64"},
    "4e17fbf80a234203a9c172043cb68893":{
      "scriptId":"u65"},
    "e12c53dc977146c7b2af19e8598905a1":{
      "scriptId":"u66"},
    "a81df45130314edabab1e273ada42346":{
      "scriptId":"u67"},
    "6eb39261855b4a308f8a46d6505f6cc3":{
      "scriptId":"u68"},
    "dd1d29a354244005a076664617eb6377":{
      "scriptId":"u69"},
    "880296ab2d574cd4a6186f7a10083492":{
      "scriptId":"u70"},
    "7de3124bc873457d845f53a053ea7c9e":{
      "scriptId":"u71"},
    "48eeeb0e9d1e464f96934e0b70e0fb88":{
      "scriptId":"u72"},
    "f38af95461364ea58115b78f0e521a62":{
      "scriptId":"u73"},
    "e306d3c5af33419fbb0c7acd5f1bbd8f":{
      "scriptId":"u74"},
    "401c4210829b43aaa335bf81ff852f88":{
      "scriptId":"u75"},
    "27f3063f530447248934a0734b8177df":{
      "scriptId":"u76"},
    "f4976449873e4975a4e5523faf41bfb2":{
      "scriptId":"u77"},
    "c055d9d49f004b68b355dc112c81d952":{
      "scriptId":"u78"},
    "dc1555a2f396495bbc39843c821cfdb9":{
      "scriptId":"u79"},
    "680aefac9a944910833a80962eda58d9":{
      "scriptId":"u80"},
    "f81bea902e44443498d37f986939482c":{
      "scriptId":"u81"},
    "8718b887c0644028aa4433024cdfaf25":{
      "scriptId":"u82"},
    "e72dff12bfac45788b017269573b8331":{
      "scriptId":"u83"},
    "48375f4342a74a13b78d7b6cfd474f1b":{
      "scriptId":"u84"},
    "08957f552dd3485cbd7976850b958fd1":{
      "scriptId":"u85"},
    "d822c0ef5d934ac5a3e9b8d153c86831":{
      "scriptId":"u86"},
    "b09a9c3729b54446814d2e2fab065816":{
      "scriptId":"u87"},
    "9e866029d34a4bedb33234f9580e0b82":{
      "scriptId":"u88"},
    "f762ddf344c646a0a815f896cf1a3c06":{
      "scriptId":"u89"},
    "e00a9f88d6984901972094a797f95789":{
      "scriptId":"u90"},
    "6213533366d54b9eb0b2db6d7ef8d07c":{
      "scriptId":"u91"},
    "41a49d5b23a24fc59eee78284731d228":{
      "scriptId":"u92"},
    "21949ce562eb4e4fbb7a8687b077bc22":{
      "scriptId":"u93"},
    "1a054dd702e845efbe238d134b5c6c47":{
      "scriptId":"u94"},
    "b09bc2fe343b48d884e33d4b861a3de9":{
      "scriptId":"u95"},
    "59e983198417441d915a5b9126a7d25d":{
      "scriptId":"u96"},
    "f93c43623fd34499aab81b79bcdaf6d9":{
      "scriptId":"u97"},
    "0da9995b0d2e4f3fa91cb7f21e94ce97":{
      "scriptId":"u98"},
    "b1d92ff1bdfe4a9ab3b4adb3a71ea4dc":{
      "scriptId":"u99"},
    "bc2370ce189b4d76965651b2f505825f":{
      "scriptId":"u100"},
    "57680b7ac28b4368aa5139d627007a78":{
      "scriptId":"u101"},
    "5be467b10124467197d7b39123e3fe08":{
      "scriptId":"u102"},
    "1811e87e27164c3e835d8f13e489924f":{
      "scriptId":"u103"},
    "291f5e5766164ddda672d8ae284b1c99":{
      "scriptId":"u104"},
    "2bb56f11ebfa4f33b13740edc6f8ec61":{
      "scriptId":"u105"},
    "1515b997b27f4751842aa52ac3c7291e":{
      "scriptId":"u106"},
    "4a3e55dc392a42de91cf25660b556ecb":{
      "scriptId":"u107"},
    "25f65cf7754841608029bfb793d3b1ef":{
      "scriptId":"u108"},
    "0d2c904a0be64917b56e2634217f0570":{
      "scriptId":"u109"},
    "2783f4ea1ce64621952caefe9ef38d1a":{
      "scriptId":"u110"},
    "e8194ee05827400396c3f88e6c311379":{
      "scriptId":"u111"},
    "4482b67f77cc419396099e6fa8d85318":{
      "scriptId":"u112"},
    "65c87c6baac949e783c8739054cbbeb7":{
      "scriptId":"u113"},
    "baf025a6c2744aee9f98884636c3eda8":{
      "scriptId":"u114"},
    "30c92d44f4c64a81b968fa14a4f19832":{
      "scriptId":"u115"},
    "c1e3312a9af1467abfe7677f205947b6":{
      "scriptId":"u116"},
    "51874fbf6dd44d3db6256c1605de216e":{
      "scriptId":"u117"},
    "66586666e19d4213be7a4bc65a9b9030":{
      "scriptId":"u118"},
    "6434cc02050b4360a72b0cce99e6ba82":{
      "scriptId":"u119"},
    "d878be4c77e54a6182c2871fc8c8076e":{
      "scriptId":"u120"},
    "0646b1b3492b4cd2b1474040ea2ab1fb":{
      "scriptId":"u121"},
    "ebce447e10ca46d982a959b8dc2e0a07":{
      "scriptId":"u122"},
    "53320c52087d48ec914c09a45cf82474":{
      "scriptId":"u123"},
    "624ad7899de04c8eaa3be58fab56b19f":{
      "scriptId":"u124"},
    "a8b08083d54c4df090b07e048b836d1a":{
      "scriptId":"u125"}}});