$axure.loadCurrentPage({
  "url":"添加菜单-保存并发布.html",
  "generationDate":new Date(1449052584916.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"baf52071289347d99d94562c886d3d9f",
    "type":"Axure:Page",
    "name":"添加菜单-保存并发布",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"356c9b145f4b41a98c132322231a73d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":1014},
            "size":{
              "width":1190,
              "height":1093},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0ea206dafdd4adc82f383daca78daa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":1014},
                "size":{
                  "width":1190,
                  "height":1093},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-保存并发布/u0.png"}},
{
          "id":"89bd8f3219924ca1bd6b62b9d066a632",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":18,
              "y":20},
            "size":{
              "width":102,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"747de3f9f541456b9fff0b64da694500",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":20},
                "size":{
                  "width":102,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e54619bbf674fe8ad96eeffefbe0d23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":163,
              "y":42},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"474df0f283b84cb88f5f56df9acd9309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":163,
                  "y":42},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"785d95c287bd4b05b8ea394c546deb4e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":75},
            "size":{
              "width":1190,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商家信息/u26_line.png"}},
{
          "id":"2ff24d103ddf4fd2a4a12ea2d70c0129",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1121,
              "y":42},
            "size":{
              "width":40,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55c7ca2e483343499748937fecedbd30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1121,
                  "y":42},
                "size":{
                  "width":40,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4b9ddb5cbc04f1bb8d9d7750d61229b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1083,
              "y":34},
            "size":{
              "width":34,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3688efcb1b344b4fb77fe9ecc4792aad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1083,
                  "y":34},
                "size":{
                  "width":34,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑_保存商家信息/u65.png"}},
{
          "id":"a69fa3f6c1db404797a8d99f8d895891",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF1E2631},
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":165,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39b1ca5eba3948eb9a2c288208c8f840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1E2631},
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":165,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加一级菜单/u17.png"}},
{
          "id":"7903d67ebd0e481080bb3c9ed947d773",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":125,
              "y":124},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15fa5e0161764d79b95e6a5d1985fe38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":124},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"21ccebaa0f0844008628128533d527cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":125,
              "y":203},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e51243aed1045c58fdb94c580db5573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":203},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"fbe8d99caef0414699a5138f7ceacfb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":129,
              "y":290},
            "size":{
              "width":15,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"901d42b0d7304085bd2e62d2bbb15d8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":129,
                  "y":290},
                "size":{
                  "width":15,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三方接入_微信接口/u13.png"}},
{
          "id":"2a8183c94f98411fbdafbe445bb8ca3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":124},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef93af339f4243f493419642db301236",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":124},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c56a2ded49b46aeb2897d9208e49ab1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":202},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d8c7ae160da4d0684597402bf7da456",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":202},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccebbbde80db46928f552315cd7aadf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":285},
            "size":{
              "width":113,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f14abce5a6de44cd8747b5559f6467b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":285},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3901868ff6044fcba33ecdd756140142",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":357},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48b3dc08dd4c41d9a1cec7465ed6a8cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":357},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d7b7afa4c2b4dfd91a93baf9567b425",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":385},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5a310e274e54c308f00c04fc94de814",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":385},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0de50cf5acb94c1aa579f057994e18ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":413},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbe0671afc3f4246942071766dcd2de3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":413},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcac9c161c1c472aaebda39c7fa6a6c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":1190,
              "height":920},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7df824c5a5284c68a8ddbeafe2479e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":1190,
                  "height":920},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加一级菜单/u37.png"}},
{
          "id":"5c1094c42dc345a383ae695475c1c3c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":204,
              "y":202},
            "size":{
              "width":370,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"055f391b0bfd4c71958dd46a74ba6127",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":204,
                  "y":202},
                "size":{
                  "width":370,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b53d7aff2e95447b9aaf5f822f54f23d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFE0EAF6},
            "location":{
              "x":204,
              "y":111},
            "size":{
              "width":941,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0EAF6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9429bf6f3b294a42a92b0d6211ed8c7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6},
                "location":{
                  "x":204,
                  "y":111},
                "size":{
                  "width":941,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u33.png"}},
{
          "id":"1e6a8c04529046c5bf3683a38cd3d1a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":224,
              "y":115},
            "size":{
              "width":330,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a534096760b43739392a1c053217efa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":224,
                  "y":115},
                "size":{
                  "width":330,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加一级菜单/u6.png"}},
{
          "id":"476c60fa2bef4f118003d6a5f8d71478",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":204,
              "y":228},
            "size":{
              "width":941,
              "height":674}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c7fcd6a40314ba9b44dceaad94fcbb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":204,
                  "y":228},
                "size":{
                  "width":941,
                  "height":674}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u37.png"}},
{
          "id":"e7d8fe87fc41464f81384c4a0956699f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":844,
              "y":501},
            "size":{
              "width":250,
              "height":170},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6df601406f96421e86c313fd69452bc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":844,
                  "y":501},
                "size":{
                  "width":250,
                  "height":170},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u41.png"}},
{
          "id":"bd1c299f82b44c09ad9f5f56abcc9bc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":647,
              "y":591},
            "size":{
              "width":150,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a0d647810d94632812aeee24321ea7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":647,
                  "y":591},
                "size":{
                  "width":150,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u43.png"}},
{
          "id":"e6d9fcd7730745bfbe4ab7d9dac4dffa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":571,
              "y":433},
            "size":{
              "width":552,
              "height":268}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b175b96a635048ceb9ff14d9bcb77c06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":571,
                  "y":433},
                "size":{
                  "width":552,
                  "height":268}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_文字信息/u12.png"}},
{
          "id":"4ce01dd5d22b404f8c2b3a6529e9d8bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":811,
              "y":443},
            "size":{
              "width":300,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bb2dfeab179453984d60acf36cb8ae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":811,
                  "y":443},
                "size":{
                  "width":300,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u39.png"}},
{
          "id":"6383d1b27e5f4df69bec262512b13367",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":547,
              "y":234},
            "size":{
              "width":598,
              "height":593}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce51dcaa02454d439a83b3cfccfcce47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":547,
                  "y":234},
                "size":{
                  "width":598,
                  "height":593}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u74.png"}},
{
          "id":"ebfe9d287f2040b8894309a581f81791",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xBF000000},
            "size":{
              "width":1190,
              "height":920}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b489e228658d4a5db399c11ba4bf5fa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xBF000000},
                "size":{
                  "width":1190,
                  "height":920}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-保存并发布/u51.png"}},
{
          "id":"b7fb2dc163864806b311abe1989be20c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":206,
              "y":1218},
            "size":{
              "width":370,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ee1285a9fcb4615aa470f36e079f91c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":206,
                  "y":1218},
                "size":{
                  "width":370,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb8a6ec6db2e438486e375d222fe479a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFE0EAF6},
            "location":{
              "x":206,
              "y":1126},
            "size":{
              "width":941,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0EAF6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6881261941ba4908846706729cc406dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6},
                "location":{
                  "x":206,
                  "y":1126},
                "size":{
                  "width":941,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE0EAF6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u33.png"}},
{
          "id":"74362a1de9f8411ea533787af36ad1cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":206,
              "y":1125},
            "size":{
              "width":252,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0397d225559944d49f9b7ccfdc097040",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":206,
                  "y":1125},
                "size":{
                  "width":252,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-保存并发布/u57.png"}},
{
          "id":"1ad2da8e74bc4d23a9627ec746059c4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":437,
              "y":209},
            "size":{
              "width":485,
              "height":307}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c970f56f71844c59975b607c7cf9a17b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":437,
                  "y":209},
                "size":{
                  "width":485,
                  "height":307}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-保存并发布/u59.png"}},
{
          "id":"a6288bddcc5a4f74a55c28790ea6b053",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":263},
            "size":{
              "width":402,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单-保存并发布/u61_line.png"}},
{
          "id":"c357e367a4a74ec39a62959dd009f1c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":635,
              "y":227},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a25db1f7edea4c4e82d711fb136cfbf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":635,
                  "y":227},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ffbe280ff9a489b9367a6477687ad29",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":874,
              "y":230},
            "size":{
              "width":10,
              "height":23},
            "rotation":"40",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单-保存并发布/u64_line.png"}},
{
          "id":"25f771ca48964ef6820db07ed7ff9dfa",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":874,
              "y":229},
            "size":{
              "width":10,
              "height":25},
            "rotation":"320",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单-保存并发布/u65_line.png"}},
{
          "id":"75def8a769504c1d9d7f1338563aaff6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":695,
              "y":444},
            "size":{
              "width":152,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8b633d5afd542f28d820c1d3bf40761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":695,
                  "y":444},
                "size":{
                  "width":152,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-保存并发布/u66.png"}},
{
          "id":"c630b5a7e1474542b65d2cbf14b8c342",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":493,
              "y":307},
            "size":{
              "width":381,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef7aa3e5e95a465eb6c1019be7e43b58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":493,
                  "y":307},
                "size":{
                  "width":381,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9645f69e221e4b58b421dafd167c8a7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":521,
              "y":444},
            "size":{
              "width":152,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92cf28c186d240a9a5149ba0114b0d0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":521,
                  "y":444},
                "size":{
                  "width":152,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-保存并发布/u66.png"}},
{
          "id":"63c7b42d7d17476a9b338673eed7a0a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":18,
              "y":1034},
            "size":{
              "width":102,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ec258cce1e94c8facbab06d6feb7042",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":1034},
                "size":{
                  "width":102,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94ad00a7681b480a9b284c7f5c53b8ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":163,
              "y":1056},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd940fa3149a4fa7acef6ef0bc3d48f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":163,
                  "y":1056},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28068ddaf16f442891391044b2bfd117",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1089},
            "size":{
              "width":1190,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商家信息/u26_line.png"}},
{
          "id":"d57c7d9c837c471fbb77156c80256f47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1121,
              "y":1056},
            "size":{
              "width":40,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54e8cbfea9cf4b948812a67983de51aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1121,
                  "y":1056},
                "size":{
                  "width":40,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c13b7391307d4fb19da5e271046a4f9d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1083,
              "y":1048},
            "size":{
              "width":34,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c05d4d0fa23845379b1de910105fd9cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1083,
                  "y":1048},
                "size":{
                  "width":34,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑_保存商家信息/u65.png"}},
{
          "id":"f03727bc3a6d41b988064dd64ebb5269",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF1E2631},
            "location":{
              "x":0,
              "y":1094},
            "size":{
              "width":165,
              "height":1013},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d515617e6b3b4e988506e09abfbfac0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1E2631},
                "location":{
                  "x":0,
                  "y":1094},
                "size":{
                  "width":165,
                  "height":1013},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-保存并发布/u81.png"}},
{
          "id":"02bd8bbc37494efa8521f4f60f2a6047",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":125,
              "y":1138},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0c4493e1a1a4d8d8554e3a4e182e7a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":1138},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"9c7c0e42845c44ad9244079c8422a8bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":125,
              "y":1217},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b24ebb63cb241e98bc602ef14ced721",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":1217},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"0c5c9559819046518c06eed495cc0733",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":129,
              "y":1304},
            "size":{
              "width":15,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a470a0ab075747edaaac378dbcd38140",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":129,
                  "y":1304},
                "size":{
                  "width":15,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三方接入_微信接口/u13.png"}},
{
          "id":"3f388039d7154d2eaef59267d1bae1d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":1138},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d27a21bde1214299adb754d42c3253a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1138},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aef7e9147e7144079b4e7eca2ab9c519",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":1216},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74eaba4d763146e197e810dbbf324e96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1216},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"940caeb327f947e28d3679f9dd70b1a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":1299},
            "size":{
              "width":113,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0288dee93374d64afcca6ef7a15c55c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1299},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9953b0a062240f68537319eec76616f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":1371},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90567eddd9f9424f8c0b0d177941dae4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1371},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"518122ad08b64a8ebe6816e489b4c7cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":1399},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a37bd26906e44236ae4b046c22a92440",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1399},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47f7b85716224eca96fbb0c973dd2b9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":1427},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c12e8d7e1bc4712a86d03fc19be7006",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":1427},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d761922c824c4556bf6d63c337e12b6b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":206,
              "y":1248},
            "size":{
              "width":906,
              "height":649}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72d6ac03475e402b9d63cbee891598c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":206,
                  "y":1248},
                "size":{
                  "width":906,
                  "height":649}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u37.png"}},
{
          "id":"5e5a2864ab814ec4b5f0d75e341da288",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":793,
              "y":1452},
            "size":{
              "width":289,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca1ef28f02534426b5baba7764fcd0d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":793,
                  "y":1452},
                "size":{
                  "width":289,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-保存并发布/u103.png"}},
{
          "id":"849f74b1f58a4e3eaffae9441936ffba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":822,
              "y":1510},
            "size":{
              "width":241,
              "height":164},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51eb256fbf5344cd87c35cd7523ff978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":822,
                  "y":1510},
                "size":{
                  "width":241,
                  "height":164},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-保存并发布/u105.png"}},
{
          "id":"c5ef79d40ca54332892cd45ca00e796c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":633,
              "y":1596},
            "size":{
              "width":144,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3147d2c90caf444f9d700e451c0241b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":633,
                  "y":1596},
                "size":{
                  "width":144,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-保存并发布/u107.png"}},
{
          "id":"c2e9cf3212b547df8eeaf1757e22c18c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":206,
              "y":1248},
            "size":{
              "width":317,
              "height":649}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b9c651c23a4f5da802d06c808be1be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":206,
                  "y":1248},
                "size":{
                  "width":317,
                  "height":649}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u135.png"}},
{
          "id":"d21b6b46540745a5ac4ec48ed9eae97e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":520,
              "y":1405},
            "size":{
              "width":587,
              "height":685}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51d203f77f9146738e963f9d44f0127f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":520,
                  "y":1405},
                "size":{
                  "width":587,
                  "height":685}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u137.png"}},
{
          "id":"38ee3e7f465041bba7f8d2cfa28b9e33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":789,
              "y":1444},
            "size":{
              "width":289,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27efd616370c4fb2a267b1e28c79ea2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":789,
                  "y":1444},
                "size":{
                  "width":289,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-保存并发布/u103.png"}},
{
          "id":"d15ef74d164e4228b154e0b4b54d508f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":254,
              "y":1709},
            "size":{
              "width":91,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf5b45a8114e4a328acbaf8be424e8c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":254,
                  "y":1709},
                "size":{
                  "width":91,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u266.png"}},
{
          "id":"4a0f9b9153b7410f8a6c1daea7a399c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":235,
              "y":1502},
            "size":{
              "width":128,
              "height":76},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e45c5630e31645d1b830ee4403953c1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":235,
                  "y":1502},
                "size":{
                  "width":128,
                  "height":76},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u268.png"}},
{
          "id":"f5c2f22d4dec4d2a99ad18dbf45e302a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":532,
              "y":1245},
            "size":{
              "width":575,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7215b3d55e14635871a5f14a3371727",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":532,
                  "y":1245},
                "size":{
                  "width":575,
                  "height":192}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加子菜单/u84.png"}},
{
          "id":"59dc0c0405804053b9e8ca000db0d2dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":647,
              "y":1327},
            "size":{
              "width":106,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"581bf9afb69840b99b90f690c96d94d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":647,
                  "y":1327},
                "size":{
                  "width":106,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-保存并发布/u121.png"}},
{
          "id":"a5b4ee8674cc43069e2ea146c2cf3ae9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "location":{
              "x":654,
              "y":1331},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e969519bb1cc481eb45872a0f85dbc64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "location":{
                  "x":654,
                  "y":1331},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bfa1757adf4472380a41bf884986de4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":321.934020996094,
              "y":1108.09301757813},
            "size":{
              "width":110,
              "height":10},
            "rotation":"143",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/添加一级菜单/u135_end.png",
            "line~":"images/添加一级菜单/u135_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "356c9b145f4b41a98c132322231a73d9":{
      "scriptId":"u0"},
    "d0ea206dafdd4adc82f383daca78daa5":{
      "scriptId":"u1"},
    "89bd8f3219924ca1bd6b62b9d066a632":{
      "scriptId":"u2"},
    "747de3f9f541456b9fff0b64da694500":{
      "scriptId":"u3"},
    "4e54619bbf674fe8ad96eeffefbe0d23":{
      "scriptId":"u4"},
    "474df0f283b84cb88f5f56df9acd9309":{
      "scriptId":"u5"},
    "785d95c287bd4b05b8ea394c546deb4e":{
      "scriptId":"u6"},
    "2ff24d103ddf4fd2a4a12ea2d70c0129":{
      "scriptId":"u7"},
    "55c7ca2e483343499748937fecedbd30":{
      "scriptId":"u8"},
    "b4b9ddb5cbc04f1bb8d9d7750d61229b":{
      "scriptId":"u9"},
    "3688efcb1b344b4fb77fe9ecc4792aad":{
      "scriptId":"u10"},
    "a69fa3f6c1db404797a8d99f8d895891":{
      "scriptId":"u11"},
    "39b1ca5eba3948eb9a2c288208c8f840":{
      "scriptId":"u12"},
    "7903d67ebd0e481080bb3c9ed947d773":{
      "scriptId":"u13"},
    "15fa5e0161764d79b95e6a5d1985fe38":{
      "scriptId":"u14"},
    "21ccebaa0f0844008628128533d527cc":{
      "scriptId":"u15"},
    "5e51243aed1045c58fdb94c580db5573":{
      "scriptId":"u16"},
    "fbe8d99caef0414699a5138f7ceacfb1":{
      "scriptId":"u17"},
    "901d42b0d7304085bd2e62d2bbb15d8c":{
      "scriptId":"u18"},
    "2a8183c94f98411fbdafbe445bb8ca3e":{
      "scriptId":"u19"},
    "ef93af339f4243f493419642db301236":{
      "scriptId":"u20"},
    "1c56a2ded49b46aeb2897d9208e49ab1":{
      "scriptId":"u21"},
    "0d8c7ae160da4d0684597402bf7da456":{
      "scriptId":"u22"},
    "ccebbbde80db46928f552315cd7aadf9":{
      "scriptId":"u23"},
    "f14abce5a6de44cd8747b5559f6467b4":{
      "scriptId":"u24"},
    "3901868ff6044fcba33ecdd756140142":{
      "scriptId":"u25"},
    "48b3dc08dd4c41d9a1cec7465ed6a8cb":{
      "scriptId":"u26"},
    "6d7b7afa4c2b4dfd91a93baf9567b425":{
      "scriptId":"u27"},
    "c5a310e274e54c308f00c04fc94de814":{
      "scriptId":"u28"},
    "0de50cf5acb94c1aa579f057994e18ce":{
      "scriptId":"u29"},
    "bbe0671afc3f4246942071766dcd2de3":{
      "scriptId":"u30"},
    "fcac9c161c1c472aaebda39c7fa6a6c0":{
      "scriptId":"u31"},
    "7df824c5a5284c68a8ddbeafe2479e11":{
      "scriptId":"u32"},
    "5c1094c42dc345a383ae695475c1c3c5":{
      "scriptId":"u33"},
    "055f391b0bfd4c71958dd46a74ba6127":{
      "scriptId":"u34"},
    "b53d7aff2e95447b9aaf5f822f54f23d":{
      "scriptId":"u35"},
    "9429bf6f3b294a42a92b0d6211ed8c7e":{
      "scriptId":"u36"},
    "1e6a8c04529046c5bf3683a38cd3d1a1":{
      "scriptId":"u37"},
    "0a534096760b43739392a1c053217efa":{
      "scriptId":"u38"},
    "476c60fa2bef4f118003d6a5f8d71478":{
      "scriptId":"u39"},
    "2c7fcd6a40314ba9b44dceaad94fcbb7":{
      "scriptId":"u40"},
    "e7d8fe87fc41464f81384c4a0956699f":{
      "scriptId":"u41"},
    "6df601406f96421e86c313fd69452bc0":{
      "scriptId":"u42"},
    "bd1c299f82b44c09ad9f5f56abcc9bc7":{
      "scriptId":"u43"},
    "9a0d647810d94632812aeee24321ea7c":{
      "scriptId":"u44"},
    "e6d9fcd7730745bfbe4ab7d9dac4dffa":{
      "scriptId":"u45"},
    "b175b96a635048ceb9ff14d9bcb77c06":{
      "scriptId":"u46"},
    "4ce01dd5d22b404f8c2b3a6529e9d8bc":{
      "scriptId":"u47"},
    "7bb2dfeab179453984d60acf36cb8ae9":{
      "scriptId":"u48"},
    "6383d1b27e5f4df69bec262512b13367":{
      "scriptId":"u49"},
    "ce51dcaa02454d439a83b3cfccfcce47":{
      "scriptId":"u50"},
    "ebfe9d287f2040b8894309a581f81791":{
      "scriptId":"u51"},
    "b489e228658d4a5db399c11ba4bf5fa6":{
      "scriptId":"u52"},
    "b7fb2dc163864806b311abe1989be20c":{
      "scriptId":"u53"},
    "6ee1285a9fcb4615aa470f36e079f91c":{
      "scriptId":"u54"},
    "eb8a6ec6db2e438486e375d222fe479a":{
      "scriptId":"u55"},
    "6881261941ba4908846706729cc406dd":{
      "scriptId":"u56"},
    "74362a1de9f8411ea533787af36ad1cd":{
      "scriptId":"u57"},
    "0397d225559944d49f9b7ccfdc097040":{
      "scriptId":"u58"},
    "1ad2da8e74bc4d23a9627ec746059c4e":{
      "scriptId":"u59"},
    "c970f56f71844c59975b607c7cf9a17b":{
      "scriptId":"u60"},
    "a6288bddcc5a4f74a55c28790ea6b053":{
      "scriptId":"u61"},
    "c357e367a4a74ec39a62959dd009f1c1":{
      "scriptId":"u62"},
    "a25db1f7edea4c4e82d711fb136cfbf2":{
      "scriptId":"u63"},
    "6ffbe280ff9a489b9367a6477687ad29":{
      "scriptId":"u64"},
    "25f771ca48964ef6820db07ed7ff9dfa":{
      "scriptId":"u65"},
    "75def8a769504c1d9d7f1338563aaff6":{
      "scriptId":"u66"},
    "a8b633d5afd542f28d820c1d3bf40761":{
      "scriptId":"u67"},
    "c630b5a7e1474542b65d2cbf14b8c342":{
      "scriptId":"u68"},
    "ef7aa3e5e95a465eb6c1019be7e43b58":{
      "scriptId":"u69"},
    "9645f69e221e4b58b421dafd167c8a7d":{
      "scriptId":"u70"},
    "92cf28c186d240a9a5149ba0114b0d0d":{
      "scriptId":"u71"},
    "63c7b42d7d17476a9b338673eed7a0a1":{
      "scriptId":"u72"},
    "9ec258cce1e94c8facbab06d6feb7042":{
      "scriptId":"u73"},
    "94ad00a7681b480a9b284c7f5c53b8ea":{
      "scriptId":"u74"},
    "bd940fa3149a4fa7acef6ef0bc3d48f7":{
      "scriptId":"u75"},
    "28068ddaf16f442891391044b2bfd117":{
      "scriptId":"u76"},
    "d57c7d9c837c471fbb77156c80256f47":{
      "scriptId":"u77"},
    "54e8cbfea9cf4b948812a67983de51aa":{
      "scriptId":"u78"},
    "c13b7391307d4fb19da5e271046a4f9d":{
      "scriptId":"u79"},
    "c05d4d0fa23845379b1de910105fd9cc":{
      "scriptId":"u80"},
    "f03727bc3a6d41b988064dd64ebb5269":{
      "scriptId":"u81"},
    "d515617e6b3b4e988506e09abfbfac0f":{
      "scriptId":"u82"},
    "02bd8bbc37494efa8521f4f60f2a6047":{
      "scriptId":"u83"},
    "f0c4493e1a1a4d8d8554e3a4e182e7a2":{
      "scriptId":"u84"},
    "9c7c0e42845c44ad9244079c8422a8bb":{
      "scriptId":"u85"},
    "5b24ebb63cb241e98bc602ef14ced721":{
      "scriptId":"u86"},
    "0c5c9559819046518c06eed495cc0733":{
      "scriptId":"u87"},
    "a470a0ab075747edaaac378dbcd38140":{
      "scriptId":"u88"},
    "3f388039d7154d2eaef59267d1bae1d4":{
      "scriptId":"u89"},
    "d27a21bde1214299adb754d42c3253a0":{
      "scriptId":"u90"},
    "aef7e9147e7144079b4e7eca2ab9c519":{
      "scriptId":"u91"},
    "74eaba4d763146e197e810dbbf324e96":{
      "scriptId":"u92"},
    "940caeb327f947e28d3679f9dd70b1a8":{
      "scriptId":"u93"},
    "d0288dee93374d64afcca6ef7a15c55c":{
      "scriptId":"u94"},
    "b9953b0a062240f68537319eec76616f":{
      "scriptId":"u95"},
    "90567eddd9f9424f8c0b0d177941dae4":{
      "scriptId":"u96"},
    "518122ad08b64a8ebe6816e489b4c7cd":{
      "scriptId":"u97"},
    "a37bd26906e44236ae4b046c22a92440":{
      "scriptId":"u98"},
    "47f7b85716224eca96fbb0c973dd2b9a":{
      "scriptId":"u99"},
    "8c12e8d7e1bc4712a86d03fc19be7006":{
      "scriptId":"u100"},
    "d761922c824c4556bf6d63c337e12b6b":{
      "scriptId":"u101"},
    "72d6ac03475e402b9d63cbee891598c0":{
      "scriptId":"u102"},
    "5e5a2864ab814ec4b5f0d75e341da288":{
      "scriptId":"u103"},
    "ca1ef28f02534426b5baba7764fcd0d9":{
      "scriptId":"u104"},
    "849f74b1f58a4e3eaffae9441936ffba":{
      "scriptId":"u105"},
    "51eb256fbf5344cd87c35cd7523ff978":{
      "scriptId":"u106"},
    "c5ef79d40ca54332892cd45ca00e796c":{
      "scriptId":"u107"},
    "3147d2c90caf444f9d700e451c0241b9":{
      "scriptId":"u108"},
    "c2e9cf3212b547df8eeaf1757e22c18c":{
      "scriptId":"u109"},
    "20b9c651c23a4f5da802d06c808be1be":{
      "scriptId":"u110"},
    "d21b6b46540745a5ac4ec48ed9eae97e":{
      "scriptId":"u111"},
    "51d203f77f9146738e963f9d44f0127f":{
      "scriptId":"u112"},
    "38ee3e7f465041bba7f8d2cfa28b9e33":{
      "scriptId":"u113"},
    "27efd616370c4fb2a267b1e28c79ea2b":{
      "scriptId":"u114"},
    "d15ef74d164e4228b154e0b4b54d508f":{
      "scriptId":"u115"},
    "cf5b45a8114e4a328acbaf8be424e8c6":{
      "scriptId":"u116"},
    "4a0f9b9153b7410f8a6c1daea7a399c5":{
      "scriptId":"u117"},
    "e45c5630e31645d1b830ee4403953c1a":{
      "scriptId":"u118"},
    "f5c2f22d4dec4d2a99ad18dbf45e302a":{
      "scriptId":"u119"},
    "b7215b3d55e14635871a5f14a3371727":{
      "scriptId":"u120"},
    "59dc0c0405804053b9e8ca000db0d2dc":{
      "scriptId":"u121"},
    "581bf9afb69840b99b90f690c96d94d1":{
      "scriptId":"u122"},
    "a5b4ee8674cc43069e2ea146c2cf3ae9":{
      "scriptId":"u123"},
    "e969519bb1cc481eb45872a0f85dbc64":{
      "scriptId":"u124"},
    "5bfa1757adf4472380a41bf884986de4":{
      "scriptId":"u125"}}});