$axure.loadCurrentPage({
  "url":"新增店员.html",
  "generationDate":new Date(1448247501941.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"46efe93991b545e384c88bc39256064b",
    "type":"Axure:Page",
    "name":"新增店员",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bf63cb274f1640f3a823c2475b1bfc50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":128},
            "size":{
              "width":1196,
              "height":665},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02d588be77db431f8e6a947dec21b01d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":128},
                "size":{
                  "width":1196,
                  "height":665},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增店员/u0.png"}},
{
          "id":"2bdd3e4aabc242bd8856c4dce071ca8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF36B3C,
              "opacity":1},
            "location":{
              "x":236,
              "y":97},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4414f65689e4a4da28b2a68944baeb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C,
                  "opacity":1},
                "location":{
                  "x":236,
                  "y":97},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2546dedac24640bd844e0baccbcf0276",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":156},
            "size":{
              "width":107,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae56bc17f5e94e4e9dfe8d0b069c1527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":304,
                  "y":156},
                "size":{
                  "width":107,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u4.png"}},
{
          "id":"62ece9c774df414f8b1b76e51e4c97aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":161},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a014cd989c204c72a4e6fe7506bac3bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":161},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a7fa660be664e909ded04189d7a7bf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":162},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f37b0d4ad4b24d1294e401f9cf876a3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":162},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d14293e61c241aba1fd2021fd574bcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":163},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d16d311b58e14f67aa37a3ef26134075",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":163},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba4b55450b414fde9075cad195006f30",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":681,
              "y":156},
            "size":{
              "width":138,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"f84907efca684171a59391cae4c731db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":816,
              "y":228},
            "size":{
              "width":94,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9a25ca328114b2991a734be0917fb2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":816,
                  "y":228},
                "size":{
                  "width":94,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u13.png"}},
{
          "id":"20cb9657693d4535a612ceb727ddcb0c",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":285},
            "size":{
              "width":938,
              "height":104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"508017244eab458089fc3efd4f05691c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":105,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"be63708d4c9e4a5693938e3695497a8f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "size":{
                      "width":105,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u16.png"}},
{
              "id":"a8c5c70259ea49239d579308b4256fe4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":105,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0eb54d1e5f1844daba93509aa192a30c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":105,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u28.png"}},
{
              "id":"06503bc85d2d44239512259a09994903",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":105,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3639b489c9544eaa90cf6ab9ac9d3588",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":105,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u40.png"}},
{
              "id":"85461e21e03b468491449e199382d2a0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":540,
                  "y":0},
                "size":{
                  "width":104,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"db099913b9a74106a83db58c31aa2828",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":540,
                      "y":0},
                    "size":{
                      "width":104,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u24.png"}},
{
              "id":"a97f17f313b447559f0a1eced6dc659a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":540,
                  "y":30},
                "size":{
                  "width":104,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c122b240c4dc4ab293d6a2fe30285aa6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":540,
                      "y":30},
                    "size":{
                      "width":104,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u36.png"}},
{
              "id":"0de42b64e70148f084a3523e98c70963",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":540,
                  "y":66},
                "size":{
                  "width":104,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cbcf70713e1646e89cf38326bf4ce35d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":540,
                      "y":66},
                    "size":{
                      "width":104,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u48.png"}},
{
              "id":"30ed2c436aa348c488bde90a77a4af31",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":644,
                  "y":0},
                "size":{
                  "width":294,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"172715cb861947a79b85dc0dd48e03ed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":644,
                      "y":0},
                    "size":{
                      "width":294,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u26.png"}},
{
              "id":"259487a166284a85bf6af6809ef2a562",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":644,
                  "y":30},
                "size":{
                  "width":294,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0ea8d6a47cd34a989dc8043dd1a1f40d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":644,
                      "y":30},
                    "size":{
                      "width":294,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u38.png"}},
{
              "id":"e645c68599584096a512606666c87441",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":644,
                  "y":66},
                "size":{
                  "width":294,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"67f39624e95d436a9a823a9fbfa4650d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":644,
                      "y":66},
                    "size":{
                      "width":294,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u50.png"}},
{
              "id":"f62ca84061c246ee8179d3ca9b26a5c7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":105,
                  "y":0},
                "size":{
                  "width":123,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c7a1c99262a64b7db66e10409a7366c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":105,
                      "y":0},
                    "size":{
                      "width":123,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u18.png"}},
{
              "id":"16ea3b4a31994cd09ce1707173ef0311",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":105,
                  "y":30},
                "size":{
                  "width":123,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75adec7c8ce44d5599d8123e1af9617e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":105,
                      "y":30},
                    "size":{
                      "width":123,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u30.png"}},
{
              "id":"39d8ae84841f41c492a6a1083ef2eb56",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":105,
                  "y":66},
                "size":{
                  "width":123,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12bad6ca96c648d5b51b577cfba9a4f9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":105,
                      "y":66},
                    "size":{
                      "width":123,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u42.png"}},
{
              "id":"ec8f6aea4a634483a214b02a60e568a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":228,
                  "y":0},
                "size":{
                  "width":213,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f51b23d264cf40029b573645461f5478",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":228,
                      "y":0},
                    "size":{
                      "width":213,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u20.png"}},
{
              "id":"28b6c37dc6de4d12935f6a90da51ebf0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":228,
                  "y":30},
                "size":{
                  "width":213,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4923200773934b3e8da70411ceb0d19b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":228,
                      "y":30},
                    "size":{
                      "width":213,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u32.png"}},
{
              "id":"d8f66e0ea33d4863a1399dcde8eddb00",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":228,
                  "y":66},
                "size":{
                  "width":213,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"538ce88fdbd9490495b406a0819cf011",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":228,
                      "y":66},
                    "size":{
                      "width":213,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u44.png"}},
{
              "id":"da76cc04845d4b0684c7a301e1919657",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":441,
                  "y":0},
                "size":{
                  "width":99,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f4d7e9a188346b7bd3ea5163557b9cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":441,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u22.png"}},
{
              "id":"4196263cf13c442db591cf977b3f0470",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":441,
                  "y":30},
                "size":{
                  "width":99,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa2b414387ed4ed0b80b3143a3fa634e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":441,
                      "y":30},
                    "size":{
                      "width":99,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u34.png"}},
{
              "id":"e0c3a4c4ac534fadb6e4d544fe1c852c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":441,
                  "y":66},
                "size":{
                  "width":99,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"562b7491c26d4141bbb274404b42c1c0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":441,
                      "y":66},
                    "size":{
                      "width":99,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u46.png"}}]},
{
          "id":"e7100e14a2654b06b14ee8c47bf34989",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":963,
              "y":328},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9611cd0442604ac591a46506adbe4bd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":963,
                  "y":328},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25b816420d7a46b98192e2c8bf0acbce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":999,
              "y":328},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e757d7a521048f68e87f3fabf9baa28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":999,
                  "y":328},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3490e4946a3145dc98972761bb2ecb35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":628,
              "y":422},
            "size":{
              "width":392,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2507eff6a1584cb9a0c98b90510688fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":628,
                  "y":422},
                "size":{
                  "width":392,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u56.png"}},
{
          "id":"936913dbbe6a47d19fd0d8e39180bbd6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1035,
              "y":423},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f2c82cceceb476c845094b4a54cb62e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1035,
                  "y":423},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u58.png"}},
{
          "id":"a49e6b35fb624c61bd9ecf5c0fefa7ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":517,
              "y":434},
            "size":{
              "width":101,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9113381a88cb4b3caaacdd8beb9fd5bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":517,
                  "y":434},
                "size":{
                  "width":101,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c21f5c4d5774c49aa1531e8920c633b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1068,
              "y":228},
            "size":{
              "width":94,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1afaaeaac1924c91b0d1d38357f83ce7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1068,
                  "y":228},
                "size":{
                  "width":94,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u13.png"}},
{
          "id":"b81f90ddf09b4ab289c24d1ed09d02b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":1043,
              "y":328},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e6b94b5a6e54a03812ce14e3b9f61a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":1043,
                  "y":328},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76c80f65de714f39b4c1ac528fde8788",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":1081,
              "y":328},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb24ebb3e9124612b23aab5866191ab6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":1081,
                  "y":328},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f50de1a036dd401d922d7a84dabb15b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":157},
            "size":{
              "width":103,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ced334d5759348f4bb05d50e89a85ccc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":157},
                "size":{
                  "width":103,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u68.png"}},
{
          "id":"56548baa631a4c229b4457c6bfd70dd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":843,
              "y":162},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c771dfa6aeb74068b34faf44bbc83a1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":843,
                  "y":162},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"646cbcce05fa40d2b68b1e82f37015d6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":884,
              "y":156},
            "size":{
              "width":105,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"29983001e5434d5392a4fe0fe3bb9e62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1017,
              "y":164},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d119c7b442c4455d8f17e24d53e6cc95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1017,
                  "y":164},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a37c08bb94f0418bb30f6a59bd00611b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1057,
              "y":156},
            "size":{
              "width":105,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"ef7c59fe09cb436ca18086a8a203a747",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":944,
              "y":228},
            "size":{
              "width":94,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3715219dc1034c3e8b1cebba2c7e0b2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":944,
                  "y":228},
                "size":{
                  "width":94,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u13.png"}},
{
          "id":"026513febc6a4fd49c6ddf27938a3f41",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":121},
            "size":{
              "width":94,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u18_line.png"}},
{
          "id":"cd552834b4044ccc84e23dcc10885a4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":353,
              "y":98},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a68aa36d620f40c782e5fe354d520f8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":353,
                  "y":98},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd1b105cd385499e8c99a8292f34b4ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF36B3C},
            "location":{
              "x":1191,
              "y":128},
            "size":{
              "width":5,
              "height":665},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c7d91451a845fb8e3b5a7a303262bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C},
                "location":{
                  "x":1191,
                  "y":128},
                "size":{
                  "width":5,
                  "height":665},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移动门店/u52.png"}},
{
          "id":"ee4223ca69c043e2957a69a3d80253ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF36B3C},
            "location":{
              "x":1126,
              "y":163},
            "size":{
              "width":100,
              "height":30},
            "rotation":"90",
            "textRotation":"90",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59a6089bc17a4035a65126525b6a6761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C},
                "location":{
                  "x":1126,
                  "y":163},
                "size":{
                  "width":100,
                  "height":30},
                "rotation":"90",
                "textRotation":"90",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移动门店/u54.png"}},
{
          "id":"859759ed0a844e7298864b128fd6b5e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1170,
              "y":164},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfb34c2d15b2491da0c20be503f43959",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1170,
                  "y":164},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8b3fd2340b745b2a3d7508dd7a905a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":6},
            "size":{
              "width":1190,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f72617598de747eb977441b39256a55b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":6},
                "size":{
                  "width":1190,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u0.png"}},
{
          "id":"9b56c85c08de407fb5462bdcf8389422",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":0},
            "size":{
              "width":808,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b8e816df6db410e87316c97333bbb76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":0},
                "size":{
                  "width":808,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u104.png"}},
{
          "id":"6d21a31bc0f44eda974f1404c6d61f0a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1045,
              "y":31},
            "size":{
              "width":66,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f6577ca05ab4accb5e132f995869ff0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1045,
                  "y":31},
                "size":{
                  "width":66,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u106.png"}},
{
          "id":"c620cca920aa45fb971124d7ea72a1bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3F4A59},
            "location":{
              "x":1,
              "y":85},
            "size":{
              "width":80,
              "height":708},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31d3b8f259f84f8a83a32959a70f7030",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59},
                "location":{
                  "x":1,
                  "y":85},
                "size":{
                  "width":80,
                  "height":708},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u108.png"}},
{
          "id":"1fdee45fd5df4103ba81c3a3a6cb8085",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":84},
            "size":{
              "width":80,
              "height":511},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96ed09f4fee14e07942d82de7475e9fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":84},
                "size":{
                  "width":80,
                  "height":511},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u110.png"}},
{
          "id":"114471cc8b58426785b7bdeec188ad3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":80,
              "y":86},
            "size":{
              "width":140,
              "height":706},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fadbef3171e49c8a7f4ac9f03105ed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":80,
                  "y":86},
                "size":{
                  "width":140,
                  "height":706},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u112.png"}},
{
          "id":"3f3f5c9a77c247e28bbb29044472e581",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":189,
              "y":153},
            "size":{
              "width":14,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c464d7150a941e8a67ba29055e54934",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":189,
                  "y":153},
                "size":{
                  "width":14,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u114.png"}},
{
          "id":"291f5afcdb814e8fbbdf980ae5db0a2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":94,
              "y":106},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b85cfff3a28746e896303da314e5dc6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":94,
                  "y":106},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84325179f1db49dfbf17d22f6fb3ea80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2BC589,
              "opacity":1},
            "location":{
              "x":94,
              "y":147},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0188e3b5eff44f1b93a421fc1e04229e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2BC589,
                  "opacity":1},
                "location":{
                  "x":94,
                  "y":147},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ced014e585c143d4b6412245e2f7f0ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":189,
              "y":112},
            "size":{
              "width":13,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a238791b92bb4030b824f617f51808e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":189,
                  "y":112},
                "size":{
                  "width":13,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u120.png"}},
{
          "id":"8832440f02844ab9b5ba407123f69c79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x66000000},
            "size":{
              "width":1196,
              "height":793}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aca523b56da43bc90e1a0db33c4dbde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x66000000},
                "size":{
                  "width":1196,
                  "height":793}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增店员/u107.png"}},
{
          "id":"624845ba438b433685cd8115a60cd62d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":298,
              "y":86},
            "size":{
              "width":760,
              "height":326}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"109682c5a29f4adc8332002d85da8bbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":298,
                  "y":86},
                "size":{
                  "width":760,
                  "height":326}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增店员/u109.png"}},
{
          "id":"90f0dae2f6f8410ba41fd526c7fb6d84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":364,
              "y":176},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e9256ec0ee248048bda64482ac64f85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":364,
                  "y":176},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8628856e5b1f498da3e027807c4c6b26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":168},
            "size":{
              "width":201,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ece3260528c348b0b9bf7e5aefea8f30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":168},
                "size":{
                  "width":201,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增店员/u113.png"}},
{
          "id":"cf91d1f7264444e0a66c26cde1776879",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":728,
              "y":176},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb184d72e16646b18b25bb095db1a329",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":728,
                  "y":176},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d397dd144363478583e0eb42d8218961",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":236},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9721e8d5fbf4442d95bedb867616acc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":236},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c05754c6cbf41bf93c2bf59d2b78469",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":427,
              "y":232},
            "size":{
              "width":201,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"4c36ff5b70854870869f2e15a7889d07",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":150},
            "size":{
              "width":678,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增店员/u120_line.png"}},
{
          "id":"9aaa8b4864c24255b1a041f68f071046",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":648,
              "y":108},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"470086e14eb94f48ab59efd5235c505a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":648,
                  "y":108},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89e4bacecda74146b7db6205ad57b0c6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1014,
              "y":102},
            "size":{
              "width":10,
              "height":29},
            "rotation":"40",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增_编辑门店/u221_line.png"}},
{
          "id":"d8984b2d2b034a85a2249828ca4cd0e3",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1014,
              "y":102},
            "size":{
              "width":10,
              "height":29},
            "rotation":"320",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增_编辑门店/u221_line.png"}},
{
          "id":"71c4f82da61a4035a31db67fc9f14648",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":792,
              "y":170},
            "size":{
              "width":201,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ba3c20056c24430943ed82342da52d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":792,
                  "y":170},
                "size":{
                  "width":201,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增店员/u113.png"}},
{
          "id":"753996ff0fbf4ae0b6d4abb29a0f0513",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":727,
              "y":237},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc4ebfcb84cb49f3a41ee2c6ef2b1e01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":727,
                  "y":237},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac9d478a88c4445c966c73b163ed1aa6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":792,
              "y":230},
            "size":{
              "width":201,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"b69c8582d6764de2bb1ed32074dab992",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":292},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d0339ed4e204832aa0b541122886950",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":292},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"718031d55c1d4d8a8155c49a3920d921",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":426,
              "y":292},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b929c9c3d82d4c4b8b8ee389bb14e1fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":292},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"32a4a5884fba41748f4406fbd7084145",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":176},
            "size":{
              "width":14,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ae2dc2281a04deca16901fe76ae811d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":343,
                  "y":176},
                "size":{
                  "width":14,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u132.png"}},
{
          "id":"153187e507d441e4b84cb0957583750e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":238},
            "size":{
              "width":14,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adc81fe1e71b4221b67bac385d08be4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":342,
                  "y":238},
                "size":{
                  "width":14,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u132.png"}},
{
          "id":"5ddb78535e744bdda5397d9678c12a23",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":704,
              "y":176},
            "size":{
              "width":14,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bda117b271e408d96471103bf418cd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":704,
                  "y":176},
                "size":{
                  "width":14,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u132.png"}},
{
          "id":"ff703a7c0785491c8de8a6543354beee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":703,
              "y":238},
            "size":{
              "width":14,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f398bf74fc5146e1bf2f6f4aa24afb8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":703,
                  "y":238},
                "size":{
                  "width":14,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u132.png"}},
{
          "id":"b4d33b39bef8454d95009b2cb8d3dd7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":552,
              "y":341},
            "size":{
              "width":119,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d84b98da3a841c3b5ce127798151270",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":552,
                  "y":341},
                "size":{
                  "width":119,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u128.png"}},
{
          "id":"836d10d3b83b41adaeb124da1081757a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":722,
              "y":341},
            "size":{
              "width":119,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"717ab758462f441699669a74cc60840f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":722,
                  "y":341},
                "size":{
                  "width":119,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u128.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bf63cb274f1640f3a823c2475b1bfc50":{
      "scriptId":"u0"},
    "02d588be77db431f8e6a947dec21b01d":{
      "scriptId":"u1"},
    "2bdd3e4aabc242bd8856c4dce071ca8f":{
      "scriptId":"u2"},
    "b4414f65689e4a4da28b2a68944baeb0":{
      "scriptId":"u3"},
    "2546dedac24640bd844e0baccbcf0276":{
      "scriptId":"u4"},
    "ae56bc17f5e94e4e9dfe8d0b069c1527":{
      "scriptId":"u5"},
    "62ece9c774df414f8b1b76e51e4c97aa":{
      "scriptId":"u6"},
    "a014cd989c204c72a4e6fe7506bac3bf":{
      "scriptId":"u7"},
    "3a7fa660be664e909ded04189d7a7bf8":{
      "scriptId":"u8"},
    "f37b0d4ad4b24d1294e401f9cf876a3a":{
      "scriptId":"u9"},
    "7d14293e61c241aba1fd2021fd574bcc":{
      "scriptId":"u10"},
    "d16d311b58e14f67aa37a3ef26134075":{
      "scriptId":"u11"},
    "ba4b55450b414fde9075cad195006f30":{
      "scriptId":"u12"},
    "f84907efca684171a59391cae4c731db":{
      "scriptId":"u13"},
    "d9a25ca328114b2991a734be0917fb2b":{
      "scriptId":"u14"},
    "20cb9657693d4535a612ceb727ddcb0c":{
      "scriptId":"u15"},
    "508017244eab458089fc3efd4f05691c":{
      "scriptId":"u16"},
    "be63708d4c9e4a5693938e3695497a8f":{
      "scriptId":"u17"},
    "f62ca84061c246ee8179d3ca9b26a5c7":{
      "scriptId":"u18"},
    "c7a1c99262a64b7db66e10409a7366c1":{
      "scriptId":"u19"},
    "ec8f6aea4a634483a214b02a60e568a2":{
      "scriptId":"u20"},
    "f51b23d264cf40029b573645461f5478":{
      "scriptId":"u21"},
    "da76cc04845d4b0684c7a301e1919657":{
      "scriptId":"u22"},
    "2f4d7e9a188346b7bd3ea5163557b9cb":{
      "scriptId":"u23"},
    "85461e21e03b468491449e199382d2a0":{
      "scriptId":"u24"},
    "db099913b9a74106a83db58c31aa2828":{
      "scriptId":"u25"},
    "30ed2c436aa348c488bde90a77a4af31":{
      "scriptId":"u26"},
    "172715cb861947a79b85dc0dd48e03ed":{
      "scriptId":"u27"},
    "a8c5c70259ea49239d579308b4256fe4":{
      "scriptId":"u28"},
    "0eb54d1e5f1844daba93509aa192a30c":{
      "scriptId":"u29"},
    "16ea3b4a31994cd09ce1707173ef0311":{
      "scriptId":"u30"},
    "75adec7c8ce44d5599d8123e1af9617e":{
      "scriptId":"u31"},
    "28b6c37dc6de4d12935f6a90da51ebf0":{
      "scriptId":"u32"},
    "4923200773934b3e8da70411ceb0d19b":{
      "scriptId":"u33"},
    "4196263cf13c442db591cf977b3f0470":{
      "scriptId":"u34"},
    "aa2b414387ed4ed0b80b3143a3fa634e":{
      "scriptId":"u35"},
    "a97f17f313b447559f0a1eced6dc659a":{
      "scriptId":"u36"},
    "c122b240c4dc4ab293d6a2fe30285aa6":{
      "scriptId":"u37"},
    "259487a166284a85bf6af6809ef2a562":{
      "scriptId":"u38"},
    "0ea8d6a47cd34a989dc8043dd1a1f40d":{
      "scriptId":"u39"},
    "06503bc85d2d44239512259a09994903":{
      "scriptId":"u40"},
    "3639b489c9544eaa90cf6ab9ac9d3588":{
      "scriptId":"u41"},
    "39d8ae84841f41c492a6a1083ef2eb56":{
      "scriptId":"u42"},
    "12bad6ca96c648d5b51b577cfba9a4f9":{
      "scriptId":"u43"},
    "d8f66e0ea33d4863a1399dcde8eddb00":{
      "scriptId":"u44"},
    "538ce88fdbd9490495b406a0819cf011":{
      "scriptId":"u45"},
    "e0c3a4c4ac534fadb6e4d544fe1c852c":{
      "scriptId":"u46"},
    "562b7491c26d4141bbb274404b42c1c0":{
      "scriptId":"u47"},
    "0de42b64e70148f084a3523e98c70963":{
      "scriptId":"u48"},
    "cbcf70713e1646e89cf38326bf4ce35d":{
      "scriptId":"u49"},
    "e645c68599584096a512606666c87441":{
      "scriptId":"u50"},
    "67f39624e95d436a9a823a9fbfa4650d":{
      "scriptId":"u51"},
    "e7100e14a2654b06b14ee8c47bf34989":{
      "scriptId":"u52"},
    "9611cd0442604ac591a46506adbe4bd6":{
      "scriptId":"u53"},
    "25b816420d7a46b98192e2c8bf0acbce":{
      "scriptId":"u54"},
    "4e757d7a521048f68e87f3fabf9baa28":{
      "scriptId":"u55"},
    "3490e4946a3145dc98972761bb2ecb35":{
      "scriptId":"u56"},
    "2507eff6a1584cb9a0c98b90510688fc":{
      "scriptId":"u57"},
    "936913dbbe6a47d19fd0d8e39180bbd6":{
      "scriptId":"u58"},
    "0f2c82cceceb476c845094b4a54cb62e":{
      "scriptId":"u59"},
    "a49e6b35fb624c61bd9ecf5c0fefa7ca":{
      "scriptId":"u60"},
    "9113381a88cb4b3caaacdd8beb9fd5bf":{
      "scriptId":"u61"},
    "1c21f5c4d5774c49aa1531e8920c633b":{
      "scriptId":"u62"},
    "1afaaeaac1924c91b0d1d38357f83ce7":{
      "scriptId":"u63"},
    "b81f90ddf09b4ab289c24d1ed09d02b0":{
      "scriptId":"u64"},
    "0e6b94b5a6e54a03812ce14e3b9f61a4":{
      "scriptId":"u65"},
    "76c80f65de714f39b4c1ac528fde8788":{
      "scriptId":"u66"},
    "fb24ebb3e9124612b23aab5866191ab6":{
      "scriptId":"u67"},
    "f50de1a036dd401d922d7a84dabb15b9":{
      "scriptId":"u68"},
    "ced334d5759348f4bb05d50e89a85ccc":{
      "scriptId":"u69"},
    "56548baa631a4c229b4457c6bfd70dd2":{
      "scriptId":"u70"},
    "c771dfa6aeb74068b34faf44bbc83a1a":{
      "scriptId":"u71"},
    "646cbcce05fa40d2b68b1e82f37015d6":{
      "scriptId":"u72"},
    "29983001e5434d5392a4fe0fe3bb9e62":{
      "scriptId":"u73"},
    "d119c7b442c4455d8f17e24d53e6cc95":{
      "scriptId":"u74"},
    "a37c08bb94f0418bb30f6a59bd00611b":{
      "scriptId":"u75"},
    "ef7c59fe09cb436ca18086a8a203a747":{
      "scriptId":"u76"},
    "3715219dc1034c3e8b1cebba2c7e0b2d":{
      "scriptId":"u77"},
    "026513febc6a4fd49c6ddf27938a3f41":{
      "scriptId":"u78"},
    "cd552834b4044ccc84e23dcc10885a4c":{
      "scriptId":"u79"},
    "a68aa36d620f40c782e5fe354d520f8f":{
      "scriptId":"u80"},
    "dd1b105cd385499e8c99a8292f34b4ac":{
      "scriptId":"u81"},
    "54c7d91451a845fb8e3b5a7a303262bd":{
      "scriptId":"u82"},
    "ee4223ca69c043e2957a69a3d80253ba":{
      "scriptId":"u83"},
    "59a6089bc17a4035a65126525b6a6761":{
      "scriptId":"u84"},
    "859759ed0a844e7298864b128fd6b5e0":{
      "scriptId":"u85"},
    "cfb34c2d15b2491da0c20be503f43959":{
      "scriptId":"u86"},
    "f8b3fd2340b745b2a3d7508dd7a905a1":{
      "scriptId":"u87"},
    "f72617598de747eb977441b39256a55b":{
      "scriptId":"u88"},
    "9b56c85c08de407fb5462bdcf8389422":{
      "scriptId":"u89"},
    "6b8e816df6db410e87316c97333bbb76":{
      "scriptId":"u90"},
    "6d21a31bc0f44eda974f1404c6d61f0a":{
      "scriptId":"u91"},
    "1f6577ca05ab4accb5e132f995869ff0":{
      "scriptId":"u92"},
    "c620cca920aa45fb971124d7ea72a1bd":{
      "scriptId":"u93"},
    "31d3b8f259f84f8a83a32959a70f7030":{
      "scriptId":"u94"},
    "1fdee45fd5df4103ba81c3a3a6cb8085":{
      "scriptId":"u95"},
    "96ed09f4fee14e07942d82de7475e9fc":{
      "scriptId":"u96"},
    "114471cc8b58426785b7bdeec188ad3c":{
      "scriptId":"u97"},
    "6fadbef3171e49c8a7f4ac9f03105ed0":{
      "scriptId":"u98"},
    "3f3f5c9a77c247e28bbb29044472e581":{
      "scriptId":"u99"},
    "3c464d7150a941e8a67ba29055e54934":{
      "scriptId":"u100"},
    "291f5afcdb814e8fbbdf980ae5db0a2c":{
      "scriptId":"u101"},
    "b85cfff3a28746e896303da314e5dc6d":{
      "scriptId":"u102"},
    "84325179f1db49dfbf17d22f6fb3ea80":{
      "scriptId":"u103"},
    "0188e3b5eff44f1b93a421fc1e04229e":{
      "scriptId":"u104"},
    "ced014e585c143d4b6412245e2f7f0ee":{
      "scriptId":"u105"},
    "a238791b92bb4030b824f617f51808e3":{
      "scriptId":"u106"},
    "8832440f02844ab9b5ba407123f69c79":{
      "scriptId":"u107"},
    "6aca523b56da43bc90e1a0db33c4dbde":{
      "scriptId":"u108"},
    "624845ba438b433685cd8115a60cd62d":{
      "scriptId":"u109"},
    "109682c5a29f4adc8332002d85da8bbe":{
      "scriptId":"u110"},
    "90f0dae2f6f8410ba41fd526c7fb6d84":{
      "scriptId":"u111"},
    "7e9256ec0ee248048bda64482ac64f85":{
      "scriptId":"u112"},
    "8628856e5b1f498da3e027807c4c6b26":{
      "scriptId":"u113"},
    "ece3260528c348b0b9bf7e5aefea8f30":{
      "scriptId":"u114"},
    "cf91d1f7264444e0a66c26cde1776879":{
      "scriptId":"u115"},
    "eb184d72e16646b18b25bb095db1a329":{
      "scriptId":"u116"},
    "d397dd144363478583e0eb42d8218961":{
      "scriptId":"u117"},
    "9721e8d5fbf4442d95bedb867616acc8":{
      "scriptId":"u118"},
    "4c05754c6cbf41bf93c2bf59d2b78469":{
      "scriptId":"u119"},
    "4c36ff5b70854870869f2e15a7889d07":{
      "scriptId":"u120"},
    "9aaa8b4864c24255b1a041f68f071046":{
      "scriptId":"u121"},
    "470086e14eb94f48ab59efd5235c505a":{
      "scriptId":"u122"},
    "89e4bacecda74146b7db6205ad57b0c6":{
      "scriptId":"u123"},
    "d8984b2d2b034a85a2249828ca4cd0e3":{
      "scriptId":"u124"},
    "71c4f82da61a4035a31db67fc9f14648":{
      "scriptId":"u125"},
    "8ba3c20056c24430943ed82342da52d5":{
      "scriptId":"u126"},
    "753996ff0fbf4ae0b6d4abb29a0f0513":{
      "scriptId":"u127"},
    "bc4ebfcb84cb49f3a41ee2c6ef2b1e01":{
      "scriptId":"u128"},
    "ac9d478a88c4445c966c73b163ed1aa6":{
      "scriptId":"u129"},
    "b69c8582d6764de2bb1ed32074dab992":{
      "scriptId":"u130"},
    "2d0339ed4e204832aa0b541122886950":{
      "scriptId":"u131"},
    "718031d55c1d4d8a8155c49a3920d921":{
      "scriptId":"u132"},
    "b929c9c3d82d4c4b8b8ee389bb14e1fd":{
      "scriptId":"u133"},
    "32a4a5884fba41748f4406fbd7084145":{
      "scriptId":"u134"},
    "6ae2dc2281a04deca16901fe76ae811d":{
      "scriptId":"u135"},
    "153187e507d441e4b84cb0957583750e":{
      "scriptId":"u136"},
    "adc81fe1e71b4221b67bac385d08be4a":{
      "scriptId":"u137"},
    "5ddb78535e744bdda5397d9678c12a23":{
      "scriptId":"u138"},
    "8bda117b271e408d96471103bf418cd0":{
      "scriptId":"u139"},
    "ff703a7c0785491c8de8a6543354beee":{
      "scriptId":"u140"},
    "f398bf74fc5146e1bf2f6f4aa24afb8e":{
      "scriptId":"u141"},
    "b4d33b39bef8454d95009b2cb8d3dd7a":{
      "scriptId":"u142"},
    "9d84b98da3a841c3b5ce127798151270":{
      "scriptId":"u143"},
    "836d10d3b83b41adaeb124da1081757a":{
      "scriptId":"u144"},
    "717ab758462f441699669a74cc60840f":{
      "scriptId":"u145"}}});