$axure.loadCurrentPage({
  "url":"修改密码.html",
  "generationDate":new Date(1448247502987.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f1c9ed41093a4ffe8e34887466760928",
    "type":"Axure:Page",
    "name":"修改密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1b5f6cdd22a94b3596b05022562e13c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":122},
            "size":{
              "width":1195,
              "height":665},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e1f385f27ea455abd76f32a2a92b3f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":122},
                "size":{
                  "width":1195,
                  "height":665},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/批量新增店员/u0.png"}},
{
          "id":"7bb6d36bcb55456689baae02d00a121e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF36B3C,
              "opacity":1},
            "location":{
              "x":235,
              "y":91},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b3a9a28d6074845a5a7350397e19896",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C,
                  "opacity":1},
                "location":{
                  "x":235,
                  "y":91},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cce1c33b51bc407aabb35c8a2a61c6eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":150},
            "size":{
              "width":107,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"673fc2545b7d45a1a43820bb954668cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":150},
                "size":{
                  "width":107,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u4.png"}},
{
          "id":"7e6a0c97ba4b49a29e658121a16bfe4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":244,
              "y":155},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4731f8407d6f47b79bc12ab482a8bb41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":244,
                  "y":155},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6ad8660555b4f59936739b4a44111e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":156},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54ed3665bd4b427482dd5068702c094a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":156},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0c85911c7d94065aea34d5df5dfe762",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":616,
              "y":157},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff33dd5eb42a49b4b91fed1436050d16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":616,
                  "y":157},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db080e0c86334554b5972cdf2b3602c8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":150},
            "size":{
              "width":138,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"5a29358d96404e42be29231a603bb0d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":815,
              "y":222},
            "size":{
              "width":94,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34add1d722504eceb6721f11713381da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":815,
                  "y":222},
                "size":{
                  "width":94,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u13.png"}},
{
          "id":"4e822d69c9714f5abfab72fd95b6c703",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":241,
              "y":279},
            "size":{
              "width":938,
              "height":104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e605f6372cf49ea8054476f68ca4dd1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":105,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3b9643ea341349ce97a0d53df5686e6b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "size":{
                      "width":105,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u16.png"}},
{
              "id":"95d9b4697d0249b5a9f24bd5f58762d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":105,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c78e15520a4245a39deebb26f0455449",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":105,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u28.png"}},
{
              "id":"7827dafcfdf148bc96e5371f3bc09f32",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":105,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"73119cba56734a29a9c726cdb8cdf3d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":105,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u40.png"}},
{
              "id":"65bf6b5ff22048bd87c4ea74924c120c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":540,
                  "y":0},
                "size":{
                  "width":104,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"58d505beebe54eb8bdd87125ff1295b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":540,
                      "y":0},
                    "size":{
                      "width":104,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u24.png"}},
{
              "id":"a84f07faf3ab4f4984a8fdeb1bfb5b3b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":540,
                  "y":30},
                "size":{
                  "width":104,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85d10d22085c408280131140a44f1dca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":540,
                      "y":30},
                    "size":{
                      "width":104,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u36.png"}},
{
              "id":"8f0db346b470468f9f668bf9649ff87c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":540,
                  "y":66},
                "size":{
                  "width":104,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8fa6323318f4d1bb27a8eb7c6120679",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":540,
                      "y":66},
                    "size":{
                      "width":104,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u48.png"}},
{
              "id":"029f9a02cf5243ca88572ebbe46b1992",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":644,
                  "y":0},
                "size":{
                  "width":294,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"beefb1494622411081d4294700712970",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":644,
                      "y":0},
                    "size":{
                      "width":294,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u26.png"}},
{
              "id":"e455208c2f124dcfa30bae547a2fd7ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":644,
                  "y":30},
                "size":{
                  "width":294,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"641ffe7f55874169983a7d879fc18453",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":644,
                      "y":30},
                    "size":{
                      "width":294,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u38.png"}},
{
              "id":"75f254e0de6b450daef336e1e34b7b8b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":644,
                  "y":66},
                "size":{
                  "width":294,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2a3034f3541c499f9e2c04c25a620b63",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":644,
                      "y":66},
                    "size":{
                      "width":294,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u50.png"}},
{
              "id":"d549526a7011434da7f06bc2481bae5f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":105,
                  "y":0},
                "size":{
                  "width":123,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7aab650232f44d6198321a4ed37ffe8c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":105,
                      "y":0},
                    "size":{
                      "width":123,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u18.png"}},
{
              "id":"ad91fdc3f79a4a6491655818e1c02720",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":105,
                  "y":30},
                "size":{
                  "width":123,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"144a4a53df504ff2835a22efaf6408a7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":105,
                      "y":30},
                    "size":{
                      "width":123,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u30.png"}},
{
              "id":"ac76a569659f4253939860f778c392b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":105,
                  "y":66},
                "size":{
                  "width":123,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"43e7d9b6ea89408d948c27d6b5d52c81",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":105,
                      "y":66},
                    "size":{
                      "width":123,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u42.png"}},
{
              "id":"48abf423374e4e0ab1f6ebe42eec07d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":228,
                  "y":0},
                "size":{
                  "width":213,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6515553a224f4574b0135715f958e4ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":228,
                      "y":0},
                    "size":{
                      "width":213,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u20.png"}},
{
              "id":"f7661b0cfa9143f0aa38a538d6b88b9b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":228,
                  "y":30},
                "size":{
                  "width":213,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e4fb4696f1bd475b83a9d77c0260a9ac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":228,
                      "y":30},
                    "size":{
                      "width":213,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u32.png"}},
{
              "id":"71553cf5477e48c487d3c69ab438428a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":228,
                  "y":66},
                "size":{
                  "width":213,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ade4889f77224643bc0e87237270ab45",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":228,
                      "y":66},
                    "size":{
                      "width":213,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u44.png"}},
{
              "id":"8cc3add774694b9dbecd3f5830eb2531",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":441,
                  "y":0},
                "size":{
                  "width":99,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"110ecc6189774599ae730ede5b264d9a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":441,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u22.png"}},
{
              "id":"296226cf5315455c8b93de3e3fb7efd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":441,
                  "y":30},
                "size":{
                  "width":99,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa4effef911b40d3911f480b57346f23",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":441,
                      "y":30},
                    "size":{
                      "width":99,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u34.png"}},
{
              "id":"e42bdcf635ae420588f9a8d90e62b8ed",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":441,
                  "y":66},
                "size":{
                  "width":99,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"445628ab1ecd44129c8d855698c5413f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":441,
                      "y":66},
                    "size":{
                      "width":99,
                      "height":38},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/店员管理/u46.png"}}]},
{
          "id":"0707345ac0834467b8856bee20606dc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":962,
              "y":322},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f17ccbaccf43fcab8f1a863b716ba8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":962,
                  "y":322},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc4b695c03514b5680258c64627098a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":998,
              "y":322},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad47c926e12e4e198a7f4a0fce3b52c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":998,
                  "y":322},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c0675fb2315472fb61c6be85a88549b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":416},
            "size":{
              "width":392,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdf387a311104d9a9787f4de03952eb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":416},
                "size":{
                  "width":392,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u56.png"}},
{
          "id":"a87cf4b31f62431489eb19194a6729e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1034,
              "y":417},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"062c047c8a8e465097b71697872e638c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1034,
                  "y":417},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u58.png"}},
{
          "id":"19a4ceefc2414935b780ad8ca045644a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":516,
              "y":428},
            "size":{
              "width":101,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d568cf2fe694f0cbba766fbaa94c3b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":516,
                  "y":428},
                "size":{
                  "width":101,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"552ec32bb73b476c9bbb82cc79597b0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1067,
              "y":222},
            "size":{
              "width":94,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"300e2f203e7a45c9b291744c3bc092d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1067,
                  "y":222},
                "size":{
                  "width":94,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u13.png"}},
{
          "id":"9aae782d47bc4a57b4063a2158051703",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":1042,
              "y":322},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"828ed4429eb04b68b9ed9fd7f448e9de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":1042,
                  "y":322},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53f8efcf19834c0897b95a953a31c25b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":1080,
              "y":322},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"216de68067694d368dc77923b157fa68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":1080,
                  "y":322},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6380c6a7b5c43af807a054b0eaa9e34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":151},
            "size":{
              "width":103,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c83ab83996f4b3f961ca7e228012dd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":151},
                "size":{
                  "width":103,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u68.png"}},
{
          "id":"4f09ed5fe6f84beba24cef1036fcb0b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":842,
              "y":156},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"567cbfdbbd0b47969c3b5e77662c55da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":842,
                  "y":156},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19cd9315d06d4186969cb0e96daafb73",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":883,
              "y":150},
            "size":{
              "width":105,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"7bb0e2ed016446cb9e8b84b6957c6680",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":158},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85ae819d5f6d44d08118c88ffe15309e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":158},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3366546995c44dbaa9da3be04e93ad9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1056,
              "y":150},
            "size":{
              "width":105,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"7812cb0a7b004822991cee98329a6754",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":943,
              "y":222},
            "size":{
              "width":94,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4661ec4821c47af9b5394f49958aac4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":943,
                  "y":222},
                "size":{
                  "width":94,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店员管理/u13.png"}},
{
          "id":"24389dd81ca54bb281cb56bffb4a589d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":115},
            "size":{
              "width":94,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/门店设置/u18_line.png"}},
{
          "id":"6d66bc508d2e415dba0596e6ae3c2669",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":352,
              "y":92},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"209952b0e003433f9e2c214da3c3ff8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":352,
                  "y":92},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c5320258f4f47808b0f3e6741987ad9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF36B3C},
            "location":{
              "x":1190,
              "y":122},
            "size":{
              "width":5,
              "height":665},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1075765453d84c23917bab8d54a8cfe6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C},
                "location":{
                  "x":1190,
                  "y":122},
                "size":{
                  "width":5,
                  "height":665},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移动门店/u52.png"}},
{
          "id":"a3223d09ebf047bcb4150fe708a24e90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF36B3C},
            "location":{
              "x":1125,
              "y":157},
            "size":{
              "width":100,
              "height":30},
            "rotation":"90",
            "textRotation":"90",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF36B3C},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4abdb12dcf4d43149e25dbd373654d3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C},
                "location":{
                  "x":1125,
                  "y":157},
                "size":{
                  "width":100,
                  "height":30},
                "rotation":"90",
                "textRotation":"90",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF36B3C},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移动门店/u54.png"}},
{
          "id":"6c4d6439c59b490d8c5e9713a8f518df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1169,
              "y":158},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bef76b20e4fc414ba3f772e7b3f16f9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1169,
                  "y":158},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d032beff471e458f9b48443250787192",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1190,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"391778cb41e8429ba17a1423b142183a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1190,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u0.png"}},
{
          "id":"ac0415c4ac4040929fedc11468fb50f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-6},
            "size":{
              "width":808,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9830b56a7b149e383c7ddcfab34a40d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-6},
                "size":{
                  "width":808,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u104.png"}},
{
          "id":"9d02b06465e84ced9b21e75e731c8c76",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1044,
              "y":25},
            "size":{
              "width":66,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b4f226128e9452c99c40ac5a0c36770",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1044,
                  "y":25},
                "size":{
                  "width":66,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u106.png"}},
{
          "id":"3730474599e4429d9a846256ad068809",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3F4A59},
            "location":{
              "x":0,
              "y":79},
            "size":{
              "width":80,
              "height":708},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd0e39ea78ab42fc9020af78fc3e3deb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59},
                "location":{
                  "x":0,
                  "y":79},
                "size":{
                  "width":80,
                  "height":708},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u108.png"}},
{
          "id":"d5503cf75989476db2db8673f78dd86b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":78},
            "size":{
              "width":80,
              "height":511},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3F4A59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"530e6ea3c3f54dbfbd9546e5a7716faa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":78},
                "size":{
                  "width":80,
                  "height":511},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3F4A59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u110.png"}},
{
          "id":"3895920d3bca4c488f715d2d621cb9ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":79,
              "y":80},
            "size":{
              "width":140,
              "height":706},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cbd78de1668491d830bd5451ce8ded3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":79,
                  "y":80},
                "size":{
                  "width":140,
                  "height":706},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u112.png"}},
{
          "id":"0a8041aa58e043138e5a290e507db043",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":147},
            "size":{
              "width":14,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1558f1106da549a29309d6d38477359f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":147},
                "size":{
                  "width":14,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u114.png"}},
{
          "id":"d83fee83d0794030b29af820982b7c44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":93,
              "y":100},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4209999a715b41d9b96a40ef3cc762f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":93,
                  "y":100},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6795347c5c684734a621212522c97547",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2BC589,
              "opacity":1},
            "location":{
              "x":93,
              "y":141},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2f0e4f0474c490e98f2373f20a812b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2BC589,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":141},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ee91d6d75d54b278161038e0a3558f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":106},
            "size":{
              "width":13,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a01cff2879c4e3288f37570c41e1fce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":106},
                "size":{
                  "width":13,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/门店设置/u120.png"}},
{
          "id":"095f3595ef5e46809672832ecd0704c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x66000000},
            "size":{
              "width":1196,
              "height":787}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09c61607112b4b56bb3dec93cbfe2bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x66000000},
                "size":{
                  "width":1196,
                  "height":787}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/批量新增店员/u107.png"}},
{
          "id":"10e64e6829ea40e0a1495dfe920a72bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":485,
              "y":222},
            "size":{
              "width":395,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0ae1557a3b544348cc02e005b8f1109",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":485,
                  "y":222},
                "size":{
                  "width":395,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u109.png"}},
{
          "id":"79b9913f4bbc4555b16eb35358904873",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":533,
              "y":266},
            "size":{
              "width":327,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码/u111_line.png"}},
{
          "id":"39381985e4444151b16194e8c179b954",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":646,
              "y":237},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a28a140bd91d4991b8b2c9b84051d492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":646,
                  "y":237},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"459967d36e7f4c35854a56b00be36af2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":239},
            "size":{
              "width":10,
              "height":19},
            "rotation":"40",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/修改密码/u114_line.png"}},
{
          "id":"1a4c0e44a2c94b7babce0901796f1198",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":238},
            "size":{
              "width":10,
              "height":20},
            "rotation":"320",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/批量新增店员/u227_line.png"}},
{
          "id":"08393a108d984ac4b28a0ef0c10e54b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":551,
              "y":413},
            "size":{
              "width":124,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fff3ddfa96f94fae916d0322a60c6885",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":551,
                  "y":413},
                "size":{
                  "width":124,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u233.png"}},
{
          "id":"69ca394d85b44df597e6cbc72821eb81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":688,
              "y":413},
            "size":{
              "width":124,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"917ace5aca4a429c941859c753dc945a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":688,
                  "y":413},
                "size":{
                  "width":124,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u233.png"}},
{
          "id":"8d8a88a56ba4452ab00b47e75fc707e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":548,
              "y":303},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c914ac9e8fc84392b4d1302e268eef7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":548,
                  "y":303},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"687d3a139aa342cfa5e89cb1a9053c4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":535,
              "y":352},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5501380a45db493e9e60a6e46f7af662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":535,
                  "y":352},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e287fdc863f544388cf16e63357fbeeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":612,
              "y":297},
            "size":{
              "width":199,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dac05f1aba924c5095ad18e7dc89b469",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":612,
                  "y":297},
                "size":{
                  "width":199,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u124.png"}},
{
          "id":"82b1d88b4f8449498c69ecda1597ed1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":612,
              "y":345},
            "size":{
              "width":199,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cc882460e464fb29c27483c45789c7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":612,
                  "y":345},
                "size":{
                  "width":199,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u124.png"}},
{
          "id":"d53b83546f0a4c499165ac50c132ed7b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":303},
            "size":{
              "width":14,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"156ef399d38e4c3db2fbe3f66e6308ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":303},
                "size":{
                  "width":14,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u132.png"}},
{
          "id":"8a1df44884ad43d29dcff1d0ba42d03f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":511,
              "y":351},
            "size":{
              "width":14,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecb5c38516564e74bbf8308945b06f40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":511,
                  "y":351},
                "size":{
                  "width":14,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑门店/u132.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1b5f6cdd22a94b3596b05022562e13c4":{
      "scriptId":"u0"},
    "2e1f385f27ea455abd76f32a2a92b3f4":{
      "scriptId":"u1"},
    "7bb6d36bcb55456689baae02d00a121e":{
      "scriptId":"u2"},
    "7b3a9a28d6074845a5a7350397e19896":{
      "scriptId":"u3"},
    "cce1c33b51bc407aabb35c8a2a61c6eb":{
      "scriptId":"u4"},
    "673fc2545b7d45a1a43820bb954668cd":{
      "scriptId":"u5"},
    "7e6a0c97ba4b49a29e658121a16bfe4f":{
      "scriptId":"u6"},
    "4731f8407d6f47b79bc12ab482a8bb41":{
      "scriptId":"u7"},
    "d6ad8660555b4f59936739b4a44111e2":{
      "scriptId":"u8"},
    "54ed3665bd4b427482dd5068702c094a":{
      "scriptId":"u9"},
    "a0c85911c7d94065aea34d5df5dfe762":{
      "scriptId":"u10"},
    "ff33dd5eb42a49b4b91fed1436050d16":{
      "scriptId":"u11"},
    "db080e0c86334554b5972cdf2b3602c8":{
      "scriptId":"u12"},
    "5a29358d96404e42be29231a603bb0d0":{
      "scriptId":"u13"},
    "34add1d722504eceb6721f11713381da":{
      "scriptId":"u14"},
    "4e822d69c9714f5abfab72fd95b6c703":{
      "scriptId":"u15"},
    "3e605f6372cf49ea8054476f68ca4dd1":{
      "scriptId":"u16"},
    "3b9643ea341349ce97a0d53df5686e6b":{
      "scriptId":"u17"},
    "d549526a7011434da7f06bc2481bae5f":{
      "scriptId":"u18"},
    "7aab650232f44d6198321a4ed37ffe8c":{
      "scriptId":"u19"},
    "48abf423374e4e0ab1f6ebe42eec07d6":{
      "scriptId":"u20"},
    "6515553a224f4574b0135715f958e4ae":{
      "scriptId":"u21"},
    "8cc3add774694b9dbecd3f5830eb2531":{
      "scriptId":"u22"},
    "110ecc6189774599ae730ede5b264d9a":{
      "scriptId":"u23"},
    "65bf6b5ff22048bd87c4ea74924c120c":{
      "scriptId":"u24"},
    "58d505beebe54eb8bdd87125ff1295b5":{
      "scriptId":"u25"},
    "029f9a02cf5243ca88572ebbe46b1992":{
      "scriptId":"u26"},
    "beefb1494622411081d4294700712970":{
      "scriptId":"u27"},
    "95d9b4697d0249b5a9f24bd5f58762d3":{
      "scriptId":"u28"},
    "c78e15520a4245a39deebb26f0455449":{
      "scriptId":"u29"},
    "ad91fdc3f79a4a6491655818e1c02720":{
      "scriptId":"u30"},
    "144a4a53df504ff2835a22efaf6408a7":{
      "scriptId":"u31"},
    "f7661b0cfa9143f0aa38a538d6b88b9b":{
      "scriptId":"u32"},
    "e4fb4696f1bd475b83a9d77c0260a9ac":{
      "scriptId":"u33"},
    "296226cf5315455c8b93de3e3fb7efd8":{
      "scriptId":"u34"},
    "aa4effef911b40d3911f480b57346f23":{
      "scriptId":"u35"},
    "a84f07faf3ab4f4984a8fdeb1bfb5b3b":{
      "scriptId":"u36"},
    "85d10d22085c408280131140a44f1dca":{
      "scriptId":"u37"},
    "e455208c2f124dcfa30bae547a2fd7ff":{
      "scriptId":"u38"},
    "641ffe7f55874169983a7d879fc18453":{
      "scriptId":"u39"},
    "7827dafcfdf148bc96e5371f3bc09f32":{
      "scriptId":"u40"},
    "73119cba56734a29a9c726cdb8cdf3d9":{
      "scriptId":"u41"},
    "ac76a569659f4253939860f778c392b5":{
      "scriptId":"u42"},
    "43e7d9b6ea89408d948c27d6b5d52c81":{
      "scriptId":"u43"},
    "71553cf5477e48c487d3c69ab438428a":{
      "scriptId":"u44"},
    "ade4889f77224643bc0e87237270ab45":{
      "scriptId":"u45"},
    "e42bdcf635ae420588f9a8d90e62b8ed":{
      "scriptId":"u46"},
    "445628ab1ecd44129c8d855698c5413f":{
      "scriptId":"u47"},
    "8f0db346b470468f9f668bf9649ff87c":{
      "scriptId":"u48"},
    "f8fa6323318f4d1bb27a8eb7c6120679":{
      "scriptId":"u49"},
    "75f254e0de6b450daef336e1e34b7b8b":{
      "scriptId":"u50"},
    "2a3034f3541c499f9e2c04c25a620b63":{
      "scriptId":"u51"},
    "0707345ac0834467b8856bee20606dc5":{
      "scriptId":"u52"},
    "c1f17ccbaccf43fcab8f1a863b716ba8":{
      "scriptId":"u53"},
    "cc4b695c03514b5680258c64627098a1":{
      "scriptId":"u54"},
    "ad47c926e12e4e198a7f4a0fce3b52c1":{
      "scriptId":"u55"},
    "0c0675fb2315472fb61c6be85a88549b":{
      "scriptId":"u56"},
    "bdf387a311104d9a9787f4de03952eb1":{
      "scriptId":"u57"},
    "a87cf4b31f62431489eb19194a6729e7":{
      "scriptId":"u58"},
    "062c047c8a8e465097b71697872e638c":{
      "scriptId":"u59"},
    "19a4ceefc2414935b780ad8ca045644a":{
      "scriptId":"u60"},
    "8d568cf2fe694f0cbba766fbaa94c3b8":{
      "scriptId":"u61"},
    "552ec32bb73b476c9bbb82cc79597b0e":{
      "scriptId":"u62"},
    "300e2f203e7a45c9b291744c3bc092d9":{
      "scriptId":"u63"},
    "9aae782d47bc4a57b4063a2158051703":{
      "scriptId":"u64"},
    "828ed4429eb04b68b9ed9fd7f448e9de":{
      "scriptId":"u65"},
    "53f8efcf19834c0897b95a953a31c25b":{
      "scriptId":"u66"},
    "216de68067694d368dc77923b157fa68":{
      "scriptId":"u67"},
    "d6380c6a7b5c43af807a054b0eaa9e34":{
      "scriptId":"u68"},
    "9c83ab83996f4b3f961ca7e228012dd8":{
      "scriptId":"u69"},
    "4f09ed5fe6f84beba24cef1036fcb0b0":{
      "scriptId":"u70"},
    "567cbfdbbd0b47969c3b5e77662c55da":{
      "scriptId":"u71"},
    "19cd9315d06d4186969cb0e96daafb73":{
      "scriptId":"u72"},
    "7bb0e2ed016446cb9e8b84b6957c6680":{
      "scriptId":"u73"},
    "85ae819d5f6d44d08118c88ffe15309e":{
      "scriptId":"u74"},
    "b3366546995c44dbaa9da3be04e93ad9":{
      "scriptId":"u75"},
    "7812cb0a7b004822991cee98329a6754":{
      "scriptId":"u76"},
    "c4661ec4821c47af9b5394f49958aac4":{
      "scriptId":"u77"},
    "24389dd81ca54bb281cb56bffb4a589d":{
      "scriptId":"u78"},
    "6d66bc508d2e415dba0596e6ae3c2669":{
      "scriptId":"u79"},
    "209952b0e003433f9e2c214da3c3ff8b":{
      "scriptId":"u80"},
    "4c5320258f4f47808b0f3e6741987ad9":{
      "scriptId":"u81"},
    "1075765453d84c23917bab8d54a8cfe6":{
      "scriptId":"u82"},
    "a3223d09ebf047bcb4150fe708a24e90":{
      "scriptId":"u83"},
    "4abdb12dcf4d43149e25dbd373654d3f":{
      "scriptId":"u84"},
    "6c4d6439c59b490d8c5e9713a8f518df":{
      "scriptId":"u85"},
    "bef76b20e4fc414ba3f772e7b3f16f9a":{
      "scriptId":"u86"},
    "d032beff471e458f9b48443250787192":{
      "scriptId":"u87"},
    "391778cb41e8429ba17a1423b142183a":{
      "scriptId":"u88"},
    "ac0415c4ac4040929fedc11468fb50f2":{
      "scriptId":"u89"},
    "b9830b56a7b149e383c7ddcfab34a40d":{
      "scriptId":"u90"},
    "9d02b06465e84ced9b21e75e731c8c76":{
      "scriptId":"u91"},
    "6b4f226128e9452c99c40ac5a0c36770":{
      "scriptId":"u92"},
    "3730474599e4429d9a846256ad068809":{
      "scriptId":"u93"},
    "cd0e39ea78ab42fc9020af78fc3e3deb":{
      "scriptId":"u94"},
    "d5503cf75989476db2db8673f78dd86b":{
      "scriptId":"u95"},
    "530e6ea3c3f54dbfbd9546e5a7716faa":{
      "scriptId":"u96"},
    "3895920d3bca4c488f715d2d621cb9ac":{
      "scriptId":"u97"},
    "8cbd78de1668491d830bd5451ce8ded3":{
      "scriptId":"u98"},
    "0a8041aa58e043138e5a290e507db043":{
      "scriptId":"u99"},
    "1558f1106da549a29309d6d38477359f":{
      "scriptId":"u100"},
    "d83fee83d0794030b29af820982b7c44":{
      "scriptId":"u101"},
    "4209999a715b41d9b96a40ef3cc762f1":{
      "scriptId":"u102"},
    "6795347c5c684734a621212522c97547":{
      "scriptId":"u103"},
    "f2f0e4f0474c490e98f2373f20a812b9":{
      "scriptId":"u104"},
    "2ee91d6d75d54b278161038e0a3558f6":{
      "scriptId":"u105"},
    "1a01cff2879c4e3288f37570c41e1fce":{
      "scriptId":"u106"},
    "095f3595ef5e46809672832ecd0704c0":{
      "scriptId":"u107"},
    "09c61607112b4b56bb3dec93cbfe2bd2":{
      "scriptId":"u108"},
    "10e64e6829ea40e0a1495dfe920a72bf":{
      "scriptId":"u109"},
    "b0ae1557a3b544348cc02e005b8f1109":{
      "scriptId":"u110"},
    "79b9913f4bbc4555b16eb35358904873":{
      "scriptId":"u111"},
    "39381985e4444151b16194e8c179b954":{
      "scriptId":"u112"},
    "a28a140bd91d4991b8b2c9b84051d492":{
      "scriptId":"u113"},
    "459967d36e7f4c35854a56b00be36af2":{
      "scriptId":"u114"},
    "1a4c0e44a2c94b7babce0901796f1198":{
      "scriptId":"u115"},
    "08393a108d984ac4b28a0ef0c10e54b5":{
      "scriptId":"u116"},
    "fff3ddfa96f94fae916d0322a60c6885":{
      "scriptId":"u117"},
    "69ca394d85b44df597e6cbc72821eb81":{
      "scriptId":"u118"},
    "917ace5aca4a429c941859c753dc945a":{
      "scriptId":"u119"},
    "8d8a88a56ba4452ab00b47e75fc707e4":{
      "scriptId":"u120"},
    "c914ac9e8fc84392b4d1302e268eef7e":{
      "scriptId":"u121"},
    "687d3a139aa342cfa5e89cb1a9053c4d":{
      "scriptId":"u122"},
    "5501380a45db493e9e60a6e46f7af662":{
      "scriptId":"u123"},
    "e287fdc863f544388cf16e63357fbeeb":{
      "scriptId":"u124"},
    "dac05f1aba924c5095ad18e7dc89b469":{
      "scriptId":"u125"},
    "82b1d88b4f8449498c69ecda1597ed1a":{
      "scriptId":"u126"},
    "9cc882460e464fb29c27483c45789c7c":{
      "scriptId":"u127"},
    "d53b83546f0a4c499165ac50c132ed7b":{
      "scriptId":"u128"},
    "156ef399d38e4c3db2fbe3f66e6308ac":{
      "scriptId":"u129"},
    "8a1df44884ad43d29dcff1d0ba42d03f":{
      "scriptId":"u130"},
    "ecb5c38516564e74bbf8308945b06f40":{
      "scriptId":"u131"}}});