$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1448247499546.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cb54fe1bf1e04e6d9194b96a56883784",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"57b1234feed3429f842c33ab8012603e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d346ea440f55475fbda5809912d19d79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"c5fc7a3d99834866ad31db449ace9135",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":123},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e90251169294e66b985104ea05c0b5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":37,
                  "y":123},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u2.png"}},
{
          "id":"f5a51bfebe6b4f7a93a147bd224c2392",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":114},
            "size":{
              "width":325,
              "height":573}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccb0b46bbae44145a46234800f517028",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":114},
                "size":{
                  "width":325,
                  "height":573}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"5858c41ebb024482a09f26c20a6876df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":227},
            "size":{
              "width":153,
              "height":131}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"956acc8d86f24ce69fd87c7535cc78c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":227},
                "size":{
                  "width":153,
                  "height":131}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u6.png"}},
{
          "id":"dcc975947f63476ca63ec4fc685efe92",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":146},
            "size":{
              "width":44,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3db10d4b94d048aea19b1f33e95f0c6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":146},
                "size":{
                  "width":44,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"28fa14b1a6aa4fda8b40cbbde6095561",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":301,
              "y":146},
            "size":{
              "width":44,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"996c87ff02a0499cae4be8bb8ea00a65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":301,
                  "y":146},
                "size":{
                  "width":44,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"fdd4319c4ae0482ea4d0255dfc83fe78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":137},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddb12996b88f455eaf88f7a958fa691b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":137},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"d7958bc2fe72493e8f24f627bbe38a3e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":444},
            "size":{
              "width":281,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec6eb646b9f24850a2449e3b84618eb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":444},
                "size":{
                  "width":281,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"f63ebb70944242679f23797209aa930a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF424242},
            "location":{
              "x":58,
              "y":279},
            "size":{
              "width":49,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dd3a91f3b62465fa0da4f20dd64978a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF424242},
                "location":{
                  "x":58,
                  "y":279},
                "size":{
                  "width":49,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u16.png"}},
{
          "id":"c6d9c4a6894a4ab0ad49df137e8b5cd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":120,
              "y":284},
            "size":{
              "width":61,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f3c29afb4bf4e1dab180f5f99a850ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":284},
                "size":{
                  "width":61,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f047c12fb3a4e4ab41a7f87b2ac3871",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":120,
              "y":310},
            "size":{
              "width":213,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca5a615a87fc4cf1872e08b9af984b37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":310},
                "size":{
                  "width":213,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"038431e17751445fa7526aadd3210e6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF424242},
            "location":{
              "x":58,
              "y":367},
            "size":{
              "width":49,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3b5da0ffe2e43d6ba065a2dda4db453",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF424242},
                "location":{
                  "x":58,
                  "y":367},
                "size":{
                  "width":49,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u16.png"}},
{
          "id":"90a86a1a605243a4b6fa8f327447a2df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":120,
              "y":372},
            "size":{
              "width":61,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d83dda31ca474d62a805f0d4f6c3396d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":372},
                "size":{
                  "width":61,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d0a4b77e28446fba87fe53c02a2bb20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":120,
              "y":398},
            "size":{
              "width":213,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70572b2b33f44170b1c292e998c4d3a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":398},
                "size":{
                  "width":213,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d57e66826f1d4b5d9a16cee8a1831a08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF424242},
            "location":{
              "x":60,
              "y":459},
            "size":{
              "width":49,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a0ba01abb844b749ea4e9c6693c327e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF424242},
                "location":{
                  "x":60,
                  "y":459},
                "size":{
                  "width":49,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u16.png"}},
{
          "id":"d54564d1cc424809b779a6f8ddb12b52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":122,
              "y":464},
            "size":{
              "width":61,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb0786a7db504755a626e04ba2b2ca5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":122,
                  "y":464},
                "size":{
                  "width":61,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1bf23f7a72943f6a54cd17f14e16c80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":122,
              "y":490},
            "size":{
              "width":213,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6deff5c918e480fb6626d3e43e485d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":122,
                  "y":490},
                "size":{
                  "width":213,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a50019ef4bf4e5cab36c96ffd43ceb3",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":328},
            "size":{
              "width":10,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u34_line.png"}},
{
          "id":"92325bf199ec4eabaef4bc6e5eca031b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":416},
            "size":{
              "width":10,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u35_line.png"}},
{
          "id":"7eb5240462244e529b117498efc57ddd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":69,
              "y":610},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eaf28cec18346498b395866367c729f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":69,
                  "y":610},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u36.png"}},
{
          "id":"3402f792664947a08b20b727969946a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":174.5,
              "y":610},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"737a4d6b9e9841b5a1ef22fcea5f9499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174.5,
                  "y":610},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u36.png"}},
{
          "id":"51e557239b3f435d9074e40e0057be8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":610},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6774a848296448e9bd4574e8b1b99200",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":610},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u36.png"}},
{
          "id":"e6cb1fabdfca4f6a82aee9ad92294c5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4A4A4A},
            "location":{
              "x":62,
              "y":654},
            "size":{
              "width":55,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4A4A4A}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1e2024a3b7c446890af6dde8b9e353e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4A4A4A},
                "location":{
                  "x":62,
                  "y":654},
                "size":{
                  "width":55,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4A4A4A}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"93c1464ef8394659b69adab815daccd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4A4A4A},
            "location":{
              "x":166,
              "y":655},
            "size":{
              "width":55,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4A4A4A}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d25665c0bbdf4a1f9209e04927dddea9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4A4A4A},
                "location":{
                  "x":166,
                  "y":655},
                "size":{
                  "width":55,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4A4A4A}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"fe65477e17b6442c81219375fb3c01ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4A4A4A},
            "location":{
              "x":272,
              "y":655},
            "size":{
              "width":55,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4A4A4A}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f09d013e7b47399e01084059c871ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4A4A4A},
                "location":{
                  "x":272,
                  "y":655},
                "size":{
                  "width":55,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4A4A4A}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"67116d8432b04fd4ac4196832a35e95f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":58,
              "y":166},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"204e9bfb5aba41c48115c85a2e7b4ee9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":166},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"528ba2d8ab9d4decb5748172b2c0a9a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":58,
              "y":198},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3969c1091e1b471ea641f89c2afe5643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":198},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "57b1234feed3429f842c33ab8012603e":{
      "scriptId":"u0"},
    "d346ea440f55475fbda5809912d19d79":{
      "scriptId":"u1"},
    "c5fc7a3d99834866ad31db449ace9135":{
      "scriptId":"u2"},
    "1e90251169294e66b985104ea05c0b5a":{
      "scriptId":"u3"},
    "f5a51bfebe6b4f7a93a147bd224c2392":{
      "scriptId":"u4"},
    "ccb0b46bbae44145a46234800f517028":{
      "scriptId":"u5"},
    "5858c41ebb024482a09f26c20a6876df":{
      "scriptId":"u6"},
    "956acc8d86f24ce69fd87c7535cc78c1":{
      "scriptId":"u7"},
    "dcc975947f63476ca63ec4fc685efe92":{
      "scriptId":"u8"},
    "3db10d4b94d048aea19b1f33e95f0c6e":{
      "scriptId":"u9"},
    "28fa14b1a6aa4fda8b40cbbde6095561":{
      "scriptId":"u10"},
    "996c87ff02a0499cae4be8bb8ea00a65":{
      "scriptId":"u11"},
    "fdd4319c4ae0482ea4d0255dfc83fe78":{
      "scriptId":"u12"},
    "ddb12996b88f455eaf88f7a958fa691b":{
      "scriptId":"u13"},
    "d7958bc2fe72493e8f24f627bbe38a3e":{
      "scriptId":"u14"},
    "ec6eb646b9f24850a2449e3b84618eb1":{
      "scriptId":"u15"},
    "f63ebb70944242679f23797209aa930a":{
      "scriptId":"u16"},
    "8dd3a91f3b62465fa0da4f20dd64978a":{
      "scriptId":"u17"},
    "c6d9c4a6894a4ab0ad49df137e8b5cd9":{
      "scriptId":"u18"},
    "7f3c29afb4bf4e1dab180f5f99a850ad":{
      "scriptId":"u19"},
    "9f047c12fb3a4e4ab41a7f87b2ac3871":{
      "scriptId":"u20"},
    "ca5a615a87fc4cf1872e08b9af984b37":{
      "scriptId":"u21"},
    "038431e17751445fa7526aadd3210e6c":{
      "scriptId":"u22"},
    "d3b5da0ffe2e43d6ba065a2dda4db453":{
      "scriptId":"u23"},
    "90a86a1a605243a4b6fa8f327447a2df":{
      "scriptId":"u24"},
    "d83dda31ca474d62a805f0d4f6c3396d":{
      "scriptId":"u25"},
    "3d0a4b77e28446fba87fe53c02a2bb20":{
      "scriptId":"u26"},
    "70572b2b33f44170b1c292e998c4d3a3":{
      "scriptId":"u27"},
    "d57e66826f1d4b5d9a16cee8a1831a08":{
      "scriptId":"u28"},
    "7a0ba01abb844b749ea4e9c6693c327e":{
      "scriptId":"u29"},
    "d54564d1cc424809b779a6f8ddb12b52":{
      "scriptId":"u30"},
    "bb0786a7db504755a626e04ba2b2ca5b":{
      "scriptId":"u31"},
    "d1bf23f7a72943f6a54cd17f14e16c80":{
      "scriptId":"u32"},
    "b6deff5c918e480fb6626d3e43e485d8":{
      "scriptId":"u33"},
    "9a50019ef4bf4e5cab36c96ffd43ceb3":{
      "scriptId":"u34"},
    "92325bf199ec4eabaef4bc6e5eca031b":{
      "scriptId":"u35"},
    "7eb5240462244e529b117498efc57ddd":{
      "scriptId":"u36"},
    "5eaf28cec18346498b395866367c729f":{
      "scriptId":"u37"},
    "3402f792664947a08b20b727969946a4":{
      "scriptId":"u38"},
    "737a4d6b9e9841b5a1ef22fcea5f9499":{
      "scriptId":"u39"},
    "51e557239b3f435d9074e40e0057be8b":{
      "scriptId":"u40"},
    "6774a848296448e9bd4574e8b1b99200":{
      "scriptId":"u41"},
    "e6cb1fabdfca4f6a82aee9ad92294c5d":{
      "scriptId":"u42"},
    "e1e2024a3b7c446890af6dde8b9e353e":{
      "scriptId":"u43"},
    "93c1464ef8394659b69adab815daccd6":{
      "scriptId":"u44"},
    "d25665c0bbdf4a1f9209e04927dddea9":{
      "scriptId":"u45"},
    "fe65477e17b6442c81219375fb3c01ff":{
      "scriptId":"u46"},
    "70f09d013e7b47399e01084059c871ea":{
      "scriptId":"u47"},
    "67116d8432b04fd4ac4196832a35e95f":{
      "scriptId":"u48"},
    "204e9bfb5aba41c48115c85a2e7b4ee9":{
      "scriptId":"u49"},
    "528ba2d8ab9d4decb5748172b2c0a9a5":{
      "scriptId":"u50"},
    "3969c1091e1b471ea641f89c2afe5643":{
      "scriptId":"u51"}}});