$axure.loadCurrentPage({
  "url":"添加图文信息.html",
  "generationDate":new Date(1449052591820.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"91cc733914a24cd5ab78c1ec0b091002",
    "type":"Axure:Page",
    "name":"添加图文信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ec0525575fbf4948a5c6e24f4fe5e988",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":1190,
              "height":920},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"132cabc758b449988d9eef86808b34b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":1190,
                  "height":920},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加一级菜单/u37.png"}},
{
          "id":"fa32bd1079e54d83af5fce8b5be330d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF1E2631},
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":165,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8197ece904846a6b24b20b5205c63ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1E2631},
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":165,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加一级菜单/u17.png"}},
{
          "id":"fccb176a3d474021a8b3501322e1761c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":129,
              "y":290},
            "size":{
              "width":15,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1211da00254497c9747695dc06e4c27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":129,
                  "y":290},
                "size":{
                  "width":15,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三方接入_微信接口/u13.png"}},
{
          "id":"b95effcf4535423e85ecdd965f2f2107",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":285},
            "size":{
              "width":113,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e5c564045714b91990586270ab54cc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":285},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5484633ed85b48eab1d7a496b41431c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":357},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e6db97d110f4f189eb28b8161832f67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":357},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"081ceded34f246589d94e56063fdad82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF747969,
              "opacity":1},
            "location":{
              "x":22,
              "y":385},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab193a5c6b2b4e85a3a37bbbcfa84f24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF747969,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":385},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91e3e8eb919c4b55bb2e7e96a30c96e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":22,
              "y":413},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c9253a1860943de9db77ae1339d939b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":413},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e4cfaf7b34f4f34ba40d9e21d41cac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":18,
              "y":20},
            "size":{
              "width":102,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2924771d93f1443ca880132cc7520422",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":20},
                "size":{
                  "width":102,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"743955fd4de548e2818e04b65aa62d87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":163,
              "y":42},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1823759225cf40558f1d2fbf2d9d3872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":163,
                  "y":42},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"513c1ac3ede54298b17cdd97984465fd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":75},
            "size":{
              "width":1190,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商家信息/u26_line.png"}},
{
          "id":"65cdc9b832c24ec58c251f61a0ae9566",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":125,
              "y":124},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6329daf01b7d44079075a8fa12f55aaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":124},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"19abbcb6aa9745a5bb5e3567604d5121",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":125,
              "y":203},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"813cc8c12f3944a5ba6e40122bd419aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":203},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家信息/u8.png"}},
{
          "id":"3aa49264a1a04b0e82bbd2853fd1378b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797971,
              "opacity":1},
            "location":{
              "x":22,
              "y":124},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a36ea909b9ef4fde8a3c4d6632dad7a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797971,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":124},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6bac8103dec4bfb890f7157f33010b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":22,
              "y":202},
            "size":{
              "width":93,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7574aa9fa65846b9adf61d050db56601",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":202},
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ab259ae954842aeb1add0abc1f81200",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "size":{
              "width":1190,
              "height":920}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ed6fff5139545a3b8ceb138926f3cf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "size":{
                  "width":1190,
                  "height":920}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单-跳转网页/u94.png"}},
{
          "id":"ff1d16b40e9b4988a7b51719fe9106f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":157,
              "y":85},
            "size":{
              "width":558,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75d21d075a9740a38ba9cba8d69d4e05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":157,
                  "y":85},
                "size":{
                  "width":558,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59ea00945631467b873c3798119a95b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":836,
              "y":676},
            "size":{
              "width":227,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6089a792837a4e428857476d7e322454",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":836,
                  "y":676},
                "size":{
                  "width":227,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u51.png"}},
{
          "id":"dfcbf275b7074bb7a67f0b96a4e1d912",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":161,
              "y":0},
            "size":{
              "width":1029,
              "height":920},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1772fa658284adfb1fba09e42cd5ae2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":161,
                  "y":0},
                "size":{
                  "width":1029,
                  "height":920},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加图文信息/u33.png"}},
{
          "id":"f02732d2e6fa425bad348a3d93466cf0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":76},
            "size":{
              "width":1013,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加图文信息/u35_line.png"}},
{
          "id":"084638aa427245c9b5e283d6a35b4fc9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":304},
            "size":{
              "width":248,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单-跳转网页/u129_line.png"}},
{
          "id":"4b62ec82cba941fba817fc338b7fb2d8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":199,
              "y":413},
            "size":{
              "width":248,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单-跳转网页/u129_line.png"}},
{
          "id":"1dab1197d0404a13883132ee9cd1ba5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":211,
              "y":142},
            "size":{
              "width":31,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"019fe4228fbf4f9fb4c883d7ab1403d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":211,
                  "y":142},
                "size":{
                  "width":31,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u107.png"}},
{
          "id":"cee069d95ba64a3bbf241aa8dcb9043a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1136,
              "y":435},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d6a64189b9e4baa958f046741fcdb32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1136,
                  "y":435},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d89e4ae3720242889950b47804ce8fa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1136,
              "y":236},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fe1bfba8eb640278f88dd360951828d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1136,
                  "y":236},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97701f831f644e119fe36fc6b178df08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":833,
              "y":649},
            "size":{
              "width":227,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35e8406be409419ca16a44b4f878bb5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":833,
                  "y":649},
                "size":{
                  "width":227,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u51.png"}},
{
          "id":"ee883e78b5ae4b289099eba1ea80c5ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":207,
              "y":89},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"331bb851b0be4c3e9317d4c919fcb86e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":207,
                  "y":89},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"151d25fdaf66415c96badf2aca00e735",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":184,
              "y":139},
            "size":{
              "width":263,
              "height":603},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2e2fa5cff0548cba9d6f96d9c382486",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":184,
                  "y":139},
                "size":{
                  "width":263,
                  "height":603},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u57.png"}},
{
          "id":"afa8459612a94fb887d1a6e64a172845",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":184,
              "y":139},
            "size":{
              "width":263,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"778fefbb64bb470c8f05831f70e8a819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":184,
                  "y":139},
                "size":{
                  "width":263,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u59.png"}},
{
          "id":"c2cdb14737b145af82cb7f062d505030",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":446,
              "y":139},
            "size":{
              "width":323,
              "height":603},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d2ec4e4f8274f40a9c608de4741d7f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":446,
                  "y":139},
                "size":{
                  "width":323,
                  "height":603},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u61.png"}},
{
          "id":"ac18d37fd487435583745b2e90fe13a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":447,
              "y":139},
            "size":{
              "width":323,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5851c5c58f4b45fb9a962dcc96c003ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":447,
                  "y":139},
                "size":{
                  "width":323,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u63.png"}},
{
          "id":"3c4de90f78df4fda8b26b2de22cc2c29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":769,
              "y":139},
            "size":{
              "width":396,
              "height":603},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29d7ee6cb4c14be3b39604a7a0da7baa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":769,
                  "y":139},
                "size":{
                  "width":396,
                  "height":603},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u65.png"}},
{
          "id":"555c0529b69d42dfbfb42b77c21e0c1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":769,
              "y":139},
            "size":{
              "width":396,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8726ecece8e4ce58b2ee9947e621365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":769,
                  "y":139},
                "size":{
                  "width":396,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u67.png"}},
{
          "id":"d92c17fde52d4254b27d47913a60e132",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF44B549},
            "location":{
              "x":662,
              "y":785},
            "size":{
              "width":187,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cfe637a61ff460988b6cdf324f1b3a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF44B549},
                "location":{
                  "x":662,
                  "y":785},
                "size":{
                  "width":187,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u74.png"}},
{
          "id":"1dd356e5bd844cae983fe7b17d69c8dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":198,
              "y":203},
            "size":{
              "width":77,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"002d8bdcb14b48188b5214fdb4a6151d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":198,
                  "y":203},
                "size":{
                  "width":77,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u76.png"}},
{
          "id":"171caa2c250245fabeda4fa32d52148b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":291,
              "y":227},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95822095778345818f035ae3429badc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":291,
                  "y":227},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c59a466bef747f99d0170fb22616e1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":510,
              "y":203},
            "size":{
              "width":77,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e06a727f2c349979cf65a86135846ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":510,
                  "y":203},
                "size":{
                  "width":77,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u76.png"}},
{
          "id":"868c8c41704e47a68412e9bd01b6c2b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":601,
              "y":211},
            "size":{
              "width":79,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa3d3aa3d686456d8f6f5939b3839356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":601,
                  "y":211},
                "size":{
                  "width":79,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34b2b055f91849f4b561571228782e7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":785,
              "y":203},
            "size":{
              "width":367,
              "height":357},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"775de5463b3c484e8f6f682df51540ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":785,
                  "y":203},
                "size":{
                  "width":367,
                  "height":357},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u84.png"}},
{
          "id":"e321b096b340419f8754c3f4187396f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":427,
              "y":785},
            "size":{
              "width":187,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a258cc1c99dd46bcaf2ace917cbc79e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":427,
                  "y":785},
                "size":{
                  "width":187,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u86.png"}},
{
          "id":"05e609745f7941168f10bf8a6d390020",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":799,
              "y":215},
            "size":{
              "width":340,
              "height":318}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfb0dc15a2aa48f68643328ba769aca5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":799,
                  "y":215},
                "size":{
                  "width":340,
                  "height":318}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u88.png"}},
{
          "id":"469e390efdae4b57a00062e236b91fe5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":463,
              "y":219},
            "size":{
              "width":33,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20277a2784364ec6aaecb830d7db49ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":463,
                  "y":219},
                "size":{
                  "width":33,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u90.png"}},
{
          "id":"746c5c0be2ee49fe90f43161b5dc0db3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":414,
              "y":227},
            "size":{
              "width":9,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3450ab73e12f461996e5b52cfbedd399",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":414,
                  "y":227},
                "size":{
                  "width":9,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e82247cb3c35480ba1d75eb7d608d2a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":281},
            "size":{
              "width":247,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单_图文信息/u94_line.png"}},
{
          "id":"9558b148805c4b96b36ca48f12cd10e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":510,
              "y":287},
            "size":{
              "width":77,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54b782e42b014aefb495b44228fe67e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":510,
                  "y":287},
                "size":{
                  "width":77,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u76.png"}},
{
          "id":"b44cca6cbf224a61bb09e4237f2c59cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":601,
              "y":297},
            "size":{
              "width":79,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7acc38d79913432ea82dfc0515e736aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":601,
                  "y":297},
                "size":{
                  "width":79,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b7d389c445340a99143507ecf2932c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":463,
              "y":305},
            "size":{
              "width":33,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"161da444df8c4f8fa21fc85c68ed5c26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":463,
                  "y":305},
                "size":{
                  "width":33,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u90.png"}},
{
          "id":"f214b2e73bbe4ee990c1868487836bf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":510,
              "y":371},
            "size":{
              "width":77,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57101af24a7144a8b66cf8eb72c19d94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":510,
                  "y":371},
                "size":{
                  "width":77,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u76.png"}},
{
          "id":"232f905a7e6f42a598e7d6a261f158b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":601,
              "y":381},
            "size":{
              "width":71,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0ac9d14503045378ac28e79a317e40a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":601,
                  "y":381},
                "size":{
                  "width":71,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"432ca25ce1b24180b4265eeab1414010",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":463,
              "y":389},
            "size":{
              "width":33,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3f6f500305f4fb1a17b74f45c19a168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":463,
                  "y":389},
                "size":{
                  "width":33,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u90.png"}},
{
          "id":"63787e9a74cb4cd1ae1af58a00902791",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":209,
              "y":121},
            "size":{
              "width":31,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84645e68ac9847cca3819a09c22f13ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":209,
                  "y":121},
                "size":{
                  "width":31,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u107.png"}},
{
          "id":"58f23f760888463aa92f55f3bfaff0fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1125,
              "y":409},
            "size":{
              "width":21,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5c78353fdc0471996e29f5dcd381394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1125,
                  "y":409},
                "size":{
                  "width":21,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u109.png"}},
{
          "id":"557105b70a91411b8f205e3e1cc49a07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1132,
              "y":411},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42be8877f8c7416e90085b1442ce8ad1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1132,
                  "y":411},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40915c4517ef4950a5353c05f31445a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1125,
              "y":473},
            "size":{
              "width":21,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86d1f3fd75e348e08bde0bea0fe3b9b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1125,
                  "y":473},
                "size":{
                  "width":21,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u109.png"}},
{
          "id":"978efe38e3524140a7a104352556af32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1132,
              "y":475},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4015f19743ab4358bb93616f6fdb57e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1132,
                  "y":475},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7999572efd4244428e4fe8de0e024cd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1125,
              "y":211},
            "size":{
              "width":21,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56a09d96039f4c4da0e3e9c4a5eda1e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1125,
                  "y":211},
                "size":{
                  "width":21,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加菜单_图文信息/u109.png"}},
{
          "id":"502f387520c446279b9ee975a7d429e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1132,
              "y":213},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f53b7784af74f65b3c08fd0214fb5b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1132,
                  "y":213},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff41ae9413984b16885a62709f21479b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1123,
              "y":-2},
            "size":{
              "width":10,
              "height":43},
            "rotation":"40",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单_图文信息/u69_line.png"}},
{
          "id":"5e356feb1b1a4c72b15443ded604c574",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1123,
              "y":-2},
            "size":{
              "width":10,
              "height":43},
            "rotation":"320",
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单_图文信息/u69_line.png"}},
{
          "id":"5fc59252ab6f463ca0d41fa4066d7c09",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":73},
            "size":{
              "width":1011,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加菜单_图文信息/u71_line.png"}},
{
          "id":"7316c4007f3946f3ac4aa2677f2e9284",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":594,
              "y":14},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6afa3ec92ac4b7e977e0af42697bd78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":594,
                  "y":14},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ec0525575fbf4948a5c6e24f4fe5e988":{
      "scriptId":"u0"},
    "132cabc758b449988d9eef86808b34b9":{
      "scriptId":"u1"},
    "fa32bd1079e54d83af5fce8b5be330d9":{
      "scriptId":"u2"},
    "a8197ece904846a6b24b20b5205c63ac":{
      "scriptId":"u3"},
    "fccb176a3d474021a8b3501322e1761c":{
      "scriptId":"u4"},
    "b1211da00254497c9747695dc06e4c27":{
      "scriptId":"u5"},
    "b95effcf4535423e85ecdd965f2f2107":{
      "scriptId":"u6"},
    "6e5c564045714b91990586270ab54cc4":{
      "scriptId":"u7"},
    "5484633ed85b48eab1d7a496b41431c8":{
      "scriptId":"u8"},
    "9e6db97d110f4f189eb28b8161832f67":{
      "scriptId":"u9"},
    "081ceded34f246589d94e56063fdad82":{
      "scriptId":"u10"},
    "ab193a5c6b2b4e85a3a37bbbcfa84f24":{
      "scriptId":"u11"},
    "91e3e8eb919c4b55bb2e7e96a30c96e8":{
      "scriptId":"u12"},
    "0c9253a1860943de9db77ae1339d939b":{
      "scriptId":"u13"},
    "2e4cfaf7b34f4f34ba40d9e21d41cac2":{
      "scriptId":"u14"},
    "2924771d93f1443ca880132cc7520422":{
      "scriptId":"u15"},
    "743955fd4de548e2818e04b65aa62d87":{
      "scriptId":"u16"},
    "1823759225cf40558f1d2fbf2d9d3872":{
      "scriptId":"u17"},
    "513c1ac3ede54298b17cdd97984465fd":{
      "scriptId":"u18"},
    "65cdc9b832c24ec58c251f61a0ae9566":{
      "scriptId":"u19"},
    "6329daf01b7d44079075a8fa12f55aaa":{
      "scriptId":"u20"},
    "19abbcb6aa9745a5bb5e3567604d5121":{
      "scriptId":"u21"},
    "813cc8c12f3944a5ba6e40122bd419aa":{
      "scriptId":"u22"},
    "3aa49264a1a04b0e82bbd2853fd1378b":{
      "scriptId":"u23"},
    "a36ea909b9ef4fde8a3c4d6632dad7a1":{
      "scriptId":"u24"},
    "f6bac8103dec4bfb890f7157f33010b0":{
      "scriptId":"u25"},
    "7574aa9fa65846b9adf61d050db56601":{
      "scriptId":"u26"},
    "2ab259ae954842aeb1add0abc1f81200":{
      "scriptId":"u27"},
    "0ed6fff5139545a3b8ceb138926f3cf1":{
      "scriptId":"u28"},
    "ff1d16b40e9b4988a7b51719fe9106f7":{
      "scriptId":"u29"},
    "75d21d075a9740a38ba9cba8d69d4e05":{
      "scriptId":"u30"},
    "59ea00945631467b873c3798119a95b3":{
      "scriptId":"u31"},
    "6089a792837a4e428857476d7e322454":{
      "scriptId":"u32"},
    "dfcbf275b7074bb7a67f0b96a4e1d912":{
      "scriptId":"u33"},
    "e1772fa658284adfb1fba09e42cd5ae2":{
      "scriptId":"u34"},
    "f02732d2e6fa425bad348a3d93466cf0":{
      "scriptId":"u35"},
    "084638aa427245c9b5e283d6a35b4fc9":{
      "scriptId":"u36"},
    "4b62ec82cba941fba817fc338b7fb2d8":{
      "scriptId":"u37"},
    "1dab1197d0404a13883132ee9cd1ba5b":{
      "scriptId":"u38"},
    "019fe4228fbf4f9fb4c883d7ab1403d3":{
      "scriptId":"u39"},
    "cee069d95ba64a3bbf241aa8dcb9043a":{
      "scriptId":"u40"},
    "1d6a64189b9e4baa958f046741fcdb32":{
      "scriptId":"u41"},
    "d89e4ae3720242889950b47804ce8fa9":{
      "scriptId":"u42"},
    "4fe1bfba8eb640278f88dd360951828d":{
      "scriptId":"u43"},
    "97701f831f644e119fe36fc6b178df08":{
      "scriptId":"u44"},
    "35e8406be409419ca16a44b4f878bb5d":{
      "scriptId":"u45"},
    "ee883e78b5ae4b289099eba1ea80c5ef":{
      "scriptId":"u46"},
    "331bb851b0be4c3e9317d4c919fcb86e":{
      "scriptId":"u47"},
    "151d25fdaf66415c96badf2aca00e735":{
      "scriptId":"u48"},
    "b2e2fa5cff0548cba9d6f96d9c382486":{
      "scriptId":"u49"},
    "afa8459612a94fb887d1a6e64a172845":{
      "scriptId":"u50"},
    "778fefbb64bb470c8f05831f70e8a819":{
      "scriptId":"u51"},
    "c2cdb14737b145af82cb7f062d505030":{
      "scriptId":"u52"},
    "7d2ec4e4f8274f40a9c608de4741d7f8":{
      "scriptId":"u53"},
    "ac18d37fd487435583745b2e90fe13a3":{
      "scriptId":"u54"},
    "5851c5c58f4b45fb9a962dcc96c003ed":{
      "scriptId":"u55"},
    "3c4de90f78df4fda8b26b2de22cc2c29":{
      "scriptId":"u56"},
    "29d7ee6cb4c14be3b39604a7a0da7baa":{
      "scriptId":"u57"},
    "555c0529b69d42dfbfb42b77c21e0c1c":{
      "scriptId":"u58"},
    "a8726ecece8e4ce58b2ee9947e621365":{
      "scriptId":"u59"},
    "d92c17fde52d4254b27d47913a60e132":{
      "scriptId":"u60"},
    "1cfe637a61ff460988b6cdf324f1b3a7":{
      "scriptId":"u61"},
    "1dd356e5bd844cae983fe7b17d69c8dc":{
      "scriptId":"u62"},
    "002d8bdcb14b48188b5214fdb4a6151d":{
      "scriptId":"u63"},
    "171caa2c250245fabeda4fa32d52148b":{
      "scriptId":"u64"},
    "95822095778345818f035ae3429badc5":{
      "scriptId":"u65"},
    "2c59a466bef747f99d0170fb22616e1f":{
      "scriptId":"u66"},
    "7e06a727f2c349979cf65a86135846ea":{
      "scriptId":"u67"},
    "868c8c41704e47a68412e9bd01b6c2b4":{
      "scriptId":"u68"},
    "aa3d3aa3d686456d8f6f5939b3839356":{
      "scriptId":"u69"},
    "34b2b055f91849f4b561571228782e7d":{
      "scriptId":"u70"},
    "775de5463b3c484e8f6f682df51540ea":{
      "scriptId":"u71"},
    "e321b096b340419f8754c3f4187396f7":{
      "scriptId":"u72"},
    "a258cc1c99dd46bcaf2ace917cbc79e9":{
      "scriptId":"u73"},
    "05e609745f7941168f10bf8a6d390020":{
      "scriptId":"u74"},
    "cfb0dc15a2aa48f68643328ba769aca5":{
      "scriptId":"u75"},
    "469e390efdae4b57a00062e236b91fe5":{
      "scriptId":"u76"},
    "20277a2784364ec6aaecb830d7db49ae":{
      "scriptId":"u77"},
    "746c5c0be2ee49fe90f43161b5dc0db3":{
      "scriptId":"u78"},
    "3450ab73e12f461996e5b52cfbedd399":{
      "scriptId":"u79"},
    "e82247cb3c35480ba1d75eb7d608d2a8":{
      "scriptId":"u80"},
    "9558b148805c4b96b36ca48f12cd10e7":{
      "scriptId":"u81"},
    "54b782e42b014aefb495b44228fe67e0":{
      "scriptId":"u82"},
    "b44cca6cbf224a61bb09e4237f2c59cd":{
      "scriptId":"u83"},
    "7acc38d79913432ea82dfc0515e736aa":{
      "scriptId":"u84"},
    "2b7d389c445340a99143507ecf2932c8":{
      "scriptId":"u85"},
    "161da444df8c4f8fa21fc85c68ed5c26":{
      "scriptId":"u86"},
    "f214b2e73bbe4ee990c1868487836bf8":{
      "scriptId":"u87"},
    "57101af24a7144a8b66cf8eb72c19d94":{
      "scriptId":"u88"},
    "232f905a7e6f42a598e7d6a261f158b3":{
      "scriptId":"u89"},
    "d0ac9d14503045378ac28e79a317e40a":{
      "scriptId":"u90"},
    "432ca25ce1b24180b4265eeab1414010":{
      "scriptId":"u91"},
    "a3f6f500305f4fb1a17b74f45c19a168":{
      "scriptId":"u92"},
    "63787e9a74cb4cd1ae1af58a00902791":{
      "scriptId":"u93"},
    "84645e68ac9847cca3819a09c22f13ff":{
      "scriptId":"u94"},
    "58f23f760888463aa92f55f3bfaff0fc":{
      "scriptId":"u95"},
    "a5c78353fdc0471996e29f5dcd381394":{
      "scriptId":"u96"},
    "557105b70a91411b8f205e3e1cc49a07":{
      "scriptId":"u97"},
    "42be8877f8c7416e90085b1442ce8ad1":{
      "scriptId":"u98"},
    "40915c4517ef4950a5353c05f31445a4":{
      "scriptId":"u99"},
    "86d1f3fd75e348e08bde0bea0fe3b9b5":{
      "scriptId":"u100"},
    "978efe38e3524140a7a104352556af32":{
      "scriptId":"u101"},
    "4015f19743ab4358bb93616f6fdb57e5":{
      "scriptId":"u102"},
    "7999572efd4244428e4fe8de0e024cd8":{
      "scriptId":"u103"},
    "56a09d96039f4c4da0e3e9c4a5eda1e3":{
      "scriptId":"u104"},
    "502f387520c446279b9ee975a7d429e1":{
      "scriptId":"u105"},
    "1f53b7784af74f65b3c08fd0214fb5b1":{
      "scriptId":"u106"},
    "ff41ae9413984b16885a62709f21479b":{
      "scriptId":"u107"},
    "5e356feb1b1a4c72b15443ded604c574":{
      "scriptId":"u108"},
    "5fc59252ab6f463ca0d41fa4066d7c09":{
      "scriptId":"u109"},
    "7316c4007f3946f3ac4aa2677f2e9284":{
      "scriptId":"u110"},
    "b6afa3ec92ac4b7e977e0af42697bd78":{
      "scriptId":"u111"}}});