$axure.loadCurrentPage({
  "url":"二维码列表.html",
  "generationDate":new Date(1448257224872.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"09e99507c7e2466da9ac45e1e9917e42",
    "type":"Axure:Page",
    "name":"二维码列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b9c5b096d3374f22a8d6afdd5cdc3253",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "size":{
              "width":1310,
              "height":910}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34f9f85b18964132bc86394ae9b52662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "size":{
                  "width":1310,
                  "height":910}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/配置二维码/u0.png"}},
{
          "id":"6780340be1e44e698574384d6f7c4d79",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2e195556ff284305b8fba021caa72779"},
{
          "id":"b3189faec1bc44a6852ce5a80cfd49be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3FB889,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":128,
              "y":204},
            "size":{
              "width":90,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"399d3a61b90e47bfbf406420f3bfbbd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3FB889,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":128,
                  "y":204},
                "size":{
                  "width":90,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/配置二维码/u9.png"}},
{
          "id":"69f632de6eca48dd9bfdde4f6847e82a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":234,
              "y":139},
            "size":{
              "width":197,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"978980cd3a434e08a00b167f608f6f3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":234,
                  "y":139},
                "size":{
                  "width":197,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/列表页/u231.png"}},
{
          "id":"fc18519132be40fba529c1876ec5547d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":240,
              "y":150},
            "size":{
              "width":170,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7162892b35344cadae0b78be415a29ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":150},
                "size":{
                  "width":170,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93eb40c1e4184b98bc72f62f814418fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":470,
              "y":139},
            "size":{
              "width":70,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9422e9bc3604ffdaca2c7647d99f6f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":139},
                "size":{
                  "width":70,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/列表页/u241.png"}},
{
          "id":"a436f689ad3e4f27804969c10c80ccf6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":121},
            "size":{
              "width":1087,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/列表页/u9_line.png"}},
{
          "id":"0f782cde76e6495a9934ea119f376c07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":220,
              "y":80},
            "size":{
              "width":1074,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebd427fe49e640c6b3b8b520a4dfe757",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":220,
                  "y":80},
                "size":{
                  "width":1074,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/列表页/u243.png"}},
{
          "id":"e0a6d5795a8f48eaa136de9cd3b6e811",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF56338,
              "opacity":1},
            "location":{
              "x":317,
              "y":92},
            "size":{
              "width":76,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf6776a0c4a542dfadcf944488b2073c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF56338,
                  "opacity":1},
                "location":{
                  "x":317,
                  "y":92},
                "size":{
                  "width":76,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b92f335a3584d8fbdde5915549dbaae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":239,
              "y":93},
            "size":{
              "width":50,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bd1dba49a6949ce876a28ad7a467e9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":239,
                  "y":93},
                "size":{
                  "width":50,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c70c877097f74a55aff741be675b3872",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":429,
              "y":92},
            "size":{
              "width":50,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58bd404e8c134a87b15024658c08714e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":92},
                "size":{
                  "width":50,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e8bc465c3bc485aab85167b172d19d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":299,
              "y":96},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1ffebd4154b497e8970ddadb2ee10ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":299,
                  "y":96},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"c3e5ac860bac4b1ebcfba570bc453c6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":304,
              "y":96},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"217a3fa85e974a84ad2fad0d38115340",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":304,
                  "y":96},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"3d6eb0ec78b04749af325271b6d76ce6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":299,
              "y":105},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9e376e408974049b265138044f5eceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":299,
                  "y":105},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"a27e74b861bc4b09a905af3aa4ab32b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":304,
              "y":105},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d0a91982ab84b9d8e4a2b9509446317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":304,
                  "y":105},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"7460fc33da4b4870a950e2bf73bae11b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":393,
              "y":96},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0e62bb5fb8948a49b7b52d4d7f24e9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":393,
                  "y":96},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"59b7a2759fce4b6eb3f68830c9ef1172",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":398,
              "y":96},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"203c59c954bc41bdbd31928e1d5fbe97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":398,
                  "y":96},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"233c2092633c491bb823bb801317c070",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":393,
              "y":105},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ccc4052b74f461f96fd6230d2265ac8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":393,
                  "y":105},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"e228a6b7d9fb4352aae813a564ea268c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":398,
              "y":105},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9c7695c30bf4c87a7cdf9279e75f866",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":398,
                  "y":105},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"7fa2df2ce81a456a9a1ea35fa187ed63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1224,
              "y":92},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dacb3a5d6a8c4fee88bfa48a8646f89f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1224,
                  "y":92},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b46e89b27a5d4cf6acaa7dd46632eb42",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":1189,
              "y":87},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53850b202de347059cc21a28c8c1d9b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":1189,
                  "y":87},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/列表页/u269.png"}},
{
          "id":"cdd6473b406a41f6a859a4906d225dd9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":507,
              "y":790},
            "size":{
              "width":553,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14e48abef77e47c9843105f5651d7808",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":507,
                  "y":790},
                "size":{
                  "width":553,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/列表页/u289.png"}},
{
          "id":"218c841de2634e4e9eb0af53a4ad70c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":239,
              "y":349},
            "size":{
              "width":150,
              "height":71},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0787fcd4e744a24a92038375a4a6af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":239,
                  "y":349},
                "size":{
                  "width":150,
                  "height":71},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u48.png"}},
{
          "id":"747a58ef298d43aeb1e085695b674a20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":239,
              "y":201},
            "size":{
              "width":150,
              "height":150},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb1a7639cf8544f1aced70460984178e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":239,
                  "y":201},
                "size":{
                  "width":150,
                  "height":150},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u50.png"}},
{
          "id":"98262f75d0904c1b959775aa330c299a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "location":{
              "x":458,
              "y":349},
            "size":{
              "width":150,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"409a9be72ac244159172e716c1258c1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "location":{
                  "x":458,
                  "y":349},
                "size":{
                  "width":150,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u52.png"}},
{
          "id":"7e2318359cd94e3f82c90a26ee9d5f7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "location":{
              "x":677,
              "y":349},
            "size":{
              "width":150,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"423f92d875734f93a0d4b492800bd184",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "location":{
                  "x":677,
                  "y":349},
                "size":{
                  "width":150,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u52.png"}},
{
          "id":"31587422e74646c897e1b837bec29781",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "location":{
              "x":896,
              "y":349},
            "size":{
              "width":150,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a7b7f68048f491dbdc06c59c6b8177f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "location":{
                  "x":896,
                  "y":349},
                "size":{
                  "width":150,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u52.png"}},
{
          "id":"acb95f1969a8499b985b61cee20b53cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "location":{
              "x":1115,
              "y":348},
            "size":{
              "width":150,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b99bd1f42f846ac9349380a94db9e54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "location":{
                  "x":1115,
                  "y":348},
                "size":{
                  "width":150,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u52.png"}},
{
          "id":"ee73f8d74aea4728a3b659b2f97a52b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":677,
              "y":201},
            "size":{
              "width":150,
              "height":150},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aef051618e24abd951d022277838ac7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":677,
                  "y":201},
                "size":{
                  "width":150,
                  "height":150},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u60.png"}},
{
          "id":"7efd4297c7444a308d1ffe11c96bb038",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":896,
              "y":201},
            "size":{
              "width":150,
              "height":150},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65203b44d065489289bfe96635d81d9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":896,
                  "y":201},
                "size":{
                  "width":150,
                  "height":150},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u60.png"}},
{
          "id":"c269eb812f124b2b9fe060a804f0990c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":1115,
              "y":200},
            "size":{
              "width":150,
              "height":150},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3723dc92b93c4a568ce48c3a562abf38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":1115,
                  "y":200},
                "size":{
                  "width":150,
                  "height":150},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u60.png"}},
{
          "id":"1ac5ba051a614bb2945a978555cc9bf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":458,
              "y":201},
            "size":{
              "width":150,
              "height":150},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aecf4664ce35461db127f26e49316c65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":458,
                  "y":201},
                "size":{
                  "width":150,
                  "height":150},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u60.png"}},
{
          "id":"15a34c1891a14cd3b1110561abba41a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":677,
              "y":351},
            "size":{
              "width":150,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27edc4acc00447b68e01e87c8b78870a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":677,
                  "y":351},
                "size":{
                  "width":150,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u68.png"}},
{
          "id":"967d5e3a8af7436db46e0c77437688a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":686,
              "y":370},
            "size":{
              "width":64,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"874b8286858340f38272e6ae8f9db6c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":686,
                  "y":370},
                "size":{
                  "width":64,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u70.png"}},
{
          "id":"5311cbb8fc424ef396e08a0b227677cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":760,
              "y":370},
            "size":{
              "width":64,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67eb42a133a1482cbe1164c1a52892ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":760,
                  "y":370},
                "size":{
                  "width":64,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/二维码列表/u70.png"}}]}},
  "masters":{
    "2e195556ff284305b8fba021caa72779":{
      "packageId":"2e195556ff284305b8fba021caa72779",
      "type":"Axure:Master",
      "name":"底板",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ece2a5eef46646caa0096a3923498bc1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1190,
                "height":908}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7df3c110fa3408f99e7f977b2d31ffc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1190,
                    "height":908}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首次进入时--引导页/u1.png"}},
{
            "id":"2b5c70957a4b4b08aa86166895ce55ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":220,
                "y":80},
              "size":{
                "width":970,
                "height":828},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"254640c021b2481d8feede958aa82cf2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":220,
                    "y":80},
                  "size":{
                    "width":970,
                    "height":828},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首次进入时--引导页/u3.png"}},
{
            "id":"56662ee06a954f4f9d1020d8c3df155c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":1040,
                "y":49},
              "size":{
                "width":150,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1553942915bc4c4a98ac88b8eef8516a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1040,
                    "y":49},
                  "size":{
                    "width":150,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首次进入时--引导页/u5.png"}}]}}},
  "objectPaths":{
    "b9c5b096d3374f22a8d6afdd5cdc3253":{
      "scriptId":"u0"},
    "34f9f85b18964132bc86394ae9b52662":{
      "scriptId":"u1"},
    "6780340be1e44e698574384d6f7c4d79":{
      "scriptId":"u2",
      "ece2a5eef46646caa0096a3923498bc1":{
        "scriptId":"u3"},
      "c7df3c110fa3408f99e7f977b2d31ffc":{
        "scriptId":"u4"},
      "2b5c70957a4b4b08aa86166895ce55ec":{
        "scriptId":"u5"},
      "254640c021b2481d8feede958aa82cf2":{
        "scriptId":"u6"},
      "56662ee06a954f4f9d1020d8c3df155c":{
        "scriptId":"u7"},
      "1553942915bc4c4a98ac88b8eef8516a":{
        "scriptId":"u8"}},
    "b3189faec1bc44a6852ce5a80cfd49be":{
      "scriptId":"u9"},
    "399d3a61b90e47bfbf406420f3bfbbd5":{
      "scriptId":"u10"},
    "69f632de6eca48dd9bfdde4f6847e82a":{
      "scriptId":"u11"},
    "978980cd3a434e08a00b167f608f6f3f":{
      "scriptId":"u12"},
    "fc18519132be40fba529c1876ec5547d":{
      "scriptId":"u13"},
    "7162892b35344cadae0b78be415a29ac":{
      "scriptId":"u14"},
    "93eb40c1e4184b98bc72f62f814418fa":{
      "scriptId":"u15"},
    "a9422e9bc3604ffdaca2c7647d99f6f7":{
      "scriptId":"u16"},
    "a436f689ad3e4f27804969c10c80ccf6":{
      "scriptId":"u17"},
    "0f782cde76e6495a9934ea119f376c07":{
      "scriptId":"u18"},
    "ebd427fe49e640c6b3b8b520a4dfe757":{
      "scriptId":"u19"},
    "e0a6d5795a8f48eaa136de9cd3b6e811":{
      "scriptId":"u20"},
    "cf6776a0c4a542dfadcf944488b2073c":{
      "scriptId":"u21"},
    "3b92f335a3584d8fbdde5915549dbaae":{
      "scriptId":"u22"},
    "7bd1dba49a6949ce876a28ad7a467e9f":{
      "scriptId":"u23"},
    "c70c877097f74a55aff741be675b3872":{
      "scriptId":"u24"},
    "58bd404e8c134a87b15024658c08714e":{
      "scriptId":"u25"},
    "2e8bc465c3bc485aab85167b172d19d9":{
      "scriptId":"u26"},
    "c1ffebd4154b497e8970ddadb2ee10ec":{
      "scriptId":"u27"},
    "c3e5ac860bac4b1ebcfba570bc453c6f":{
      "scriptId":"u28"},
    "217a3fa85e974a84ad2fad0d38115340":{
      "scriptId":"u29"},
    "3d6eb0ec78b04749af325271b6d76ce6":{
      "scriptId":"u30"},
    "a9e376e408974049b265138044f5eceb":{
      "scriptId":"u31"},
    "a27e74b861bc4b09a905af3aa4ab32b3":{
      "scriptId":"u32"},
    "1d0a91982ab84b9d8e4a2b9509446317":{
      "scriptId":"u33"},
    "7460fc33da4b4870a950e2bf73bae11b":{
      "scriptId":"u34"},
    "d0e62bb5fb8948a49b7b52d4d7f24e9f":{
      "scriptId":"u35"},
    "59b7a2759fce4b6eb3f68830c9ef1172":{
      "scriptId":"u36"},
    "203c59c954bc41bdbd31928e1d5fbe97":{
      "scriptId":"u37"},
    "233c2092633c491bb823bb801317c070":{
      "scriptId":"u38"},
    "7ccc4052b74f461f96fd6230d2265ac8":{
      "scriptId":"u39"},
    "e228a6b7d9fb4352aae813a564ea268c":{
      "scriptId":"u40"},
    "d9c7695c30bf4c87a7cdf9279e75f866":{
      "scriptId":"u41"},
    "7fa2df2ce81a456a9a1ea35fa187ed63":{
      "scriptId":"u42"},
    "dacb3a5d6a8c4fee88bfa48a8646f89f":{
      "scriptId":"u43"},
    "b46e89b27a5d4cf6acaa7dd46632eb42":{
      "scriptId":"u44"},
    "53850b202de347059cc21a28c8c1d9b4":{
      "scriptId":"u45"},
    "cdd6473b406a41f6a859a4906d225dd9":{
      "scriptId":"u46"},
    "14e48abef77e47c9843105f5651d7808":{
      "scriptId":"u47"},
    "218c841de2634e4e9eb0af53a4ad70c0":{
      "scriptId":"u48"},
    "e0787fcd4e744a24a92038375a4a6af4":{
      "scriptId":"u49"},
    "747a58ef298d43aeb1e085695b674a20":{
      "scriptId":"u50"},
    "bb1a7639cf8544f1aced70460984178e":{
      "scriptId":"u51"},
    "98262f75d0904c1b959775aa330c299a":{
      "scriptId":"u52"},
    "409a9be72ac244159172e716c1258c1d":{
      "scriptId":"u53"},
    "7e2318359cd94e3f82c90a26ee9d5f7e":{
      "scriptId":"u54"},
    "423f92d875734f93a0d4b492800bd184":{
      "scriptId":"u55"},
    "31587422e74646c897e1b837bec29781":{
      "scriptId":"u56"},
    "1a7b7f68048f491dbdc06c59c6b8177f":{
      "scriptId":"u57"},
    "acb95f1969a8499b985b61cee20b53cd":{
      "scriptId":"u58"},
    "3b99bd1f42f846ac9349380a94db9e54":{
      "scriptId":"u59"},
    "ee73f8d74aea4728a3b659b2f97a52b3":{
      "scriptId":"u60"},
    "3aef051618e24abd951d022277838ac7":{
      "scriptId":"u61"},
    "7efd4297c7444a308d1ffe11c96bb038":{
      "scriptId":"u62"},
    "65203b44d065489289bfe96635d81d9b":{
      "scriptId":"u63"},
    "c269eb812f124b2b9fe060a804f0990c":{
      "scriptId":"u64"},
    "3723dc92b93c4a568ce48c3a562abf38":{
      "scriptId":"u65"},
    "1ac5ba051a614bb2945a978555cc9bf6":{
      "scriptId":"u66"},
    "aecf4664ce35461db127f26e49316c65":{
      "scriptId":"u67"},
    "15a34c1891a14cd3b1110561abba41a1":{
      "scriptId":"u68"},
    "27edc4acc00447b68e01e87c8b78870a":{
      "scriptId":"u69"},
    "967d5e3a8af7436db46e0c77437688a7":{
      "scriptId":"u70"},
    "874b8286858340f38272e6ae8f9db6c2":{
      "scriptId":"u71"},
    "5311cbb8fc424ef396e08a0b227677cd":{
      "scriptId":"u72"},
    "67eb42a133a1482cbe1164c1a52892ba":{
      "scriptId":"u73"}}});