$axure.loadCurrentPage({
  "url":"概览.html",
  "generationDate":new Date(1448257274912.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"02bb0a69f0c44b4ca50db4f83f9af70f",
    "type":"Axure:Page",
    "name":"概览",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8f842aadc9ef4a629abb9a044870b0cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":0},
            "size":{
              "width":1310,
              "height":915}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4975285cefe3454ca402c90e29a4b737",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":0},
                "size":{
                  "width":1310,
                  "height":915}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/概览/u0.png"}},
{
          "id":"1a80d57093504c70959830113f2efd62",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":6}},
          "adaptiveStyles":{
},
          "masterId":"2e195556ff284305b8fba021caa72779"},
{
          "id":"de072d5ba20f4feca9af3b199dfe20d3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":125},
            "size":{
              "width":1087,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/列表页/u9_line.png"}},
{
          "id":"cb1c4033e1b94ae1956dbb73d6849816",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":221,
              "y":84},
            "size":{
              "width":1074,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"131416740a8c49849359e7e7b4cefb24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":221,
                  "y":84},
                "size":{
                  "width":1074,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卡券统计/u10.png"}},
{
          "id":"01d4e428fe664ccf82c44a8d7d5440c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":328,
              "y":96},
            "size":{
              "width":56,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"261323a48e5c4d6ea327360ab7d69b9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":96},
                "size":{
                  "width":56,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5463f8fb3df946419dc8310548de5ba7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":245,
              "y":96},
            "size":{
              "width":50,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f5d07141ff340738645f7b11aa61284",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":245,
                  "y":96},
                "size":{
                  "width":50,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7bfb5628aa74b87909673fe59c94be7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":430,
              "y":96},
            "size":{
              "width":50,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"967be5b88b2f4c78bbc237db4a385f21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":430,
                  "y":96},
                "size":{
                  "width":50,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc4a897a24444b9d88875513627dbc41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":300,
              "y":100},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f53cf5e1757416a919541b155af4be8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":300,
                  "y":100},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"c569ca1d914549a99e912eb66332800f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":305,
              "y":100},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfddc1c7378149fb9908ebf425b770d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":305,
                  "y":100},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"7a189af7821c44618a098b7c3c92d6d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":300,
              "y":109},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e6fbba471fa4b59af5dbe1b052dddd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":300,
                  "y":109},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"f27f7787481a4bcf8503b8cef5a2460e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":305,
              "y":109},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c38975ff2354abfb1e64f94d4706f3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":305,
                  "y":109},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"28160d6a0dff4e6c8fee349e4901871a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":394,
              "y":100},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20947bdc299540a8a99b6083e3a3592b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":394,
                  "y":100},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"636f5589c0974783b29c1aaafae3edd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":399,
              "y":100},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84bc0b8b0b444c43acc5e63c05b59879",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":399,
                  "y":100},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"f3f379926a814a008db1c0c10313aea2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":394,
              "y":109},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6835c5a861a4a66841a52bca9d313c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":394,
                  "y":109},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"515fc18f631e4cc1906a204a8555c468",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":399,
              "y":109},
            "size":{
              "width":3,
              "height":3},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bba19aa06ce48789be9edb025c0bf37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":399,
                  "y":109},
                "size":{
                  "width":3,
                  "height":3},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首次进入时--引导页/u16.png"}},
{
          "id":"2b073defdbe6431a93ae915641c8c35c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":228,
              "y":142},
            "size":{
              "width":1067,
              "height":222},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7773ffc2bcb84216bff8a67d32bb7683",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":228,
                  "y":142},
                "size":{
                  "width":1067,
                  "height":222},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/概览/u34.png"}},
{
          "id":"e3eb650de71249bf9ee9a753a6218d28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":238,
              "y":259},
            "size":{
              "width":300,
              "height":88},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46d59dd0bf9948c78c39fd4bb8e25240",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":238,
                  "y":259},
                "size":{
                  "width":300,
                  "height":88},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/概览/u36.png"}},
{
          "id":"3c1fb624d87a46ada8e2422743f2d754",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":400,
              "y":296},
            "size":{
              "width":34,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d8ef641d7bc468f9bec405e845e46d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":400,
                  "y":296},
                "size":{
                  "width":34,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3443c732bf03459aafe6170ae2ffe0ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":254,
              "y":273},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02452cbe46e3498c872ac9b6738eb9e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":254,
                  "y":273},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a8b3047d9464738974117726c522a0f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":253},
            "size":{
              "width":300,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66CC00}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/概览/u42_line.png"}},
{
          "id":"77a6b4b311e447e4a10d5f5cb4242085",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":610,
              "y":260},
            "size":{
              "width":300,
              "height":88},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22d0ed21f12248919aa048f79079a856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":610,
                  "y":260},
                "size":{
                  "width":300,
                  "height":88},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/概览/u36.png"}},
{
          "id":"def84cacfc344c1bb98dcb7d02e745c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":772,
              "y":297},
            "size":{
              "width":34,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d530a1bb12649fb923f4da26342ff8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":772,
                  "y":297},
                "size":{
                  "width":34,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37856616f7f549a5a7f2269b6c0b680e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":626,
              "y":270},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dc9c98e6765473d92cb235c872d7031",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":626,
                  "y":270},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c31cb6d4e7af4aad8ba5c1623111ec67",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":254},
            "size":{
              "width":300,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/概览/u49_line.png"}},
{
          "id":"6ddb94a3b8f9402f9e4f537ec1daa1b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":968,
              "y":261},
            "size":{
              "width":300,
              "height":88},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78e313f27b10455bb6a54ab3912e4765",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":968,
                  "y":261},
                "size":{
                  "width":300,
                  "height":88},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/概览/u36.png"}},
{
          "id":"cab846abe2bc4f23b705c225dcde8d30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":1150,
              "y":299},
            "size":{
              "width":34,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3f35a4d994e47c4b581f93371e5a829",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":1150,
                  "y":299},
                "size":{
                  "width":34,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96f3af576fae4946a82c5bf3037499ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":998,
              "y":273},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c73ac759b2d94fcbb63003d4ba995674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":998,
                  "y":273},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d85b3392352d461f844b53ca37d94867",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":257},
            "size":{
              "width":300,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66CC00}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/概览/u42_line.png"}},
{
          "id":"8a6179013b9e471fb011524d2c3daa06",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":951,
              "y":193},
            "size":{
              "width":100,
              "height":39}},
          "adaptiveStyles":{
}},
{
          "id":"dacae1d77cb6412e90f6c83b45cbafd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":242,
              "y":193},
            "size":{
              "width":120,
              "height":40},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7ca0beecd034e0f8627cf656a02fc26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":242,
                  "y":193},
                "size":{
                  "width":120,
                  "height":40},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/概览/u58.png"}},
{
          "id":"4b4d640d838a40779ba829ca2a4e493c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":372,
              "y":193},
            "size":{
              "width":120,
              "height":40},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2a2d27efab845e1a22099fb5f4c1bee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":372,
                  "y":193},
                "size":{
                  "width":120,
                  "height":40},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/概览/u60.png"}},
{
          "id":"d02b811f32dc48dcbb78cc914ad2cc4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":502,
              "y":193},
            "size":{
              "width":120,
              "height":40},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daceb5d964714c23a1621d05146ef35b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":502,
                  "y":193},
                "size":{
                  "width":120,
                  "height":40},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/概览/u60.png"}},
{
          "id":"88387ef3b6da42bf8c643f9efc9b28d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":658,
              "y":201},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1927af794cfe49b883dff4300ee52a90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":658,
                  "y":201},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6f7b56ee79f485bbae1b968a9c888e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":888,
              "y":204},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f9975673a364f82b7fbf69e8c86b16c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":888,
                  "y":204},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"992745f68ad2405aab2d14330890bec1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1198,
              "y":192},
            "size":{
              "width":66,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a4b3ed980d949568900f12c86009a93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1198,
                  "y":192},
                "size":{
                  "width":66,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/概览/u68.png"}},
{
          "id":"5ff733fd70534de5b61d8e3b4f03f2f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF66FFCC},
            "location":{
              "x":228,
              "y":141},
            "size":{
              "width":1067,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7df81917a4a47639fe862a9df090144",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FFCC},
                "location":{
                  "x":228,
                  "y":141},
                "size":{
                  "width":1067,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卡券统计/u263.png"}},
{
          "id":"3c6cdff2dc5a451ab94575fc3d8e0e89",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":231,
              "y":364},
            "size":{
              "width":1064,
              "height":321}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14d49415d99b4ea19eaacfd6530305de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":364},
                "size":{
                  "width":1064,
                  "height":321}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/概览/u72.png"}},
{
          "id":"4d1b6aab8916431f94de29a5b4fc7ebd",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":1081,
              "y":192},
            "size":{
              "width":100,
              "height":39}},
          "adaptiveStyles":{
}},
{
          "id":"39a87ce6e95c42eeb7b1b9e2d6b683d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":1061,
              "y":204},
            "size":{
              "width":14,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c0d3d17b4a64b2db30b0f17a37a164f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":1061,
                  "y":204},
                "size":{
                  "width":14,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"631e4b4d426e447fb7f5563b4f6f64ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":242,
              "y":152},
            "size":{
              "width":27,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"879caa49301f441c8b520d6cf203f30c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":242,
                  "y":152},
                "size":{
                  "width":27,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e503ba36dde24f3c82c7909b04adb104",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":292,
              "y":152},
            "size":{
              "width":27,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d85a4d0477564f9391f602eba699df32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":152},
                "size":{
                  "width":27,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "2e195556ff284305b8fba021caa72779":{
      "packageId":"2e195556ff284305b8fba021caa72779",
      "type":"Axure:Master",
      "name":"底板",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ece2a5eef46646caa0096a3923498bc1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1190,
                "height":908}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7df3c110fa3408f99e7f977b2d31ffc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1190,
                    "height":908}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首次进入时--引导页/u1.png"}},
{
            "id":"2b5c70957a4b4b08aa86166895ce55ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":220,
                "y":80},
              "size":{
                "width":970,
                "height":828},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"254640c021b2481d8feede958aa82cf2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":220,
                    "y":80},
                  "size":{
                    "width":970,
                    "height":828},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首次进入时--引导页/u3.png"}},
{
            "id":"56662ee06a954f4f9d1020d8c3df155c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":1040,
                "y":49},
              "size":{
                "width":150,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1553942915bc4c4a98ac88b8eef8516a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1040,
                    "y":49},
                  "size":{
                    "width":150,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首次进入时--引导页/u5.png"}}]}}},
  "objectPaths":{
    "8f842aadc9ef4a629abb9a044870b0cb":{
      "scriptId":"u0"},
    "4975285cefe3454ca402c90e29a4b737":{
      "scriptId":"u1"},
    "1a80d57093504c70959830113f2efd62":{
      "scriptId":"u2",
      "ece2a5eef46646caa0096a3923498bc1":{
        "scriptId":"u3"},
      "c7df3c110fa3408f99e7f977b2d31ffc":{
        "scriptId":"u4"},
      "2b5c70957a4b4b08aa86166895ce55ec":{
        "scriptId":"u5"},
      "254640c021b2481d8feede958aa82cf2":{
        "scriptId":"u6"},
      "56662ee06a954f4f9d1020d8c3df155c":{
        "scriptId":"u7"},
      "1553942915bc4c4a98ac88b8eef8516a":{
        "scriptId":"u8"}},
    "de072d5ba20f4feca9af3b199dfe20d3":{
      "scriptId":"u9"},
    "cb1c4033e1b94ae1956dbb73d6849816":{
      "scriptId":"u10"},
    "131416740a8c49849359e7e7b4cefb24":{
      "scriptId":"u11"},
    "01d4e428fe664ccf82c44a8d7d5440c5":{
      "scriptId":"u12"},
    "261323a48e5c4d6ea327360ab7d69b9b":{
      "scriptId":"u13"},
    "5463f8fb3df946419dc8310548de5ba7":{
      "scriptId":"u14"},
    "6f5d07141ff340738645f7b11aa61284":{
      "scriptId":"u15"},
    "c7bfb5628aa74b87909673fe59c94be7":{
      "scriptId":"u16"},
    "967be5b88b2f4c78bbc237db4a385f21":{
      "scriptId":"u17"},
    "fc4a897a24444b9d88875513627dbc41":{
      "scriptId":"u18"},
    "1f53cf5e1757416a919541b155af4be8":{
      "scriptId":"u19"},
    "c569ca1d914549a99e912eb66332800f":{
      "scriptId":"u20"},
    "dfddc1c7378149fb9908ebf425b770d3":{
      "scriptId":"u21"},
    "7a189af7821c44618a098b7c3c92d6d9":{
      "scriptId":"u22"},
    "5e6fbba471fa4b59af5dbe1b052dddd4":{
      "scriptId":"u23"},
    "f27f7787481a4bcf8503b8cef5a2460e":{
      "scriptId":"u24"},
    "9c38975ff2354abfb1e64f94d4706f3d":{
      "scriptId":"u25"},
    "28160d6a0dff4e6c8fee349e4901871a":{
      "scriptId":"u26"},
    "20947bdc299540a8a99b6083e3a3592b":{
      "scriptId":"u27"},
    "636f5589c0974783b29c1aaafae3edd7":{
      "scriptId":"u28"},
    "84bc0b8b0b444c43acc5e63c05b59879":{
      "scriptId":"u29"},
    "f3f379926a814a008db1c0c10313aea2":{
      "scriptId":"u30"},
    "a6835c5a861a4a66841a52bca9d313c9":{
      "scriptId":"u31"},
    "515fc18f631e4cc1906a204a8555c468":{
      "scriptId":"u32"},
    "2bba19aa06ce48789be9edb025c0bf37":{
      "scriptId":"u33"},
    "2b073defdbe6431a93ae915641c8c35c":{
      "scriptId":"u34"},
    "7773ffc2bcb84216bff8a67d32bb7683":{
      "scriptId":"u35"},
    "e3eb650de71249bf9ee9a753a6218d28":{
      "scriptId":"u36"},
    "46d59dd0bf9948c78c39fd4bb8e25240":{
      "scriptId":"u37"},
    "3c1fb624d87a46ada8e2422743f2d754":{
      "scriptId":"u38"},
    "9d8ef641d7bc468f9bec405e845e46d5":{
      "scriptId":"u39"},
    "3443c732bf03459aafe6170ae2ffe0ec":{
      "scriptId":"u40"},
    "02452cbe46e3498c872ac9b6738eb9e6":{
      "scriptId":"u41"},
    "7a8b3047d9464738974117726c522a0f":{
      "scriptId":"u42"},
    "77a6b4b311e447e4a10d5f5cb4242085":{
      "scriptId":"u43"},
    "22d0ed21f12248919aa048f79079a856":{
      "scriptId":"u44"},
    "def84cacfc344c1bb98dcb7d02e745c9":{
      "scriptId":"u45"},
    "8d530a1bb12649fb923f4da26342ff8c":{
      "scriptId":"u46"},
    "37856616f7f549a5a7f2269b6c0b680e":{
      "scriptId":"u47"},
    "7dc9c98e6765473d92cb235c872d7031":{
      "scriptId":"u48"},
    "c31cb6d4e7af4aad8ba5c1623111ec67":{
      "scriptId":"u49"},
    "6ddb94a3b8f9402f9e4f537ec1daa1b1":{
      "scriptId":"u50"},
    "78e313f27b10455bb6a54ab3912e4765":{
      "scriptId":"u51"},
    "cab846abe2bc4f23b705c225dcde8d30":{
      "scriptId":"u52"},
    "f3f35a4d994e47c4b581f93371e5a829":{
      "scriptId":"u53"},
    "96f3af576fae4946a82c5bf3037499ab":{
      "scriptId":"u54"},
    "c73ac759b2d94fcbb63003d4ba995674":{
      "scriptId":"u55"},
    "d85b3392352d461f844b53ca37d94867":{
      "scriptId":"u56"},
    "8a6179013b9e471fb011524d2c3daa06":{
      "scriptId":"u57"},
    "dacae1d77cb6412e90f6c83b45cbafd3":{
      "scriptId":"u58"},
    "d7ca0beecd034e0f8627cf656a02fc26":{
      "scriptId":"u59"},
    "4b4d640d838a40779ba829ca2a4e493c":{
      "scriptId":"u60"},
    "b2a2d27efab845e1a22099fb5f4c1bee":{
      "scriptId":"u61"},
    "d02b811f32dc48dcbb78cc914ad2cc4a":{
      "scriptId":"u62"},
    "daceb5d964714c23a1621d05146ef35b":{
      "scriptId":"u63"},
    "88387ef3b6da42bf8c643f9efc9b28d6":{
      "scriptId":"u64"},
    "1927af794cfe49b883dff4300ee52a90":{
      "scriptId":"u65"},
    "a6f7b56ee79f485bbae1b968a9c888e6":{
      "scriptId":"u66"},
    "7f9975673a364f82b7fbf69e8c86b16c":{
      "scriptId":"u67"},
    "992745f68ad2405aab2d14330890bec1":{
      "scriptId":"u68"},
    "6a4b3ed980d949568900f12c86009a93":{
      "scriptId":"u69"},
    "5ff733fd70534de5b61d8e3b4f03f2f0":{
      "scriptId":"u70"},
    "e7df81917a4a47639fe862a9df090144":{
      "scriptId":"u71"},
    "3c6cdff2dc5a451ab94575fc3d8e0e89":{
      "scriptId":"u72"},
    "14d49415d99b4ea19eaacfd6530305de":{
      "scriptId":"u73"},
    "4d1b6aab8916431f94de29a5b4fc7ebd":{
      "scriptId":"u74"},
    "39a87ce6e95c42eeb7b1b9e2d6b683d7":{
      "scriptId":"u75"},
    "7c0d3d17b4a64b2db30b0f17a37a164f":{
      "scriptId":"u76"},
    "631e4b4d426e447fb7f5563b4f6f64ac":{
      "scriptId":"u77"},
    "879caa49301f441c8b520d6cf203f30c":{
      "scriptId":"u78"},
    "e503ba36dde24f3c82c7909b04adb104":{
      "scriptId":"u79"},
    "d85a4d0477564f9391f602eba699df32":{
      "scriptId":"u80"}}});